// Renderer, camera, controls, lighting, puzzle-run data, and shared DOM handles.

const canvas=document.querySelector('#game'),storySelect=document.querySelector('#story-select'),lowPowerMode=(navigator.hardwareConcurrency||8)<=6||matchMedia('(prefers-reduced-motion: reduce)').matches,renderer=new THREE.WebGLRenderer({canvas,antialias:!lowPowerMode,powerPreference:'high-performance'});document.body.classList.toggle('low-power',lowPowerMode);
const chapter=document.querySelector('#chapter'),title=document.querySelector('#title'),description=document.querySelector('#description'),objective=document.querySelector('#objective'),count=document.querySelector('#count'),roomNumber=document.querySelector('#room-number strong'),intro=document.querySelector('#intro');
renderer.setPixelRatio(Math.min(devicePixelRatio,lowPowerMode?1:1.35));renderer.shadowMap.enabled=!lowPowerMode;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.78;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x151511);scene.fog=new THREE.FogExp2(0x1d1c18,.016);
const camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.1,100);camera.position.set(0,1.7,5.5);
const controls=new PointerLockControls(camera,document.body);controls.pointerSpeed=1.1;
const rawMoveForward=controls.moveForward.bind(controls),rawMoveRight=controls.moveRight.bind(controls);function activeMovementModifier(){const floorOneModifier=!floorOne?1:floorOne.cough>0?0:floorOne.exhausted>0?.5:floorOne.lookDown?.8:1,floorTwoModifier=floorTwo&&hotelSideScene.startsWith('floor-two')&&floorTwo.waterSlow?.62:1,vitaminModifier=inventoryEffects?.vitaminsTimer>0?(floorOne?1.3:1.2):1,energyModifier=inventoryEffects?.energyTimer>0?1.18:1;return(floorFive?.slowTimer>0?.45:1)*floorOneModifier*floorTwoModifier*vitaminModifier*energyModifier}controls.moveForward=distance=>{if(hotelHideState)return;const before=camera.position.clone();rawMoveForward(distance*activeMovementModifier());if(playerHitsSolid(camera.position))camera.position.copy(before)};controls.moveRight=distance=>{if(hotelHideState)return;const before=camera.position.clone();rawMoveRight(distance*activeMovementModifier());if(playerHitsSolid(camera.position))camera.position.copy(before)};
scene.add(camera);
scene.add(new THREE.AmbientLight(0xa79c83,.48));
scene.add(new THREE.HemisphereLight(0x8f9694,0x21170f,.62));
const moon=new THREE.DirectionalLight(0x9aa8b8,1.15);moon.position.set(-4,7,4);moon.castShadow=true;scene.add(moon);
const flashlight=new THREE.SpotLight(0xffedc2,240,100,Math.PI/3.2,.45,1.05);flashlight.position.set(.12,-.08,0);flashlight.target.position.set(0,-.05,-1);flashlight.castShadow=true;flashlight.shadow.mapSize.set(2048,2048);flashlight.shadow.bias=-.0004;camera.add(flashlight,flashlight.target);
const inventoryMatchLight=new THREE.PointLight(0xff9b45,0,8,2);inventoryMatchLight.position.set(.25,-.15,-.35);camera.add(inventoryMatchLight);
const inventoryGlowLight=new THREE.PointLight(0x69ffd5,0,17,1.65);inventoryGlowLight.position.set(-.3,-.35,-.55);camera.add(inventoryGlowLight);

function newPuzzleRun(){const pick=list=>list[Math.floor(Math.random()*list.length)],shuffle=list=>[...list].sort(()=>Math.random()-.5);return{warning:pick([['DO NOT','TRUST','THE VOICE','BELOW'],['NEVER','FOLLOW','THE CHILD','DOWNSTAIRS'],['COVER','THE MIRROR','BEFORE','MIDNIGHT']]),ritual:pick([['SALT','HERBS','ASH','BLOOD'],['IRON','WATER','BONE','FIRE'],['BELL','THREAD','WAX','HAIR']]),trophyReverse:Math.random()>.5,cellarTarget:pick([11,13,16]),clockHour:1+Math.floor(Math.random()*11),clockMinute:pick([7,13,22,37,46,53]),mazeBinding:pick([['CUT THE ROOTS','BREAK THE CIRCLE','BURN THE HEART','RUN AT DAWN'],['BREAK THE SEAL','PIERCE THE HEART','LIGHT THE ROOTS','RUN TO THE DOOR'],['SPEAK THE NAME','RING THE BELL','BURN THE MARK','FLEE AT DAWN']]),logOrder:shuffle(['BIRCH','PINE','OAK']),windowWord:pick(['WOLF','DARK','FIND','MOON']),mapRoute:pick([['40° NORTH','120° EAST'],['70° EAST','30° NORTH'],['20° WEST','90° SOUTH']])}}
const puzzleRun=JSON.parse(sessionStorage.getItem('cabin-puzzle-run')||'null')||newPuzzleRun();const savePuzzleRun=()=>sessionStorage.setItem('cabin-puzzle-run',JSON.stringify(puzzleRun));savePuzzleRun();
puzzleRun.hiddenWall||=[['YOU','HAVE','BEEN','HERE'],['THE','CABIN','KNOWS','YOUR NAME'],['NEVER','ANSWER','THE','KNOCKING']][Math.floor(Math.random()*3)];puzzleRun.hiddenRitual||=[['SALT','FIRE','WATER','BONE'],['IRON','WAX','HAIR','ASH'],['BELL','BLOOD','THREAD','SMOKE']][Math.floor(Math.random()*3)];puzzleRun.lockYear||=[1987,1996,2008][Math.floor(Math.random()*3)];puzzleRun.toolOrder||=[['HAMMER','SAW','PLIERS','BAT'],['SAW','PLIERS','HAMMER','BAT'],['PLIERS','HAMMER','SAW','BAT']][Math.floor(Math.random()*3)];savePuzzleRun();
puzzleRun.hotelStart??=[7,13,21][Math.floor(Math.random()*3)];puzzleRun.hotelStep??=[7,11,13][Math.floor(Math.random()*3)];puzzleRun.hotelAnswer??=puzzleRun.hotelStart+puzzleRun.hotelStep*3;puzzleRun.hotelFloor??=[-1,0,404][Math.floor(Math.random()*3)];const hotelWelcomeRooms=[13,14,15];if(!hotelWelcomeRooms.includes(puzzleRun.hotelAssignedRoom))puzzleRun.hotelAssignedRoom=hotelWelcomeRooms[Math.floor(Math.random()*hotelWelcomeRooms.length)];puzzleRun.hotelRoomVariant??=Math.floor(Math.random()*4);savePuzzleRun();
const assignedHotelRoom=puzzleRun.hotelAssignedRoom;
const hotelFloorNumber=5;
const hotelRealityPuzzleUpgrade=puzzleRun.hotelRealityVersion!==2;puzzleRun.hotelFeatures??=['fireplace','clock','aquarium','shrine','sealed-window'].sort(()=>Math.random()-.5);puzzleRun.hotelSymbols??=['△','○','□','◇','✕'].sort(()=>Math.random()-.5);puzzleRun.hotelRealityVersion=2;savePuzzleRun();

const rooms=[
 ['CHAPTER I','The Main Cabin','You wake on splintered floorboards. The windows are boarded from the inside.','Find three pieces of the broken door handle.'],
 ['CHAPTER II','The Bedroom','An empty rocking chair faces a mirror that refuses to show your reflection.','Recover the warning hidden in the mirror.'],
 ['CHAPTER III','The Kitchen','Bundles of herbs hang above bowls marked with ritual symbols.','Reconstruct the cabin owner’s ritual.'],
 ['CHAPTER IV','The Trophy Room','Backpacks and photographs belong to people who vanished in these woods.','Arrange the disappearances in order.'],
 ['CHAPTER V','The Flooded Cellar','Black water covers the floor. Three rusted valves feed a pressure pump above the submerged hatch.',`Set the pump to exactly ${puzzleRun.cellarTarget} PSI and drain the hatch.`],
 ['CHAPTER VI','The Workshop','Rusting tools hang above a workbench. A baseball bat rests in an open vise.','Take something you can defend yourself with.'],
 ['CHAPTER VII','The Playroom','A giant spider hunts across the entire floor. One touch is fatal, so keep moving and use the high platforms.','Avoid its body and hit the spider’s faster throws back five times.'],
 ['CHAPTER VIII','The Root Maze','A vast maze of stone and living roots stretches far beneath the cabin.','Find the glowing heart at the center of the maze.'],
 ['CHAPTER IX','The Infinite Hotel','Fog surrounds the oak entrance of a hotel that already has your name in its guestbook.','Enter the Grand Lobby, complete check-in, and find Room 304.'] ];
