function makeRansackTextSprite(text,color='#fff4da',background='rgba(63,2,6,.94)'){
 const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const context=canvas.getContext('2d');context.fillStyle=background;context.fillRect(12,84,232,88);context.strokeStyle='#f3d8a4';context.lineWidth=8;context.strokeRect(14,86,228,84);context.fillStyle=color;context.font='900 58px monospace';context.textAlign='center';context.textBaseline='middle';context.fillText(text,128,130);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false}));sprite.scale.set(1.22,1.22,1);sprite.renderOrder=20;return sprite
}
function makeRansackAngel(){
 const angel=new THREE.Group();angel.name='Ransack · the mean angel';const robe=mat(0x221116,.72,0x210207),bone=mat(0xd8d0bc,.62),crimson=mat(0x8d1118,.4,0x550006),gold=mat(0xc7a457,.25,0x4a2400),body=new THREE.Mesh(new THREE.ConeGeometry(.72,2.45,9),robe);body.position.y=1.15;angel.add(body);const chest=new THREE.Mesh(new THREE.CapsuleGeometry(.38,.62,6,10),robe);chest.position.y=2.03;angel.add(chest);const head=new THREE.Mesh(new THREE.SphereGeometry(.34,18,12),bone);head.scale.set(.82,1.08,.48);head.position.y=2.82;angel.add(head);
 for(const x of [-.12,.12]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.035,8,6),crimson);eye.position.set(x,2.87,.31);angel.add(eye)}const mouth=new THREE.Mesh(new THREE.BoxGeometry(.2,.025,.025),crimson);mouth.position.set(0,2.68,.32);angel.add(mouth);
 const halo=new THREE.Mesh(new THREE.TorusGeometry(.42,.035,8,28),gold);halo.position.y=3.34;halo.rotation.x=Math.PI/2;angel.add(halo);angel.userData.wings=[];
 for(const side of [-1,1]){const wing=new THREE.Group();wing.position.set(side*.42,2.15,.12);for(let feather=0;feather<6;feather++){const plume=new THREE.Mesh(new THREE.ConeGeometry(.13,.82+feather*.09,5),bone);plume.position.set(side*(.2+feather*.17),-.08-feather*.08,.05+feather*.035);plume.rotation.z=side*(-.72+feather*.09);wing.add(plume)}angel.add(wing);angel.userData.wings.push(wing);const arm=new THREE.Mesh(new THREE.CylinderGeometry(.07,.1,1.05,8),robe);arm.position.set(side*.46,1.92,.38);arm.rotation.z=side*.38;arm.rotation.x=-.48;angel.add(arm)}
 const sign=new THREE.Mesh(new THREE.CircleGeometry(.62,8),new THREE.MeshStandardMaterial({color:0xa70d16,roughness:.5,metalness:.12,emissive:0x4b0004,emissiveIntensity:2,side:THREE.DoubleSide}));sign.name='Ransack stop sign';sign.position.set(0,1.65,.76);angel.add(sign);const stopText=makeRansackTextSprite('STOP');stopText.position.set(0,1.65,.79);stopText.scale.set(.92,.92,1);angel.add(stopText);angel.userData.sign=sign;angel.userData.stopText=stopText;
 const light=new THREE.PointLight(0xff2331,58,10,1.5);light.position.set(0,2.1,.5);angel.add(light);angel.userData.light=light;angel.traverse(child=>{if(child.isMesh){child.castShadow=true;child.renderOrder=8}});scene.add(angel);return angel
}
function playRansackChime(failed=false){try{funAudio||=new AudioContext();const context=funAudio,gain=context.createGain();gain.gain.setValueAtTime(.0001,context.currentTime);gain.gain.exponentialRampToValueAtTime(failed?.24:.15,context.currentTime+.025);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.55);gain.connect(context.destination);for(const [frequency,delay] of (failed?[[110,0],[82,.14],[55,.28]]:[[740,0],[988,.12],[1240,.24]])){const oscillator=context.createOscillator();oscillator.type=failed?'sawtooth':'sine';oscillator.frequency.value=frequency;oscillator.connect(gain);oscillator.start(context.currentTime+delay);oscillator.stop(context.currentTime+delay+.25)}}catch{}}
function ransackPlayerMoving(){return Boolean(keys.KeyW||keys.KeyS||keys.KeyA||keys.KeyD||keys.ArrowUp||keys.ArrowDown||keys.ArrowLeft||keys.ArrowRight||keys.Space||slideTimer>0||Math.abs(verticalVelocity)>.2)}
function ransackExplorationEligible(){
 if(activeStory!=='hotel'||room!==8||inLobby||!storySelect.hidden||dlg?.open||hotelHideState||hotelHideTransition||combat||eviction||noise||hotelNoiseArc||pursuer||molly||collector||clockmaker||drowned||adminMonsters.length||hotelRoomPassage||document.body.classList.contains('admin-open'))return false;
 if(hotelSideScene==='floor5-transition')return true;if(hotelSideScene.startsWith('floor-one-'))return Boolean(floorOne&&[1,3,5,7,9].includes(floorOne.phase));if(hotelSideScene.startsWith('floor-two-'))return Boolean(floorTwo&&[1,3,5,18].includes(floorTwo.phase));return false
}
function setRansackHud(phase,copy,time=0,progress=0){const hud=document.querySelector('#ransack-hud');if(!hud)return;hud.classList.add('active');hud.classList.toggle('failed',phase==='COLLECT');hud.classList.toggle('passed',phase==='PASSED');hud.setAttribute('aria-hidden','false');document.querySelector('#ransack-sign').textContent=phase==='COLLECT'?'FAILED':phase==='PASSED'?'GOOD':'STOP';document.querySelector('#ransack-time').textContent=phase==='COLLECT'?`${ransack.collected} / ${ransack.total}`:phase==='PASSED'?'CLEAR':Math.max(0,time).toFixed(1);document.querySelector('#ransack-progress').style.transform=`scaleX(${THREE.MathUtils.clamp(progress,0,1)})`;document.querySelector('#ransack-instruction').textContent=copy;document.body.dataset.ransackPhase=ransack.phase}
function hideRansackHud(){const hud=document.querySelector('#ransack-hud');hud?.classList.remove('active','failed','passed');hud?.setAttribute('aria-hidden','true');document.body.classList.remove('ransack-stop','ransack-failed');document.body.dataset.ransackPhase=ransack.phase}
function clearRansackObjects(){const doomed=new Set();for(const item of ransackCollectibles){item.group?.removeFromParent();item.trigger?.removeFromParent();doomed.add(item.trigger)}interactables=interactables.filter(item=>!doomed.has(item));ransackCollectibles=[]}
function removeRansackEntity(){if(!ransackEntity)return;ransackEntity.removeFromParent();ransackEntity.traverse(child=>{if(child.isMesh||child.isSprite){child.geometry?.dispose();child.material?.map?.dispose();child.material?.dispose()}});ransackEntity=null}
function finishRansackEvent(countAppearance=true){clearRansackObjects();removeRansackEntity();ransack.phase='waiting';ransack.cooldown=36+Math.random()*18;ransack.timer=0;ransack.deadline=0;ransack.stillStarted=0;ransack.stillTime=0;ransack.eventRoomGroup=null;if(countAppearance){ransack.appearances++;sessionStorage.setItem('hotel-ransack-appearances',String(ransack.appearances))}hideRansackHud()}
function placeRansackEntity(){const forward=new THREE.Vector3();camera.getWorldDirection(forward);forward.y=0;if(forward.lengthSq()<.01)forward.set(0,0,-1);forward.normalize();ransackEntity??=makeRansackAngel();let distance=4.8,candidate=new THREE.Vector3();while(distance>2.4){candidate.set(camera.position.x+forward.x*distance,1.7,camera.position.z+forward.z*distance);if(!playerHitsSolid(candidate))break;distance-=.6}ransackEntity.position.set(candidate.x,0,candidate.z);ransackEntity.lookAt(camera.position.x,1.65,camera.position.z)}
function startRansackEvent(force=false){if(ransack.phase!=='waiting'||!force&&!ransackExplorationEligible())return false;ransack.phase='warning';ransack.timer=3;ransack.deadline=performance.now()+3000;ransack.stillStarted=0;ransack.stillTime=0;ransack.collected=0;ransack.eventRoomGroup=roomGroup;ransack.lastPosition.copy(camera.position);placeRansackEntity();document.body.classList.add('ransack-stop');playRansackChime();setRansackHud('STOP','Release every movement key. Ransack is judging whether you obey.',ransack.timer,1);document.querySelector('#prompt').textContent='RANSACK SAYS STOP · RELEASE ALL MOVEMENT WITHIN 3 SECONDS';return true}
function passRansackStop(){ransack.phase='passed';ransack.resolveTimer=1.65;document.body.classList.remove('ransack-stop');playRansackChime();setRansackHud('PASSED','“Good. You may continue. I wanted a challenge—not your death.”',0,1);document.querySelector('#prompt').textContent='RANSACK: “GOOD. YOU LISTENED.”'}
function ransackCollectiblePosition(index){const boundary=Math.max(5,(pursuer?.boundary||floorTwo?.boundary||floorOne?.boundary||13)-1.2);for(let attempt=0;attempt<14;attempt++){const angle=index*Math.PI*2/3+attempt*.71,distance=3.1+(attempt%4)*.7,candidate=new THREE.Vector3(THREE.MathUtils.clamp(camera.position.x+Math.cos(angle)*distance,-boundary,boundary),1.05,THREE.MathUtils.clamp(camera.position.z+Math.sin(angle)*distance,-boundary,boundary));if(!playerHitsSolid(candidate)&&candidate.distanceTo(camera.position)>2.1)return candidate}return new THREE.Vector3(THREE.MathUtils.clamp(camera.position.x+(index-1)*2.3,-boundary,boundary),1.05,THREE.MathUtils.clamp(camera.position.z-3.2,-boundary,boundary))}
function spawnRansackCollectibles(){clearRansackObjects();for(let index=0;index<ransack.total;index++){const position=ransackCollectiblePosition(index),group=new THREE.Group();group.name=`Ransack red mark ${index+1}`;group.position.copy(position);const mark=new THREE.Mesh(new THREE.OctahedronGeometry(.34,0),mat(0xb6111d,.3,0x6d0007)),ring=new THREE.Mesh(new THREE.TorusGeometry(.48,.035,7,20),mat(0xe4bd6c,.24,0x5d2700));ring.rotation.x=Math.PI/2;group.add(mark,ring);const glow=new THREE.PointLight(0xff2638,45,6,1.7);group.add(glow);roomGroup.add(group);const trigger=interactive([position.x,position.y,position.z],[1.5,2.2,1.5],8,'ransack',`mark:${index}`),item={group,trigger,index,phase:index*2.1};trigger.userData.ransackCollectible=item;ransackCollectibles.push(item)}}
function failRansackStop(){ransack.phase='collect';ransack.collected=0;document.body.classList.remove('ransack-stop');document.body.classList.add('ransack-failed');playRansackChime(true);spawnRansackCollectibles();setRansackHud('COLLECT','Ransack sealed the route. Collect all three red marks to continue.',0,0);document.querySelector('#prompt').textContent='RANSACK: “TOO SLOW. COLLECT MY THREE RED MARKS.”'}
function collectRansackMark(object){if(ransack.phase!=='collect')return;const item=object.userData.ransackCollectible;if(!item||!ransackCollectibles.includes(item))return;item.group.removeFromParent();item.trigger.removeFromParent();interactables=interactables.filter(entry=>entry!==item.trigger);ransackCollectibles=ransackCollectibles.filter(entry=>entry!==item);ransack.collected++;playFirstPersonAction('pickup','brass-token',.6);pickupTone();if(ransack.collected>=ransack.total){ransack.phase='passed';ransack.resolveTimer=2;document.body.classList.remove('ransack-failed');setRansackHud('PASSED','“That will do. I was never trying to kill you.”',0,1);document.querySelector('#prompt').textContent='RANSACK: “THAT WILL DO. CONTINUE.”'}else{setRansackHud('COLLECT',`Collect the remaining red marks. ${ransack.total-ransack.collected} left.`,0,ransack.collected/ransack.total);document.querySelector('#prompt').textContent=`RANSACK MARK COLLECTED · ${ransack.collected} / ${ransack.total}`}}
function ransackBlocksExit(data){if(!['warning','collect'].includes(ransack.phase)||data.type==='ransack')return false;const part=String(data.part||''),exitType=['hotel-run-exit','hotel-floor-one-exit','hotel-door','hotel-elevator'].includes(data.type),exitPart=part==='exit'||part==='transition-exit'||part.includes('elevator')||part.includes('lost-property')||part.includes('clock-tower')||part.includes('flooded-atrium');if(!exitType&&!exitPart)return false;document.querySelector('#prompt').textContent=ransack.phase==='warning'?'RANSACK SEALED THE ROUTE · OBEY THE STOP SIGN':'RANSACK SEALED THE ROUTE · COLLECT ALL THREE RED MARKS';return true}
function updateRansack(dt,time){
 if(ransack.phase==='waiting'){document.body.dataset.ransackPhase='waiting';if(!ransackExplorationEligible()){ransack.lastPosition.copy(camera.position);return}ransack.cooldown=Math.max(0,ransack.cooldown-dt);if(ransack.cooldown<=0&&ransackPlayerMoving())startRansackEvent();ransack.lastPosition.copy(camera.position);return}
 if(ransack.eventRoomGroup!==roomGroup||activeStory!=='hotel'||room!==8){finishRansackEvent(false);return}if(ransackEntity){ransackEntity.lookAt(camera.position.x,1.65,camera.position.z);ransackEntity.position.y=Math.sin(time*2.2)*.08;ransackEntity.userData.wings.forEach((wing,index)=>wing.rotation.y=Math.sin(time*3.1+index*Math.PI)*.16);ransackEntity.userData.sign.rotation.z=Math.sin(time*2.8)*.025;ransackEntity.userData.light.intensity=42+Math.sin(time*9)*12}
 for(const item of ransackCollectibles){item.group.rotation.y+=dt*.9;item.group.position.y=1.05+Math.sin(time*2.5+item.phase)*.13}
 if(ransack.phase==='warning'){const now=performance.now(),keyMovement=ransackPlayerMoving(),positionMovement=camera.position.distanceTo(ransack.lastPosition)>.035,moving=keyMovement||positionMovement;ransack.timer=Math.max(0,(ransack.deadline-now)/1000);if(moving){ransack.stillStarted=0;ransack.stillTime=0}else{ransack.stillStarted||=now;ransack.stillTime=(now-ransack.stillStarted)/1000}document.body.dataset.ransackStill=ransack.stillTime.toFixed(3);document.body.dataset.ransackMotion=keyMovement?'keys':positionMovement?'position':'still';setRansackHud('STOP',moving?'Release every movement key. Ransack is still watching.':'Hold still…',ransack.timer,ransack.timer/3);if(ransack.stillTime>=.28)passRansackStop();else if(ransack.timer<=0)failRansackStop()}
 else if(ransack.phase==='passed'){ransack.resolveTimer-=dt;if(ransack.resolveTimer<=0)finishRansackEvent(true)}ransack.lastPosition.copy(camera.position)
}
