function setStability(value){stability=THREE.MathUtils.clamp(value,0,100);document.querySelector('#stability-fill').style.width=`${stability}%`;document.querySelector('#stability-text').textContent=`COMPOSURE ${Math.ceil(stability)}%`}
function adminPreventDeath(reason='DAMAGE BLOCKED'){
 if(!adminInvincible)return false;setStability(100);if(adminHitCooldown<=0){adminHitCooldown=1.25;document.querySelector('#prompt').textContent=`ADMIN INVINCIBILITY · ${reason}`;pickupTone()}return true
}
function makeAdminMonsterModel(kind){
 if(kind==='molly'&&typeof makeMollyModel==='function')return makeMollyModel(true);
 if(kind==='spider'){const spider=makeGiantSpider();spider.scale.setScalar(.72);return spider}
 const group=new THREE.Group(),dark=mat(0x171315,.78),iron=mat(0x4d5558,.24),red=mat(0x48110e,.45,0x7c0d08);
 const humanoid=(clothColor=0x171315,scale=1,skinColor=0x655049)=>{const cloth=mat(clothColor,.72),skin=mat(skinColor,.66),body=new THREE.Mesh(new THREE.CapsuleGeometry(.42*scale,1.2*scale,7,12),cloth),head=new THREE.Mesh(new THREE.SphereGeometry(.34*scale,14,10),skin),arms=[];body.position.y=1.35*scale;head.position.y=2.35*scale;group.add(body,head);for(const side of [-1,1]){const arm=new THREE.Mesh(new THREE.CylinderGeometry(.07*scale,.11*scale,1.25*scale,7),cloth);arm.position.set(side*.55*scale,1.35*scale,0);arm.rotation.z=side*.22;arm.userData.humanoidArm=side;group.add(arm);arms.push(arm)}group.userData.humanoidArms=arms;return{body,head,cloth,skin,arms}}
 if(kind==='bash'){
  const body=new THREE.Mesh(new THREE.CapsuleGeometry(.78,1.8,7,12),dark);body.position.y=1.55;body.scale.set(1.25,1,1);group.add(body);
  const skull=new THREE.Mesh(new THREE.SphereGeometry(.5,12,9),red);skull.position.set(0,2.75,.25);group.add(skull);
  for(const side of [-1,1]){const shoulder=new THREE.Mesh(new THREE.BoxGeometry(1.1,.55,.8),iron);shoulder.position.set(side*.9,2.15,0);shoulder.rotation.z=side*.18;group.add(shoulder);const arm=new THREE.Mesh(new THREE.CylinderGeometry(.13,.22,2.35,7),dark);arm.position.set(side*1.05,1.25,.12);arm.rotation.z=side*.34;group.add(arm)}
  for(const side of [-1,1]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.075,8,6),mat(0xf5d28a,.25,0xff4a16));eye.position.set(side*.17,2.82,.7);group.add(eye)}
 }else if(kind==='purge'){
  for(let n=0;n<5;n++){const gear=new THREE.Mesh(new THREE.TorusGeometry(.65+n*.18,.11,7,14),n%2?iron:red);gear.rotation.set(n%2?Math.PI/2:0,n*.7,n*.35);group.add(gear)}for(let n=0;n<8;n++){const tooth=new THREE.Mesh(new THREE.ConeGeometry(.14,.8,5),iron);const angle=n/8*Math.PI*2;tooth.position.set(Math.cos(angle)*1.25,Math.sin(angle)*1.25,0);tooth.rotation.z=-angle;group.add(tooth)}group.position.y=1.7;
 }else if(kind==='noise'){
  const face=new THREE.Mesh(new THREE.BoxGeometry(1.45,1,.35),mat(0xdfe5e6,.15,0xffffff));face.position.y=2.25;group.add(face);for(const side of [-1,1]){const antenna=new THREE.Mesh(new THREE.CylinderGeometry(.035,.09,2,6),iron);antenna.position.set(side*.65,3.35,0);antenna.rotation.z=side*.35;group.add(antenna);const limb=new THREE.Mesh(new THREE.CylinderGeometry(.06,.15,2.7,6),dark);limb.position.set(side*.85,1,0);limb.rotation.z=side*.62;group.add(limb)}
 }else if(kind==='cable-mass'){
  for(let n=0;n<5;n++){const gear=new THREE.Mesh(new THREE.TorusGeometry(.5+n*.23,.1,7,16),mat(n%2?0x6b3825:0x292f31,.28,0x092532));gear.rotation.set(n%2?Math.PI/2:0,n*.5,n*.72);group.add(gear)}for(let n=0;n<7;n++){const cable=new THREE.Mesh(new THREE.CylinderGeometry(.035,.1,2.8+n*.15,6),iron);cable.position.set((n-3)*.28,(n%2-.5)*.35,0);cable.rotation.z=(n-3)*.16;group.add(cable)}
 }else if(kind==='pursuer'){
  const suit=mat(0x11151a,.84),shirt=mat(0x3a3b3c,.78),maskMat=mat(0xd8d4c8,.25),voidMat=mat(0x020203,.4),body=new THREE.Mesh(new THREE.CapsuleGeometry(.4,2.25,7,12),suit);body.position.y=1.9;body.scale.set(.82,1.18,.72);group.add(body);const shirtFront=new THREE.Mesh(new THREE.BoxGeometry(.36,1.55,.12),shirt);shirtFront.position.set(0,2.05,.39);group.add(shirtFront);const mask=new THREE.Mesh(new THREE.SphereGeometry(.39,18,12),maskMat);mask.scale.set(.88,1.14,.4);mask.position.set(0,3.55,.32);group.add(mask);for(const side of [-1,1]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.09,10,7),voidMat);eye.scale.set(.72,1.25,.45);eye.position.set(side*.15,3.63,.48);group.add(eye);const arm=new THREE.Mesh(new THREE.CylinderGeometry(.065,.105,2.55,7),suit);arm.position.set(side*.54,1.65,.02);arm.rotation.z=side*.08;group.add(arm);arm.userData.pursuerLimb=side}const mouth=new THREE.Mesh(new THREE.TorusGeometry(.17,.04,6,14,Math.PI),voidMat);mouth.position.set(0,3.39,.49);mouth.rotation.z=Math.PI;group.add(mouth);for(const side of [-1,1]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.08,.13,1.9,7),suit);leg.position.set(side*.2,.58,0);leg.rotation.z=side*.04;leg.userData.pursuerLeg=side;group.add(leg)}group.userData.pursuerBody=body;
 }else if(kind==='drowned-guest'){
  const figure=humanoid(0x172b32,1.28,0xc9c8bc);figure.body.scale.set(1.18,1,1);const coatTail=new THREE.Mesh(new THREE.BoxGeometry(1.12,1.65,.42),mat(0x13272e,.86));coatTail.position.set(0,.72,-.08);group.add(coatTail);const mask=new THREE.Mesh(new THREE.SphereGeometry(.37,18,12),mat(0xe1ddd0,.24));mask.scale.set(1,.92,.38);mask.position.set(0,3.03,.33);group.add(mask);for(const side of [-1,1]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.07,9,7),mat(0x020405,.35));eye.position.set(side*.14,3.08,.47);group.add(eye)}const smile=new THREE.Mesh(new THREE.TorusGeometry(.11,.018,5,12,Math.PI),mat(0x5f4845,.4));smile.position.set(0,2.92,.48);smile.rotation.z=Math.PI;group.add(smile);const key=new THREE.Mesh(new THREE.BoxGeometry(.12,.42,.05),mat(0xb4904e,.2,0x4a3512));key.position.set(0,1.82,.58);group.add(key);const bow=new THREE.Mesh(new THREE.BoxGeometry(.48,.16,.08),mat(0x351519));bow.position.set(0,2.2,.5);bow.rotation.z=.08;group.add(bow);for(let n=0;n<8;n++){const drop=new THREE.Mesh(new THREE.SphereGeometry(.025+.02*Math.random(),6,4),mat(0x4d9aa7,.25,0x113b43));drop.position.set((Math.random()-.5)*1.2,.4+Math.random()*2.4,(Math.random()-.5)*.6);group.add(drop)}
 }else if(['watcher','window-creature','gardener','false-guest','ballroom-guest','stair-monster'].includes(kind)){
  const colors={watcher:0x050607,'window-creature':0x07090b,gardener:0x263b29,'false-guest':0x4a3038,'ballroom-guest':0x38242e,'stair-monster':0x160b0c},figure=humanoid(colors[kind],kind==='watcher'?1.35:kind==='stair-monster'?1.18:1,kind==='false-guest'?0x9b7b69:0x23201e);if(kind==='watcher'){figure.head.scale.set(.72,1.5,.7);for(const x of [-.12,.12]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.045,8,6),mat(0xe6e0cd,.2,0x8b150d));eye.position.set(x,2.42,.3);group.add(eye)}}else if(kind==='gardener'){const shovel=new THREE.Mesh(new THREE.BoxGeometry(.13,2.6,.13),iron);shovel.position.set(.75,1.15,.2);shovel.rotation.z=-.18;group.add(shovel);const blade=new THREE.Mesh(new THREE.BoxGeometry(.6,.65,.1),iron);blade.position.set(.98,.02,.2);group.add(blade)}else if(kind==='window-creature'){const frame=new THREE.Mesh(new THREE.BoxGeometry(1.45,2.9,.12),mat(0x27333a,.32));frame.position.y=1.4;group.add(frame);figure.head.material.emissive.setHex(0x561017);figure.head.material.emissiveIntensity=1.4}else{const mask=new THREE.Mesh(new THREE.BoxGeometry(.52,.4,.09),mat(kind==='false-guest'?0xd7c6af:0xc9c0af,.3));mask.position.set(0,2.37,.3);group.add(mask);if(kind==='false-guest')for(const side of [-1,1]){const extra=new THREE.Mesh(new THREE.CylinderGeometry(.04,.1,1.6,6),dark);extra.position.set(side*.7,.85,.15);extra.rotation.z=side*.8;group.add(extra)}}
 }else if(['luggage-warden','empty-porter','black-bellhop','reflection','hotel-manager','night-auditor'].includes(kind)){
  const colors={'luggage-warden':0x442b23,'empty-porter':0x202329,'black-bellhop':0x280d14,reflection:0x2d3541,'hotel-manager':0x3f2529,'night-auditor':0x17191d},figure=humanoid(colors[kind],kind==='luggage-warden'?1.18:1,kind==='empty-porter'?0x0b0b0c:0x8b6d5d);if(kind==='luggage-warden'){for(const side of [-1,1]){const trunk=new THREE.Mesh(new THREE.BoxGeometry(.95,.75,.55),mat(0x503426));trunk.position.set(side*.8,.75,.1);group.add(trunk)}}else if(kind==='empty-porter'){figure.head.material.color.setHex(0x08090a);const glove=new THREE.Mesh(new THREE.SphereGeometry(.16,10,7),mat(0xd5d1c8));glove.position.set(.68,1.7,.3);group.add(glove)}else if(kind==='black-bellhop'){const cap=new THREE.Mesh(new THREE.CylinderGeometry(.38,.4,.17,14),mat(0x390f17));cap.position.y=2.72;group.add(cap);const bell=new THREE.Mesh(new THREE.SphereGeometry(.2,12,8),mat(0xc19a4d,.25,0x5b3008));bell.position.set(.72,1,.35);group.add(bell)}else if(kind==='reflection'){group.scale.x=-1;figure.head.material.metalness=.65;figure.head.material.color.setHex(0x8895a0)}else if(kind==='hotel-manager'){const badge=new THREE.Mesh(new THREE.BoxGeometry(.42,.22,.06),mat(0xb38a47));badge.position.set(.2,1.55,.43);group.add(badge)}else{const ledger=new THREE.Mesh(new THREE.BoxGeometry(.85,.12,.65),mat(0x3b2218));ledger.position.set(0,1.2,.62);group.add(ledger)}
 }else if(kind==='clockmaker'){
  const brass=mat(0xb78b3c,.24,0x362005),coat=mat(0x30271d,.76),voidMat=mat(0x060606,.35),body=new THREE.Mesh(new THREE.CapsuleGeometry(.5,1.75,7,12),coat);body.position.y=1.55;group.add(body);const face=new THREE.Mesh(new THREE.CylinderGeometry(.46,.46,.18,24),brass);face.rotation.x=Math.PI/2;face.position.set(0,2.75,.16);group.add(face);const faceVoid=new THREE.Mesh(new THREE.CircleGeometry(.35,20),voidMat);faceVoid.position.set(0,2.75,.27);group.add(faceVoid);const hands=[];for(const [length,width,angle] of [[.28,.035,.2],[.36,.025,1.5]]){const hand=new THREE.Mesh(new THREE.BoxGeometry(width,length,.025),brass);hand.position.set(0,2.75+length/2,.3);hand.rotation.z=angle;group.add(hand);hands.push(hand)}for(let n=0;n<7;n++){const gear=new THREE.Mesh(new THREE.TorusGeometry(.12+n*.018,.025,6,12),n%2?brass:voidMat);gear.position.set((n%3-1)*.22,2.68+Math.floor(n/3)*.22,.31);gear.rotation.z=n*.7;group.add(gear)}const keyStem=new THREE.Mesh(new THREE.BoxGeometry(.12,.82,.12),brass);keyStem.position.set(0,1.8,-.58);group.add(keyStem);for(const side of [-1,1]){const loop=new THREE.Mesh(new THREE.TorusGeometry(.24,.055,7,14),brass);loop.position.set(side*.23,2.15,-.58);loop.rotation.y=Math.PI/2;group.add(loop)}group.userData.clockHands=hands;
 }else if(kind==='collector'){
  const coat=mat(0x271f1d,.86),leather=mat(0x4b3023,.72),brass=mat(0xb28a43,.26,0x2c1805),body=new THREE.Mesh(new THREE.CapsuleGeometry(.58,2.05,7,12),coat);body.position.y=1.65;group.add(body);const hood=new THREE.Mesh(new THREE.SphereGeometry(.42,12,9),mat(0x0a0909));hood.position.set(0,2.95,.05);group.add(hood);const bag=new THREE.Mesh(new THREE.SphereGeometry(.92,12,10),leather);bag.scale.set(.8,1.28,.58);bag.position.set(0,1.6,-.62);group.add(bag);for(const side of [-1,1]){const strap=new THREE.Mesh(new THREE.BoxGeometry(.12,2.5,.1),leather);strap.position.set(side*.35,1.75,.48);strap.rotation.z=side*.12;group.add(strap)}for(let n=0;n<9;n++){const key=new THREE.Group(),ring=new THREE.Mesh(new THREE.TorusGeometry(.075,.018,5,9),brass),stem=new THREE.Mesh(new THREE.BoxGeometry(.03,.28,.025),brass);stem.position.y=-.18;key.add(ring,stem);key.position.set((n%3-1)*.28,1.15+Math.floor(n/3)*.36,.55);key.rotation.z=(n-4)*.08;group.add(key)}
 }else if(kind==='chef'){
  const body=new THREE.Mesh(new THREE.CapsuleGeometry(.68,1.7,7,12),mat(0xd8d1c5,.7));body.position.y=1.55;group.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.46,14,10),mat(0x936d59));head.position.y=2.75;group.add(head);const hat=new THREE.Mesh(new THREE.CylinderGeometry(.55,.38,.75,12),mat(0xeee7dc));hat.position.y=3.3;group.add(hat);const cleaver=new THREE.Mesh(new THREE.BoxGeometry(.12,.8,1),iron);cleaver.position.set(.85,1.65,.25);group.add(cleaver);
 }else{
  const body=new THREE.Mesh(new THREE.CapsuleGeometry(.58,1.8,7,12),dark);body.position.y=1.5;group.add(body);for(let n=0;n<7;n++){const root=new THREE.Mesh(new THREE.CylinderGeometry(.04,.13,2.3,6),mat(0x3b2115));root.position.set((n-3)*.22,.7,0);root.rotation.z=(n-3)*.08;group.add(root)}const eye=new THREE.Mesh(new THREE.SphereGeometry(.18,10,8),red);eye.position.set(0,2.6,.5);group.add(eye)
 }
 group.name=`admin monster ${kind}`;group.traverse(child=>{if(child.isMesh){child.castShadow=true;child.receiveShadow=true}});return group
}
function clearAdminMonsters(){
 if(bashSpawnHandle){clearTimeout(bashSpawnHandle);bashSpawnHandle=null}if(randomRoomMonsterHandle){clearTimeout(randomRoomMonsterHandle);randomRoomMonsterHandle=null}for(const monster of adminMonsters)monster.mesh?.removeFromParent();adminMonsters=[];document.body.classList.remove('bash-warning','bash-rush');delete document.querySelector('#prompt')?.dataset.randomMonster;delete document.body.dataset.randomMonsterPending
}
function adminMonsterHit(monster){
 if(monster.hit)return;if(adminPreventDeath(`${monster.name.toUpperCase()} COULD NOT HURT YOU`)){monster.hit=true;return}monster.hit=true;journalDiscover(monster.type,2);adminHitCooldown=1.8;setStability(0);controls.unlock();horrorStinger();const reason=monster.type==='bash'?'BASH RAN THROUGH YOU':`${monster.name.toUpperCase()} CAUGHT YOU`;playMonsterJumpscare(monster.type,monster.name,reason,1050);const blackout=document.querySelector('#blackout');blackout.querySelector('span').textContent=reason;blackout.classList.add('show');setTimeout(()=>{camera.position.copy(monster.safePosition);setStability(65);blackout.classList.remove('show');blackout.querySelector('span').textContent='You wake inside the cabin.';monster.mesh?.removeFromParent();adminMonsters=adminMonsters.filter(entry=>entry!==monster);if(!dlg.open&&!document.querySelector('#admin-panel:not([hidden])')&&storySelect.hidden)controls.lock()},1050)
}
function adminMonsterPlatforms(){
 if(mazeEscape&&mazeEscapePlatforms.length)return mazeEscapePlatforms;if(room===6&&playroomPlatforms.length)return playroomPlatforms;if(hotelStairPlatforms.length)return hotelStairPlatforms;return[]
}
function adminMonsterFloorAt(position,maxY=Infinity,stepHeight=.65){
 let floor=0;for(const platform of adminMonsterPlatforms()){if(platform.disabled||platform.mesh&&!platform.mesh.parent)continue;const dx=position.x-platform.x,dz=position.z-platform.z,c=Math.cos(-(platform.rotation||0)),s=Math.sin(-(platform.rotation||0)),localX=dx*c-dz*s,localZ=dx*s+dz*c;if(Math.abs(localX)>platform.halfX+.08||Math.abs(localZ)>platform.halfZ+.08||platform.top>maxY+stepHeight)continue;floor=Math.max(floor,platform.top)}return floor
}
function adminMonsterHitsSolid(monster,position,ground,forceWalls=false){
 if(monster.phaseWalls&&!forceWalls)return false;const radius=monster.radius||.62,bottom=ground+.08,top=ground+(monster.height||3.35);for(const collider of solidColliders){if(!collider.mesh.parent||top<=collider.bottom+.04||bottom>=collider.top-.04)continue;const dx=position.x-collider.mesh.position.x,dz=position.z-collider.mesh.position.z,c=Math.cos(-(collider.mesh.rotation.y||0)),s=Math.sin(-(collider.mesh.rotation.y||0)),localX=dx*c-dz*s,localZ=dx*s+dz*c;if(Math.abs(localX)<collider.halfX+radius&&Math.abs(localZ)<collider.halfZ+radius)return true}return false
}
function adminMonsterPlacement(monster,position,currentGround=playerFeetY,forceWalls=false){
 const stepHeight=monster.stepHeight||.65,ground=adminMonsterFloorAt(position,currentGround,stepHeight);if(currentGround>.7&&ground<currentGround-Math.max(.8,stepHeight))return null;if(adminMonsterHitsSolid(monster,position,ground,forceWalls))return null;return ground
}
function adminMonsterSegmentBlocked(monster,start,end){
 const distance=start.distanceTo(end),steps=Math.max(2,Math.ceil(distance/.45));for(let index=1;index<steps;index++){const position=start.clone().lerp(end,index/steps),ground=adminMonsterFloorAt(position,monster.groundY,monster.stepHeight||.65);if(adminMonsterHitsSolid(monster,position,ground,true))return true}return false
}
function findAdminMonsterSpawn(monster,forward,distance){
 const side=new THREE.Vector3(-forward.z,0,forward.x),fallback=[];for(const offset of [0,2,-2,4,-4])for(let range=distance;range>=3;range-=1){const position=new THREE.Vector3(camera.position.x,0,camera.position.z).addScaledVector(forward,range).addScaledVector(side,offset),ground=adminMonsterPlacement(monster,position,playerFeetY,true);if(ground==null)continue;const option={position,ground};fallback.push(option);if(!adminMonsterSegmentBlocked(monster,new THREE.Vector3(camera.position.x,playerFeetY,camera.position.z),new THREE.Vector3(position.x,ground,position.z)))return option}return fallback[0]||null
}
function placeAdminMonster(monster,position,currentGround=monster.groundY){
 const ground=adminMonsterPlacement(monster,position,currentGround);if(ground==null)return false;monster.mesh.position.x=position.x;monster.mesh.position.z=position.z;monster.groundY=ground;monster.mesh.position.y=ground+monster.hover;return true
}
function moveAdminMonsterStep(monster,direction,distance){
 const origin=monster.mesh.position.clone(),candidate=origin.clone().addScaledVector(direction,distance);if(placeAdminMonster(monster,candidate))return true;if(monster.phaseWalls)return false;
 const axes=[new THREE.Vector3(direction.x,0,0),new THREE.Vector3(0,0,direction.z)];axes.sort((a,b)=>b.lengthSq()-a.lengthSq());for(const axis of axes)if(axis.lengthSq()>.0001&&placeAdminMonster(monster,origin.clone().addScaledVector(axis.normalize(),distance)))return true;
 const left=new THREE.Vector3(-direction.z,0,direction.x),right=left.clone().negate(),turns=monster.turnSign>0?[left,right]:[right,left];for(const turn of turns)if(placeAdminMonster(monster,origin.clone().addScaledVector(turn,distance))){monster.turnSign*=-1;return true}return false
}
function moveAdminMonster(monster,direction,distance){
 if(!direction||direction.lengthSq()<.0001||distance<=0)return true;direction=direction.clone().setY(0).normalize();const steps=Math.max(1,Math.ceil(distance/.25)),stepDistance=distance/steps;for(let step=0;step<steps;step++)if(!moveAdminMonsterStep(monster,direction,stepDistance))return false;return true
}
function adminMonsterWatched(monster){
 const view=new THREE.Vector3();camera.getWorldDirection(view);view.y=0;view.normalize();const towardMonster=new THREE.Vector3(monster.mesh.position.x-camera.position.x,0,monster.mesh.position.z-camera.position.z);return towardMonster.lengthSq()>.001&&view.dot(towardMonster.normalize())>.92
}
function adminMonsterTargetDirection(monster,target){return new THREE.Vector3(target.x-monster.mesh.position.x,0,target.z-monster.mesh.position.z)}
function adminMonsterHearsPlayer(monster,{mossMuffles=false}={}){
 const moving=keys.KeyW||keys.ArrowUp||keys.KeyS||keys.ArrowDown||keys.KeyA||keys.ArrowLeft||keys.KeyD||keys.ArrowRight,crouched=keys.KeyC||keys.ControlLeft||keys.ControlRight,onMoss=mossMuffles&&floorTwoMoss.some(moss=>Math.abs(camera.position.x-moss.x)<moss.halfX&&Math.abs(camera.position.z-moss.z)<moss.halfZ);if(!moving||crouched||onMoss)return 0;return keys.ShiftLeft||keys.ShiftRight?1.65:1
}
function adminMonsterInvestigateSound(monster,dt,strength){
 if(strength){monster.lastHeardPosition.copy(camera.position);monster.soundMemory=strength>1?3.8:2.6}else monster.soundMemory=Math.max(0,monster.soundMemory-dt);if(monster.soundMemory<=0)return null;const direction=adminMonsterTargetDirection(monster,monster.lastHeardPosition);if(direction.length()<.35){monster.soundMemory=0;return null}return direction.normalize()
}
function adminMonsterIntent(monster,toPlayer,distance,dt,time){
 const direct=toPlayer.clone().setY(0).normalize(),side=new THREE.Vector3(-direct.z,0,direct.x),cycle=(time+monster.seed)%4;monster.speedScale=1;
 if(monster.behavior==='sound-hunt'){const strength=adminMonsterHearsPlayer(monster),investigation=adminMonsterInvestigateSound(monster,dt,strength);if(!investigation){monster.speedScale=0;return new THREE.Vector3()}monster.speedScale=strength>1?1.65:strength?1.15:.72;return investigation.addScaledVector(side,Math.sin(time*5+monster.seed)*.12).normalize()}
 if(monster.behavior==='molly-listen'){const strength=adminMonsterHearsPlayer(monster),investigation=adminMonsterInvestigateSound(monster,dt,strength);if(!investigation){monster.speedScale=0;return new THREE.Vector3()}monster.speedScale=strength>1?1.45:strength?.8:.62;return investigation}
 if(monster.behavior==='knife-flank'){monster.specialTimer-=dt;if(monster.specialTimer<=0){monster.turnSign*=-1;monster.specialTimer=1.1}monster.speedScale=distance<3?1.4:.82;const target=camera.position.clone().addScaledVector(side,monster.turnSign*(distance<3?1.4:3.2));return adminMonsterTargetDirection(monster,target).normalize()}
 if(monster.behavior==='possessions-guard'){const fromAnchor=monster.anchorPosition?monster.mesh.position.clone().sub(monster.anchorPosition):new THREE.Vector3(),tooFar=fromAnchor.length()>5.5;if(tooFar){monster.speedScale=1.25;return adminMonsterTargetDirection(monster,monster.anchorPosition).normalize()}monster.speedScale=distance>4.2?.9:.55;return(distance>4.2?direct:side.multiplyScalar(monster.turnSign).addScaledVector(direct,.18)).normalize()}
 if(monster.behavior==='clockwork-step'){const beat=(time+monster.seed)%1;monster.speedScale=beat<.16?2.35:0;if(beat>=.16)return new THREE.Vector3();return direct}
 if(monster.behavior==='spider-pounce'){const pounce=(time+monster.seed)%3.2;if(pounce<.7){monster.speedScale=0;monster.mesh.scale.y=.62}else if(pounce<1.28){monster.speedScale=2.25;monster.mesh.scale.y=.82}else{monster.speedScale=.48;monster.mesh.scale.y=.72}return direct}
 if(monster.behavior==='root-stalk'){monster.speedScale=adminMonsterWatched(monster)?.18:1.22;return direct.addScaledVector(side,Math.sin(time*1.7+monster.seed)*.22).normalize()}
 if(monster.behavior==='stair-zigzag'){monster.speedScale=.9;const step=Math.floor((time+monster.seed)*1.7)%2?1:-1;return direct.addScaledVector(side,step*.82).normalize()}
 if(monster.behavior==='tag-circle'){monster.speedScale=distance<2.8?1.35:.78;const inward=distance<2.8?1:.32;return direct.multiplyScalar(inward).addScaledVector(side,monster.turnSign*.95).normalize()}
 if(monster.behavior==='gaze-freeze'){if(adminMonsterWatched(monster)){monster.speedScale=0;document.querySelector('#prompt').textContent='THE WATCHER STOPS WHILE YOU LOOK AT IT'}return direct}
 if(monster.behavior==='water-heavy'){monster.speedScale=cycle<2.8?.58:cycle<3.45?1.75:.32;monster.mesh.rotation.z=Math.sin(time*2.1+monster.seed)*.025;return direct.addScaledVector(side,Math.sin(time*.9+monster.seed)*.18).normalize()}
 if(monster.behavior==='relentless-cutoff'){monster.speedScale=distance>6?1.2:.84;monster.mesh.rotation.z=Math.sin(time*13+monster.seed)*.055;const view=new THREE.Vector3();camera.getWorldDirection(view);view.y=0;const target=camera.position.clone().addScaledVector(view,distance>6?3.8:1.2);return adminMonsterTargetDirection(monster,target).normalize()}
 if(monster.behavior==='garden-patrol'){const strength=adminMonsterHearsPlayer(monster,{mossMuffles:true}),investigation=adminMonsterInvestigateSound(monster,dt,strength);if(investigation){monster.speedScale=strength?1.05:.82;return investigation}monster.specialTimer-=dt;if(monster.specialTimer<=0){monster.patrolAngle=(monster.patrolAngle||0)+Math.PI*.72;monster.specialTimer=2.6}const target=monster.anchorPosition.clone();target.x+=Math.cos(monster.patrolAngle||0)*4.2;target.z+=Math.sin(monster.patrolAngle||0)*4.2;monster.speedScale=.58;return adminMonsterTargetDirection(monster,target).normalize()}
 if(monster.behavior==='window-ambush'){if(cycle<1.45)monster.speedScale=.08;else if(cycle<2.15)monster.speedScale=2.05;else monster.speedScale=.42;return direct}
 if(monster.behavior==='false-feint'){if(cycle<1.65)return direct;if(cycle<2.45){monster.speedScale=1.25;return direct.negate()}monster.speedScale=.72;return side.multiplyScalar(monster.turnSign).addScaledVector(direct,.2).normalize()}
 if(monster.behavior==='luggage-block'){const view=new THREE.Vector3();camera.getWorldDirection(view);view.y=0;const target=camera.position.clone().addScaledVector(view,2);monster.speedScale=distance<3?.42:.82;return adminMonsterTargetDirection(monster,target).addScaledVector(side,Math.sin(time+monster.seed)*.3).normalize()}
 if(monster.behavior==='porter-blink'){monster.specialTimer-=dt;if(monster.specialTimer<=0&&distance>3){moveAdminMonster(monster,direct,Math.min(1.7,distance-2));monster.specialTimer=2.4}monster.speedScale=.55;return direct}
 if(monster.behavior==='bellhop-charge'){if(cycle<1.25)monster.speedScale=.12;else if(cycle<2.05)monster.speedScale=2.15;else monster.speedScale=.52;return direct}
 if(monster.behavior==='mirror-copy'){const playerDelta=camera.position.clone().sub(monster.lastPlayerPosition);monster.lastPlayerPosition.copy(camera.position);playerDelta.y=0;monster.speedScale=playerDelta.lengthSq()>.0001?1.15:.32;return direct.addScaledVector(new THREE.Vector3(-playerDelta.x,0,-playerDelta.z).normalize(),.65).normalize()}
 if(monster.behavior==='manager-cutoff'){const view=new THREE.Vector3();camera.getWorldDirection(view);view.y=0;return adminMonsterTargetDirection(monster,camera.position.clone().addScaledVector(view,3.2)).normalize()}
 if(monster.behavior==='audit-search'){const audit=(time+monster.seed)%5;if(audit<1.25){monster.speedScale=.35;return side.multiplyScalar(monster.turnSign)}if(audit<3.6){monster.speedScale=distance>5?1.12:.72;return direct}monster.speedScale=.62;return direct.multiplyScalar(.25).addScaledVector(side,-monster.turnSign).normalize()}
 return direct
}
function finishAdminMonsterRush(monster,hitWall=false){
 journalDiscover(monster.type,3);monster.mesh.removeFromParent();adminMonsters=adminMonsters.filter(entry=>entry!==monster);if(monster.type==='bash'){document.body.classList.remove('bash-warning','bash-rush');document.querySelector('#prompt').textContent=hitWall?'BASH CRASHED INTO A WALL · THE LANE IS CLEAR':'BASH PASSED · THE CORRIDOR IS CLEAR'}else if(monster.natural&&monster.type==='purge')document.querySelector('#prompt').textContent='THE PURGE PASSED · THE ROOM IS QUIET AGAIN';else if(monster.natural&&monster.type==='cable-mass')document.querySelector('#prompt').textContent='CABLE MASS PASSED · THE CORRIDOR IS CLEAR';if(!monster.hit||adminInvincible)monster.onComplete?.()
}
function activeHotelEncounter(){if(noise||hotelNoiseArc||floorOne?.huntTimer>0||floorOne?.phase===2)return'THE NOISE';if(pursuer)return'THE PURSUER';if(molly)return'MOLLY';if(collector)return'THE COLLECTOR';if(clockmaker)return'THE CLOCKMAKER';if(drowned)return'THE DROWNED GUEST';if(eviction)return'THE PURGE';if(ransack.phase!=='waiting')return'RANSACK';if(floorOne?.phase===10||document.body.classList.contains('boss-encounter'))return'THE CHEF';const floorTwoOwner={6:'THE MASKED GUESTS',7:'THE WATCHER',10:'THE GARDENER',11:'THE WINDOW CREATURE',12:'THE FALSE GUEST'}[floorTwo?.phase];if(floorTwoOwner)return floorTwoOwner;if(inLobby||hotelSideScene.includes('boss')||hotelSideScene==='room60'||hotelSideScene==='floor-two-19')return'A PROTECTED ENCOUNTER';return''}
function transientEncounterAvailable(){return!activeHotelEncounter()&&!adminMonsters.length&&!hotelRoomPassage&&!dlg?.open&&!document.body.classList.contains('admin-open')}
function finishTransientMonster(monster){journalDiscover(monster.type,3);monster.mesh?.removeFromParent();adminMonsters=adminMonsters.filter(entry=>entry!==monster);document.body.classList.remove('bash-warning','bash-rush');if(monster.natural)document.querySelector('#prompt').textContent=`${monster.name.toUpperCase()} VANISHED · THE MOMENT HAS PASSED`;if(!monster.hit||adminInvincible)monster.onComplete?.()}
function spawnAdminMonster(kind='bash',options={}){
 if(!roomGroup)return;const conflict=activeHotelEncounter()||(adminMonsters.length?adminMonsters[0].name.toUpperCase():'');if(conflict&&!options.force){document.querySelector('#prompt').textContent=`${conflict} OWNS THIS AREA · NO OTHER MONSTER CAN ENTER`;return null}const config=ADMIN_MONSTER_CATALOG[kind]||ADMIN_MONSTER_CATALOG.root,mesh=makeAdminMonsterModel(kind),forward=new THREE.Vector3();camera.getWorldDirection(forward);forward.y=0;if(forward.lengthSq()<.01)forward.set(0,0,-1);forward.normalize();const monster={type:kind,name:config.name,behavior:config.behavior,mesh,phase:config.rush?'warning':'active',timer:config.warning||.9,direction:new THREE.Vector3(),speed:config.speed||2.7,speedScale:1,safePosition:camera.position.clone(),travel:0,hit:false,natural:!!options.natural,lifetime:options.natural?(config.rush?12:8+Math.random()*5):Infinity,onComplete:options.onComplete||null,hover:config.hover||0,phaseWalls:!!config.phaseWalls,radius:config.radius||.62,height:config.height||3.35,stepHeight:config.stepHeight||.65,groundY:playerFeetY,turnSign:Math.random()>.5?1:-1,seed:Math.random()*12,specialTimer:1.8,lastPlayerPosition:camera.position.clone(),lastHeardPosition:camera.position.clone(),soundMemory:0};const spawn=findAdminMonsterSpawn(monster,forward,config.distance||9);if(!spawn){document.querySelector('#prompt').textContent=`NO SAFE FLOOR SPACE TO SPAWN ${config.name.toUpperCase()}`;if(options.natural)options.onComplete?.();return null}monster.groundY=spawn.ground;mesh.position.set(spawn.position.x,spawn.ground+monster.hover,spawn.position.z);monster.direction.set(camera.position.x-mesh.position.x,0,camera.position.z-mesh.position.z).normalize();mesh.lookAt(camera.position.x,mesh.position.y,camera.position.z);roomGroup.add(mesh);adminMonsters.push(monster);journalDiscover(kind,1);
 monster.anchorPosition=mesh.position.clone();monster.patrolAngle=monster.seed;
 const behaviorCopy=ADMIN_MONSTER_BEHAVIOR_COPY[monster.behavior]||'hunts with an unknown pattern';if(kind==='bash'){document.body.classList.add('bash-warning');document.querySelector('#prompt').textContent='BASH LOCKED ONE LANE · MOVE SIDEWAYS'}else document.querySelector('#prompt').textContent=`${monster.name.toUpperCase()} · ${behaviorCopy.toUpperCase()}`;return monster
}
function randomRoomMonsterPlan(roomKey,{chance=.22,allowed=['bash','purge','cable-mass','empty-porter','black-bellhop','reflection','night-auditor']}={}){
 let hash=2166136261;const seed=`${HOTEL_VISIT_SEED}|${roomKey}`;for(let index=0;index<seed.length;index++){hash^=seed.charCodeAt(index);hash=Math.imul(hash,16777619)}hash>>>=0;if(hash%10000>=Math.floor(chance*10000)||!allowed.length)return null;return{kind:allowed[Math.floor(hash/10000)%allowed.length],delay:1400+Math.floor(hash/100000)%1200}
}
function scheduleRandomRoomMonster(roomKey,run,saveRun,options={}){
 if(!run||randomRoomMonsterHandle||!transientEncounterAvailable())return;run.randomMonsterRooms??=[];run.randomMonsterCooldown??=0;if(run.randomMonsterRooms.includes(roomKey))return;if(run.randomMonsterCooldown>0){run.randomMonsterCooldown--;saveRun();return}const plan=randomRoomMonsterPlan(roomKey,options);if(!plan)return;const expectedScene=hotelSideScene,expectedGroup=roomGroup,cooldownRooms=options.cooldownRooms??2;let attempts=0;
 document.body.dataset.randomMonsterPending=roomKey;document.querySelector('#prompt').textContent='THE LIGHTS FLICKER · SOMETHING IS ENTERING THIS ROOM';
 const trySpawn=()=>{randomRoomMonsterHandle=null;if(hotelSideScene!==expectedScene||roomGroup!==expectedGroup||!expectedGroup?.parent){delete document.body.dataset.randomMonsterPending;return}if(!transientEncounterAvailable()){if(attempts++<8)randomRoomMonsterHandle=setTimeout(trySpawn,650);else delete document.body.dataset.randomMonsterPending;return}const monster=spawnAdminMonster(plan.kind,{natural:true});if(!monster){if(attempts++<4)randomRoomMonsterHandle=setTimeout(trySpawn,500);else delete document.body.dataset.randomMonsterPending;return}delete document.body.dataset.randomMonsterPending;run.randomMonsterRooms.push(roomKey);run.randomMonsterCooldown=cooldownRooms;saveRun();document.querySelector('#prompt').dataset.randomMonster=plan.kind};
 randomRoomMonsterHandle=setTimeout(trySpawn,plan.delay)
}
function updateAdminMonsters(dt,time){
 if(journalPaused)return;
 adminHitCooldown=Math.max(0,adminHitCooldown-dt);for(const monster of [...adminMonsters]){
  if(!monster.mesh.parent){if(monster.type==='bash')document.body.classList.remove('bash-warning','bash-rush');adminMonsters=adminMonsters.filter(entry=>entry!==monster);continue}
  monster.mesh.visible=true;
  if(monster.natural&&monster.phase==='active'){monster.lifetime-=dt;if(monster.lifetime<=0){finishTransientMonster(monster);continue}}
  if(monster.phase==='warning'){monster.timer-=dt;monster.mesh.visible=true;monster.mesh.rotation.z=Math.sin(time*18)*.04;if(monster.timer<=0){monster.phase='rush';journalDiscover(monster.type,2);monster.mesh.rotation.z=0;if(monster.type==='bash'){document.body.classList.remove('bash-warning');document.body.classList.add('bash-rush');document.querySelector('#prompt').textContent='BASH · GET OUT OF THE LANE'}}continue}
  if(monster.phase==='rush'){let rushDirection=monster.direction;if(monster.behavior==='cable-charge'){const side=new THREE.Vector3(-monster.direction.z,0,monster.direction.x);rushDirection=monster.direction.clone().addScaledVector(side,Math.sin(time*8+monster.seed)*.42).normalize()}const moved=moveAdminMonster(monster,rushDirection,monster.speed*dt);if(!moved&&!monster.phaseWalls){finishAdminMonsterRush(monster,true);continue}monster.travel+=monster.speed*dt;monster.mesh.rotation.z=Math.sin(time*25)*.08;if(monster.behavior==='purge-sweep')monster.mesh.rotation.y+=dt*5;const flatDistance=Math.hypot(monster.mesh.position.x-camera.position.x,monster.mesh.position.z-camera.position.z),sameFloor=Math.abs(monster.groundY-playerFeetY)<1.5,coverBlocks=!monster.phaseWalls&&adminMonsterSegmentBlocked(monster,monster.mesh.position,new THREE.Vector3(camera.position.x,playerFeetY,camera.position.z));if(!hotelHideState&&flatDistance<1.45&&sameFloor&&!monster.hit&&!coverBlocks)adminMonsterHit(monster);if(monster.travel>25)finishAdminMonsterRush(monster);continue}
  const toPlayer=new THREE.Vector3(camera.position.x-monster.mesh.position.x,0,camera.position.z-monster.mesh.position.z),distance=toPlayer.length(),intent=adminMonsterIntent(monster,toPlayer,distance,dt,time);if(distance>.05&&monster.speedScale>0)moveAdminMonster(monster,intent,monster.speed*monster.speedScale*dt);monster.mesh.lookAt(camera.position.x,monster.mesh.position.y,camera.position.z);monster.mesh.rotation.z=Math.sin(time*7+monster.seed)*.025;const sameFloor=Math.abs(monster.groundY-playerFeetY)<1.5,coverBlocks=!monster.phaseWalls&&adminMonsterSegmentBlocked(monster,monster.mesh.position,new THREE.Vector3(camera.position.x,playerFeetY,camera.position.z));if(!hotelHideState&&distance<1.35&&sameFloor&&!monster.hit&&!coverBlocks)adminMonsterHit(monster)
 }
}
function grantAdminItem(id){
 if(!inventoryCatalog[id])return;const permanent=new Set(['vitamins','medkit','bandage','energy-drink','glowstick','wind-up-decoy','flashlight-battery','lockpick','matches','gold']);
 if(id==='vitamins')usableInventory.vitamins+=5;else if(id==='medkit')usableInventory.medkits+=5;else if(id==='bandage')usableInventory.bandages+=5;else if(id==='energy-drink')usableInventory.energyDrinks+=5;else if(id==='glowstick')usableInventory.glowsticks+=5;else if(id==='wind-up-decoy')usableInventory.decoys+=5;else if(id==='flashlight-battery')usableInventory.batteries+=5;else if(id==='lockpick')usableInventory.lockpicks+=5;else if(id==='matches')usableInventory.matchesBought+=10;else if(id==='gold')usableInventory.adminGold=(usableInventory.adminGold||0)+20;else if(id==='door-handle'){handlePieces=new Set([0,1,2]);localStorage.setItem('cabin-handle-pieces',JSON.stringify([...handlePieces]))}else if(id==='baseball-bat'){batOwned=true;localStorage.setItem('cabin-baseball-bat','true')}else if(['compass','ash-key','batteries','lantern'].includes(id)){cabinSecrets.add(id);localStorage.setItem('cabin-secret-chain',JSON.stringify([...cabinSecrets]))}else if(['sheet','spoon','rope','cutters','baton','hall-key','code','baton-code'].includes(id)){jailbreakItems.add(id);saveJailbreak()}else if(id==='room-assignment'){hotelArrivalItems.add('first-digit');saveHotelArrival()}else if(id==='room304-key'){hotelArrivalItems.add('room304-key');saveHotelArrival()}else if(['flashlight','brochure'].includes(id)){hotelArrivalItems.add(id);saveHotelArrival()}else if(id==='elevator-key'){floorFive??=newFloorFiveRun();floorFive.items.add(id);saveFloorFive()}else if(['sheet-music','grounding-wire','cleaning-rag'].includes(id)){floorTwo??=newFloorTwoRun();if(id==='sheet-music')floorTwo.sheetFound=true;if(id==='grounding-wire')floorTwo.wires=4;if(id==='cleaning-rag')floorTwo.rag=true;saveFloorTwo()}else{hotelRunItems.add(id);saveHotelRun()}
 if(!permanent.has(id))adminGrantedItems.add(id);localStorage.setItem('escape-admin-items',JSON.stringify([...adminGrantedItems]));saveUsableInventory();updateInventory();pickupTone();document.querySelector('#prompt').textContent=`ADMIN GAVE ${inventoryCatalog[id].label.toUpperCase()}`
}

const ADMIN_COMPLETION_FLAGS=Object.freeze([
 "room13-key","purge-survived","floor-five-arrival","floor-one-checkout","floor-two-room140",
 "doors-style-run-escaped","escaped","collector-escaped","clockmaker-out-of-time",
 "drowned-guest-left-below","subfloor-one-infinite-cinema","lobby-bell","lobby-elevator",
 "lobby-guestbook","lobby-storage","door",...Array.from({length:6},(_,index)=>`pursuer-chase-${index+1}`),
 ...Array.from({length:5},(_,index)=>`reality-solved-${index}`)
]);
const ADMIN_RESOURCE_ITEMS=new Set(["vitamins","medkit","bandage","energy-drink","glowstick","wind-up-decoy","flashlight-battery","lockpick","matches","gold"]);
function adminRestockEverything(announce=true){
 usableInventory.vitamins=Math.max(99,usableInventory.vitamins||0);
 usableInventory.medkits=Math.max(99,usableInventory.medkits||0);
 usableInventory.bandages=Math.max(99,usableInventory.bandages||0);
 usableInventory.energyDrinks=Math.max(99,usableInventory.energyDrinks||0);
 usableInventory.glowsticks=Math.max(99,usableInventory.glowsticks||0);
 usableInventory.decoys=Math.max(99,usableInventory.decoys||0);
 usableInventory.batteries=Math.max(99,usableInventory.batteries||0);
 usableInventory.lockpicks=Math.max(99,usableInventory.lockpicks||0);
 usableInventory.matchesBought=Math.max((usableInventory.matchesUsed||0)+99,usableInventory.matchesBought||0);
 usableInventory.adminGold=Math.max(999,usableInventory.adminGold||0);
 usableInventory.flashlightCharge=100;
 usableInventory.flashlightOn=true;
 saveUsableInventory();
 setStability(100);
 if(announce){pickupTone();document.querySelector("#prompt").textContent="ADMIN RESOURCES MAXED · FLASHLIGHT FULL · COMPOSURE RESTORED"}
 return true
}
function adminGiveEveryItem(announce=true){
 const catalogIds=Object.keys(inventoryCatalog);
 adminGrantedItems=new Set([...adminGrantedItems,...catalogIds.filter(id=>!ADMIN_RESOURCE_ITEMS.has(id))]);
 handlePieces=new Set([0,1,2]);
 batOwned=true;
 cabinSecrets=new Set([...cabinSecrets,...requiredCabinSecrets]);
 jailbreakItems=new Set([...jailbreakItems,"sheet","spoon","rope","cutters","baton","hall-key","code","baton-code","vent-unlocked","vent-maze","guard-knocked","dug-hole","key-room-open","cameras-off","steam-released","truck-started"]);
 hotelArrivalItems=new Set([...hotelArrivalItems,"first-digit","room304-key","room304-key-used","flashlight","brochure","matches","matches-5","arrival-gold","gold-tokens-3"]);
 for(const id of catalogIds)if(!ADMIN_RESOURCE_ITEMS.has(id))hotelRunItems.add(id);
 if(floorFive)floorFive.items.add("elevator-key");
 if(floorTwo){floorTwo.sheetFound=true;floorTwo.wires=Math.max(4,floorTwo.wires||0);floorTwo.rag=true}
 if(molly){molly.hammerTaken=true;molly.cameraTaken=true;molly.droneTaken=true;saveMolly()}
 localStorage.setItem("escape-admin-items",JSON.stringify([...adminGrantedItems]));
 localStorage.setItem("cabin-handle-pieces",JSON.stringify([...handlePieces]));
 localStorage.setItem("cabin-baseball-bat","true");
 localStorage.setItem("cabin-secret-chain",JSON.stringify([...cabinSecrets]));
 saveJailbreak();saveHotelArrival();saveHotelRun();saveFloorFive();saveFloorTwo();
 adminRestockEverything(false);updateInventory();
 if(announce){pickupTone();document.querySelector("#prompt").textContent=`ADMIN GRANTED EVERY ITEM · ${catalogIds.length} CATALOG ENTRIES AVAILABLE`}
 return catalogIds.length
}
function adminUnlockEverything(){
 adminGiveEveryItem(false);
 saved.fill(true);
 bonusSolved=new Set([...bonusSolved,...requiredBonusPuzzles]);
 cabinSecrets=new Set([...cabinSecrets,...requiredCabinSecrets]);
 jailbreakStage=Math.max(jailbreakStage,8);
 hotelStage=Math.max(hotelStage,3);
 hotelProgress=new Set([...hotelProgress,...ADMIN_COMPLETION_FLAGS]);
 pursuerCompletedScenes=new Set([1,2,3,4,5,6]);
 journalDiscoveries={...journalDiscoveries,...Object.fromEntries(SURVIVOR_JOURNAL_ENTRIES.map(entry=>[entry.id,3]))};
 journalCurios=new Set([...journalCurios,...Object.keys(inventoryCatalog).filter(id=>id.startsWith("curio-"))]);
 journalPlaces=new Set([...journalPlaces,...HOTEL_PLACE_DISCOVERIES.map(entry=>entry.id)]);
 lobbyBadgeNotified=new Set(lobbyBadgeDefinitions().map(badge=>badge.id));
 localStorage.setItem("cabin-3d-progress",JSON.stringify(saved));
 localStorage.setItem("cabin-bonus-puzzles",JSON.stringify([...bonusSolved]));
 localStorage.setItem("cabin-secret-chain",JSON.stringify([...cabinSecrets]));
 localStorage.setItem("jailbreak-stage",String(jailbreakStage));
 localStorage.setItem("infinite-hotel-stage",String(hotelStage));
 localStorage.setItem("infinite-hotel-progress",JSON.stringify([...hotelProgress]));
 localStorage.setItem("infinite-hotel-pursuer-scenes-v2",JSON.stringify([...pursuerCompletedScenes]));
 localStorage.setItem("hotel-molly-complete","true");
 localStorage.setItem(LOBBY_BADGE_NOTICE_KEY,JSON.stringify([...lobbyBadgeNotified]));
 sessionStorage.setItem("infinite-hotel-purge-complete-v1","true");
 saveJournalDiscoveries();saveJournalCurios();saveJournalPlaces();
 adminRestockEverything(false);
 if(inLobby){refreshLobbyProgressionDoors();updateLobbyPreview()}else updateHud();
 if(journalPaused)renderSurvivorJournal();
 updateInventory();pickupTone();
 document.querySelector("#prompt").textContent="ADMIN MASTER OVERRIDE · ALL STORIES, LOBBY DOORS, BADGES, JOURNALS, ITEMS, AND RESOURCES UNLOCKED";
 return{stories:saved.filter(Boolean).length,journals:Object.keys(journalDiscoveries).length,badges:lobbyBadgeDefinitions().filter(badge=>badge.earned).length,items:adminGrantedItems.size}
}
function setAdminHotelContext(){hideStorySelection();inLobby=false;inJailbreak=false;activeStory='hotel';room=8;clearAdminMonsters()}
function adminTeleport(destination){
 closeAdminPanel(false);clearAdminMonsters();if(!destination.startsWith('collector-'))collector=null;if(!destination.startsWith('clock-'))clockmaker=null;if(!destination.startsWith('drowned-'))drowned=null;if(!destination.startsWith('pursuer-'))pursuer=null;if(destination!=='molly-electrical')molly=null;if(destination==='story-lobby')return buildStoryLobby();if(destination==='cabin-main'||destination==='cabin-workshop'){hideStorySelection();room=destination==='cabin-main'?0:5;return buildRoom(room)}if(destination==='jailbreak-cell'){hideStorySelection();return buildJailbreak(0)}setAdminHotelContext();
 if(destination==='badge-sunroom')return buildBadgeSunroom();if(destination.startsWith('cinema-')){const index=THREE.MathUtils.clamp(Number(destination.slice(7))-1,0,INFINITE_CINEMA_FILMS.length-1);infiniteCinema=newInfiniteCinemaState();infiniteCinema.room=index;infiniteCinema.heldFilm=INFINITE_CINEMA_FILMS[index].id;saveInfiniteCinema();return buildInfiniteCinemaRoom()}
 if(destination==='hotel-courtyard')return buildHotelArrivalCourtyard();if(destination==='hotel-lobby')return buildHotelArrivalLobby();if(destination==='hotel-room304')return buildHotelArrivalSuite();
 if(destination.startsWith('floor5-')){floorFive=newFloorFiveRun();if(destination==='floor5-entry')return startFloorFiveSequence();if(destination==='floor5-library'){floorFive.phase='library';return buildFloorFiveLibrary()}floorFive.phase='boss';floorFive.items.add('elevator-key');return buildFloorFiveBoss()}
 if(destination==='room51'||destination==='room60')return buildHotelNoiseArcRoom(Number(destination.slice(4)));
 if(destination.startsWith('collector-')){floorOne=null;floorTwo=null;collector=newCollectorRun();if(destination==='collector-medallion'){collector.phase=3;collector.slots=['key']}else if(destination==='collector-watch'){collector.phase=4;collector.slots=['key','medallion'];collector.caseOpen=true}else if(destination==='collector-room'){collector.phase=6;collector.slots=['key','medallion','watch'];collector.watchTaken=true}else if(destination==='collector-release'){collector.phase=7;collector.slots=['key','medallion','watch'];collector.watchTaken=true;collector.released=true}else if(destination==='collector-escape'){collector.phase=8;collector.slots=['key','medallion','watch'];collector.watchTaken=true;collector.released=true}saveCollector();return startCollector(false)}
 if(destination.startsWith('clock-')){floorOne=null;floorTwo=null;collector=null;clockmaker=newClockmakerRun();clockmaker.phase=destination==='clock-face'?2:destination==='clock-four'?3:destination==='clock-broken'?4:destination==='clock-climb'?5:destination==='clock-master'?6:destination==='clock-escape'?7:1;if(clockmaker.phase>=2)clockmaker.lowerLocks=[0,1,2];if(clockmaker.phase>=3)clockmaker.upperLocks=[0,1];if(clockmaker.phase>=4)clockmaker.clocks=clockmaker.clocks.map(()=>({hour:12,minute:0,locked:true}));if(clockmaker.phase>=6)clockmaker.brakes=[0,1,2];if(clockmaker.phase>=7)clockmaker.masterLocks=[0,1,2,3];saveClockmaker();return startClockmaker(false)}
 if(destination.startsWith('drowned-')){floorOne=null;floorTwo=null;collector=null;clockmaker=null;drowned=newDrownedRun();drowned.phase=destination==='drowned-furniture'?2:destination==='drowned-maintenance'?3:destination==='drowned-basin'?4:destination==='drowned-chase'?5:destination==='drowned-bulkhead'?6:1;drowned.pumps=Array.from({length:Math.min(4,Math.max(0,drowned.phase-1))},(_,index)=>index);if(drowned.phase>=3){drowned.channels=[1,2,0];drowned.channelSolved=true}if(drowned.phase>=5)drowned.sluices=[0,1];saveDrowned();return startDrowned(false)}
 if(destination.startsWith('pursuer-')){const slug=destination.slice(8),sceneIndex=Object.values(PURSUER_SCENES).findIndex(scene=>scene.slug===slug)+1||1;return startPursuerEncounter(sceneIndex,'admin',true)}
 if(destination==='molly-electrical')return startMolly(true,'admin');
 if(destination.startsWith('floor2-')||destination==='room140'){floorOne=null;floorTwo=newFloorTwoRun();floorTwo.phase=destination==='floor2-scale'?2:destination==='floor2-piano'?4:destination==='floor2-outside'?6:destination==='floor2-watcher'?7:destination==='floor2-fireescape'?9:destination==='floor2-garden'?10:destination==='floor2-window'?11:destination==='floor2-guests'?12:destination==='floor2-fuse'?13:destination==='floor2-rooftops'?14:destination==='floor2-spotlights'?15:destination==='floor2-gauntlet'?16:destination==='floor2-crane'?17:destination==='room140'?19:1;const routeKind=entry=>typeof entry==='string'?entry:entry?.kind;if(destination==='floor2-fireescape')floorTwo.index=Math.max(0,floorTwo.routes.watcherExterior.findIndex(entry=>routeKind(entry)==='fire-escape'));if(destination==='floor2-rooftops')floorTwo.index=Math.max(0,floorTwo.routes.fuseExterior.findIndex(entry=>routeKind(entry)==='vent-roof'));if(destination==='floor2-gauntlet')floorTwo.index=Math.max(0,floorTwo.routes.finalExterior.findIndex(entry=>routeKind(entry)!=='balcony'));if(floorTwo.phase>=7)floorTwo.storm=true;saveFloorTwo();return buildFloorTwoPhase()}
 floorOne=newFloorOneRun();floorOne.phase=destination==='floor1-sound'?2:destination==='floor1-ballroom'?8:destination.startsWith('floor1-chef')?10:1;floorOne.index=0;if(destination.startsWith('floor1-chef')){floorOne.chefTriggered=true;floorOne.chefStage=destination==='floor1-chef-elevator'?'defeated':'combat';floorOne.chefHealth=destination==='floor1-chef-freezer'?66:destination==='floor1-chef-final'?32:destination==='floor1-chef-elevator'?0:100;floorOne.chefCombatPhase=destination==='floor1-chef-freezer'?2:destination==='floor1-chef-final'?3:1;floorOne.chefExitUnlocked=destination==='floor1-chef-elevator';floorOne.chefAction='idle';floorOne.chefAttackCooldown=1.25;floorOne.gasValves=destination==='floor1-chef'?[]:destination==='floor1-chef-freezer'?[0]:destination==='floor1-chef-final'?[0,1]:[0,1,2]}saveFloorOne();buildFloorOnePhase();armGameplayControls()
}
const ADMIN_DESTINATION_LABELS={'floor5-entry':'Floor 5 · Room 501','floor5-library':'Floor 5 · Room 525 Library','floor5-boss':'Floor 5 · Room 550 Elevator Boss','floor1-entry':'Floor 1 · Room 1','floor1-sound':'Floor 1 · Room 10 Sound Sector','floor1-ballroom':'Floor 1 · Room 40 Ballroom','floor1-chef':'Chef Arena · Phase One','floor1-chef-freezer':'Chef Arena · Phase Two','floor1-chef-final':'Chef Arena · Phase Three','floor1-chef-elevator':'Chef Arena · Defeated / Elevator','floor2-outside':'Floor 2 · Room 115 Ballroom','floor2-watcher':'Floor 2 · Room 116 Watcher','floor2-fireescape':'Floor 2 · Rooms 117–118 Fire Escapes','floor2-garden':'Floor 2 · Room 119 Garden Maze','floor2-window':'Floor 2 · Room 120 Window Creature','floor2-guests':'Floor 2 · Room 121 False Guests','floor2-fuse':'Floor 2 · Room 122 Fuse Box','floor2-rooftops':'Floor 2 · Rooms 123–129 Rooftops','floor2-spotlights':'Floor 2 · Room 130 Spotlights','floor2-gauntlet':'Floor 2 · Rooms 131–139 Exterior','floor2-crane':'Floor 2 · Room 140 Crane','room140':'Floor 2 · Room 150 Safe Vault','molly-electrical':'Molly · Electrical Section'};
const ADMIN_LOCATION_CATEGORIES=[['hotel','HOTEL & LOBBY'],['floor5','FLOOR 5'],['floor1','FLOOR 1'],['floor2','FLOOR 2'],['boss','BOSS ENCOUNTERS'],['pursuer','PURSUER CHASES'],['subfloor','SUB-FLOORS'],['cabin','CABIN'],['jailbreak','JAILBREAK']];
const ADMIN_BOSS_MONSTERS=new Set(['chef','collector','clockmaker','drowned-guest','pursuer','molly','luggage-warden','empty-porter','black-bellhop','reflection','hotel-manager','night-auditor']);
const ADMIN_FLOOR_TWO_MONSTERS=new Set(['ballroom-guest','watcher','gardener','window-creature','false-guest']);
const ADMIN_CABIN_MONSTERS=new Set(['spider','root']);
let adminDestinationOptions=[];
function adminDestinationCategory(id){if(id.startsWith('cabin-'))return'cabin';if(id.startsWith('jailbreak-'))return'jailbreak';if(id==='badge-sunroom'||id.startsWith('cinema-'))return'subfloor';if(id.startsWith('pursuer-'))return'pursuer';if(id.startsWith('collector-')||id.startsWith('clock-')||id.startsWith('drowned-')||id.startsWith('floor1-chef')||id==='floor5-boss'||id==='molly-electrical')return'boss';if(id.startsWith('floor5-'))return'floor5';if(id.startsWith('floor1-'))return'floor1';if(id.startsWith('floor2-')||id==='room140')return'floor2';return'hotel'}
function adminEncounterCategory(id){if(ADMIN_BOSS_MONSTERS.has(id))return'boss';if(ADMIN_FLOOR_TWO_MONSTERS.has(id))return'floor2';if(ADMIN_CABIN_MONSTERS.has(id))return'cabin';return'monster'}
function refreshAdminTeleportLabels(){const select=document.querySelector('#admin-teleport');for(const option of select?.options||[])if(ADMIN_DESTINATION_LABELS[option.value])option.textContent=ADMIN_DESTINATION_LABELS[option.value]}
function refreshAdminMonsterLabels(){const select=document.querySelector('#admin-monster');for(const option of select?.options||[]){const config=ADMIN_MONSTER_CATALOG[option.value],copy=config&&ADMIN_MONSTER_BEHAVIOR_COPY[config.behavior];if(!copy)continue;option.dataset.pattern=copy;option.title=copy}}
function updateAdminLocationDetail(){const select=document.querySelector('#admin-teleport'),detail=document.querySelector('#admin-location-detail'),option=select?.selectedOptions?.[0];if(!detail||!option)return;const category=ADMIN_LOCATION_CATEGORIES.find(([id])=>id===adminDestinationCategory(option.value))?.[1]||'LOCATION';detail.textContent=`${category} · ${option.textContent.toUpperCase()}`}
function updateAdminMonsterDetail(){const select=document.querySelector('#admin-monster'),detail=document.querySelector('#admin-monster-detail'),id=select?.value,config=ADMIN_MONSTER_CATALOG[id];if(!detail||!config)return;const category=adminEncounterCategory(id)==='boss'?'BOSS':adminEncounterCategory(id)==='floor2'?'FLOOR 2 MONSTER':adminEncounterCategory(id)==='cabin'?'CABIN MONSTER':'RANDOM MONSTER',behavior=ADMIN_MONSTER_BEHAVIOR_COPY[config.behavior]||config.behavior;detail.textContent=`${category} · ${config.name.toUpperCase()} · ${behavior.toUpperCase()} · ${config.phaseWalls?'PHASES THROUGH WALLS':'SOLID WALLS'}`}
function adminSetStatus(message,state='success'){const status=document.querySelector('#admin-status');if(status){status.textContent=message;status.dataset.state=state}return message}
function runAdminCommand(label,action){try{const result=action();adminSetStatus(`${label} · COMPLETE`);return result}catch(error){console.error(`Admin command failed: ${label}`,error);adminSetStatus(`${label} · ${String(error?.message||error).toUpperCase()}`,'error');document.querySelector('#prompt').textContent=`ADMIN ERROR · ${label}`;return null}}
function openAdminPanel(){refreshAdminMonsterLabels();updateAdminLocationDetail();updateAdminMonsterDetail();const panel=document.querySelector('#admin-panel'),toggle=document.querySelector('#admin-toggle');panel.hidden=false;toggle.setAttribute('aria-expanded','true');document.body.classList.add('admin-open');controls.unlock()}
function closeAdminPanel(relock=true){const panel=document.querySelector('#admin-panel'),toggle=document.querySelector('#admin-toggle');panel.hidden=true;toggle.setAttribute('aria-expanded','false');document.body.classList.remove('admin-open');if(relock&&!dlg.open&&storySelect.hidden)controls.lock()}
function syncGraphicsControls(){
 const quality=document.querySelector('#graphics-quality'),resolution=document.querySelector('#graphics-resolution'),resolutionValue=document.querySelector('#graphics-resolution-value'),effects=document.querySelector('#graphics-effects'),motion=document.querySelector('#reduced-motion'),flashing=document.querySelector('#reduced-flashing'),buffer=document.querySelector('#graphics-buffer');if(!quality)return;const snapshot=graphicsSnapshot();quality.value=snapshot.quality;resolution.value=String(Math.round(snapshot.resolutionScale*100));resolutionValue.value=`${Math.round(snapshot.resolutionScale*100)}%`;effects.checked=snapshot.optionalEffects;effects.disabled=!GRAPHICS_PRESETS[snapshot.quality].optionalEffects;motion.checked=snapshot.reducedMotion;flashing.checked=snapshot.reducedFlashing;buffer.textContent=`DRAWING BUFFER · ${snapshot.drawingBuffer[0]} × ${snapshot.drawingBuffer[1]} · DPR ${snapshot.pixelRatio.toFixed(2)}`
}
function setupGraphicsControls(){
 const quality=document.querySelector('#graphics-quality'),resolution=document.querySelector('#graphics-resolution'),effects=document.querySelector('#graphics-effects'),motion=document.querySelector('#reduced-motion'),flashing=document.querySelector('#reduced-flashing');if(!quality)return;quality.onchange=()=>{graphicsQuality=quality.value;graphicsRenderScale=GRAPHICS_PRESETS[graphicsQuality].resolutionScale;graphicsOptionalEffects=GRAPHICS_PRESETS[graphicsQuality].optionalEffects;applyGraphicsQuality(graphicsQuality)};resolution.oninput=()=>{graphicsRenderScale=Number(resolution.value)/100;applyGraphicsQuality(graphicsQuality)};effects.onchange=()=>{graphicsOptionalEffects=effects.checked;applyGraphicsQuality(graphicsQuality)};motion.onchange=()=>{graphicsReducedMotion=motion.checked;applyGraphicsQuality(graphicsQuality)};flashing.onchange=()=>{graphicsReducedFlashing=flashing.checked;applyGraphicsQuality(graphicsQuality)};syncGraphicsControls()
}
function populateAdminDestinationMenu(category='all'){
 const select=document.querySelector('#admin-teleport'),previous=select.value;select.replaceChildren();for(const [categoryId,categoryLabel] of ADMIN_LOCATION_CATEGORIES){if(category!=='all'&&category!==categoryId)continue;const matching=adminDestinationOptions.filter(option=>option.category===categoryId).sort((a,b)=>a.label.localeCompare(b.label,undefined,{numeric:true,sensitivity:'base'}));if(!matching.length)continue;const group=document.createElement('optgroup');group.label=categoryLabel;for(const entry of matching){const option=document.createElement('option');option.value=entry.id;option.textContent=entry.label;group.append(option)}select.append(group)}if([...select.options].some(option=>option.value===previous))select.value=previous;updateAdminLocationDetail()
}
function setupAdminDestinationMenus(){
 refreshAdminTeleportLabels();const select=document.querySelector('#admin-teleport'),category=document.querySelector('#admin-location-category');adminDestinationOptions=[...select.options].map(option=>({id:option.value,label:ADMIN_DESTINATION_LABELS[option.value]||option.textContent,category:adminDestinationCategory(option.value)}));category.replaceChildren();const all=document.createElement('option');all.value='all';all.textContent='All rooms and bosses';category.append(all);for(const [id,label] of ADMIN_LOCATION_CATEGORIES){const option=document.createElement('option');option.value=id;option.textContent=label;category.append(option)}category.onchange=()=>populateAdminDestinationMenu(category.value);select.onchange=updateAdminLocationDetail;populateAdminDestinationMenu()
}
const ADMIN_ENCOUNTER_CATEGORIES=[['boss','BOSSES'],['monster','RANDOM MONSTERS'],['floor2','FLOOR 2 MONSTERS'],['cabin','CABIN MONSTERS']];
function populateAdminEncounterMenu(category='all'){
 const select=document.querySelector('#admin-monster'),previous=select.value;select.replaceChildren();for(const [categoryId,categoryLabel] of ADMIN_ENCOUNTER_CATEGORIES){if(category!=='all'&&category!==categoryId)continue;const matching=Object.entries(ADMIN_MONSTER_CATALOG).filter(([id])=>adminEncounterCategory(id)===categoryId).sort(([,a],[,b])=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'}));if(!matching.length)continue;const group=document.createElement('optgroup');group.label=categoryLabel;for(const [id,config] of matching){const option=document.createElement('option');option.value=id;option.textContent=config.name;option.dataset.behavior=config.behavior;option.dataset.wallMode=config.phaseWalls?'phase':'solid';group.append(option)}select.append(group)}if([...select.options].some(option=>option.value===previous))select.value=previous;refreshAdminMonsterLabels();updateAdminMonsterDetail()
}
function setupAdminEncounterMenus(){
 const select=document.querySelector('#admin-monster'),category=document.querySelector('#admin-encounter-category');category.replaceChildren();const all=document.createElement('option');all.value='all';all.textContent='All monsters and bosses';category.append(all);for(const [id,label] of ADMIN_ENCOUNTER_CATEGORIES){const option=document.createElement('option');option.value=id;option.textContent=label;category.append(option)}category.onchange=()=>populateAdminEncounterMenu(category.value);select.onchange=updateAdminMonsterDetail;populateAdminEncounterMenu()
}
function sortedAdminCatalogEntries(){return Object.entries(inventoryCatalog).sort(([,a],[,b])=>{const rankA=INVENTORY_KIND_ORDER.indexOf(a.kind),rankB=INVENTORY_KIND_ORDER.indexOf(b.kind);return(rankA<0?INVENTORY_KIND_ORDER.length:rankA)-(rankB<0?INVENTORY_KIND_ORDER.length:rankB)||a.label.localeCompare(b.label,undefined,{numeric:true,sensitivity:'base'})})}
function populateAdminItemMenu(category='all'){
 const select=document.querySelector('#admin-item'),previous=select.value,groups=new Map();select.replaceChildren();for(const [id,item] of sortedAdminCatalogEntries()){if(category!=='all'&&item.kind!==category)continue;if(!groups.has(item.kind)){const group=document.createElement('optgroup');group.label=item.kind;groups.set(item.kind,group);select.append(group)}const option=document.createElement('option');option.value=id;option.textContent=item.label;groups.get(item.kind).append(option)}if([...select.options].some(option=>option.value===previous))select.value=previous
}
function setupAdminItemMenus(){
 const category=document.querySelector('#admin-item-category'),kinds=[...new Set(Object.values(inventoryCatalog).map(item=>item.kind))].sort((a,b)=>{const rankA=INVENTORY_KIND_ORDER.indexOf(a),rankB=INVENTORY_KIND_ORDER.indexOf(b);return(rankA<0?INVENTORY_KIND_ORDER.length:rankA)-(rankB<0?INVENTORY_KIND_ORDER.length:rankB)||a.localeCompare(b)});for(const kind of kinds){const option=document.createElement('option');option.value=kind;option.textContent=kind;category.append(option)}category.onchange=()=>populateAdminItemMenu(category.value);populateAdminItemMenu()
}
function setupAdminPanel(){
 const panel=document.querySelector('#admin-panel'),toggle=document.querySelector('#admin-toggle'),itemSelect=document.querySelector('#admin-item');setupAdminDestinationMenus();setupAdminEncounterMenus();setupAdminItemMenus();toggle.onclick=event=>{event.stopPropagation();panel.hidden?openAdminPanel():closeAdminPanel()};document.querySelector('#admin-close').onclick=()=>closeAdminPanel();
 document.querySelector('#admin-teleport-go').onclick=()=>runAdminCommand('TELEPORT',()=>adminTeleport(document.querySelector('#admin-teleport').value));
 document.querySelector('#admin-spawn').onclick=()=>{const id=document.querySelector('#admin-monster').value,result=runAdminCommand(`SPAWN ${ADMIN_MONSTER_CATALOG[id]?.name?.toUpperCase()||id.toUpperCase()}`,()=>{const spawned=spawnAdminMonster(id,{force:true});if(!spawned)throw new Error('NO SAFE FLOOR SPACE');return spawned});if(result)closeAdminPanel()};
 document.querySelector('#admin-clear-monsters').onclick=()=>runAdminCommand('CLEAR MONSTERS',()=>{clearAdminMonsters();document.querySelector('#prompt').textContent='ADMIN CLEARED ALL SPAWNED MONSTERS';return true});
 document.querySelector('#admin-give-item').onclick=()=>runAdminCommand(`GIVE ${inventoryCatalog[itemSelect.value]?.label?.toUpperCase()||'ITEM'}`,()=>grantAdminItem(itemSelect.value));
 document.querySelector('#admin-give-all').onclick=()=>runAdminCommand('GIVE EVERY ITEM',()=>adminGiveEveryItem());
 document.querySelector('#admin-restock').onclick=()=>runAdminCommand('MAX RESOURCES',()=>adminRestockEverything());
 document.querySelector('#admin-unlock-all').onclick=()=>runAdminCommand('UNLOCK EVERYTHING',()=>adminUnlockEverything());
 document.querySelector('#admin-invincible').onclick=event=>runAdminCommand('INFINITE HEALTH',()=>{adminInvincible=!adminInvincible;event.currentTarget.setAttribute('aria-pressed',String(adminInvincible));event.currentTarget.textContent=`INFINITE HEALTH · ${adminInvincible?'ON':'OFF'}`;if(adminInvincible)setStability(100);return adminInvincible});
 panel.addEventListener('click',event=>event.stopPropagation());document.addEventListener('keydown',event=>{if(event.code!=='F2'||event.repeat)return;event.preventDefault();panel.hidden?openAdminPanel():closeAdminPanel()});let lastMonsterTick=performance.now();setInterval(()=>{const now=performance.now(),dt=Math.min(.1,(now-lastMonsterTick)/1000);lastMonsterTick=now;updateAdminMonsters(dt,now*.001)},50);
 document.querySelector('#admin-ransack').onclick=()=>runAdminCommand('TRIGGER RANSACK',()=>{closeAdminPanel();finishRansackEvent(false);ransack.cooldown=0;startRansackEvent(true);return true});setupGraphicsControls();adminSetStatus('ADMIN READY','success')
}
