const MOLLY_COMPUTER_POSITIONS=[[-21,0,13],[-15,0,7],[-21,0,-4],[15,0,7],[21,0,-4],[16,0,-11]],MOLLY_PATROL_POINTS=[[-11,0,18],[-17,0,13],[-17,0,0],[-17,0,-11],[0,0,-13],[17,0,-11],[17,0,0],[17,0,13],[11,0,18],[0,0,13]],MOLLY_DOOR_COMPUTERS=[2,4,6];
const MOLLY_ROUTE_NODES=[[0,0,21.5],[-11,0,18],[-17,0,13],[-15,0,7],[-17,0,0],[-21,0,-4],[-17,0,-11],[-18,0,-15],[-18,0,-22],[0,0,-13],[0,0,-18],[0,0,-22],[17,0,-11],[16,0,-15],[18,0,-22],[17,0,0],[15,0,7],[17,0,13],[11,0,18],[0,0,13],[0,0,0],[-8,0,13],[8,0,13],[-8,0,0],[8,0,0],[-12,0,-13],[8,0,-13],[-21,0,13],[21,0,-4],[16,0,-11]],MOLLY_ROUTE_LINKS=[[1,18,19],[0,2,21],[1,3,27],[2,4,21],[3,5,6,23],[4],[4,7,25],[6,8,10],[7],[10,20,25,26],[7,9,11,13],[10],[13,15,26,29],[10,12,14],[13],[12,16,24,28],[15,17,22],[16,18,28],[0,17,22],[0,20,21,22],[9,19,23,24],[2,3,19,23],[16,17,18,19,24],[4,20,21,25],[15,20,22,26],[6,9,23],[9,12,24],[2],[15,17],[12]];
const MOLLY_CAMERA_FEEDS=[{label:'RECEPTION · CODE MACHINE',position:[0,5.4,28],look:[0,1.3,21]},{label:'WEST LOOP · COMPUTER 02',position:[-10,5.2,11],look:[-17,1.5,7]},{label:'CROSS PASSAGE · FAN JUNCTION',position:[0,5.1,5],look:[0,1.4,0]},{label:'EAST LOOP · COMPUTER 04',position:[10,5.2,11],look:[17,1.5,7]},{label:'LEVER APPROACH · COMPUTER 06',position:[10,5.3,-8],look:[17,1.4,-13]},{label:'FINAL SWITCH ROOM',position:[0,6.2,-27],look:[0,1.5,-21]}],MOLLY_DRONE_ROUTES=[{label:'WEST INSPECTION VENT',position:[-17,0,0]},{label:'COMPUTER 04 OVERLOOK',position:[17,0,7]},{label:'LEVER 03 WINDOW',position:[24,0,-17]},{label:'FINAL SWITCH ROOM',position:[0,0,-22]}];
function newMollyRun(origin='floor2'){return{origin,boundary:32,phase:'patrol',timer:0,selectionTimer:7,patrolIndex:0,targetComputer:0,display:'00',hacked:[],overridden:[],levers:[],codesRead:false,hammerTaken:false,droneTaken:false,brokenWindow:false,droneLatchOpen:false,droneRouteIndex:0,cameraFeedIndex:0,finalUnlocked:false,finalControlLost:false,grace:5,soundCooldown:0,intercomCooldown:0,stepTimer:.4,dying:false,flare:null,cameraView:null,lastSound:null,route:[],routeTarget:''}}
function loadMolly(origin='floor2'){try{const value=JSON.parse(sessionStorage.getItem('hotel-molly-run')||'null');return value?{...newMollyRun(value.origin||origin),...value,origin:value.origin||origin,hacked:value.hacked||[],overridden:value.overridden||[],levers:value.levers||[],flare:null,cameraView:null,dying:false}:newMollyRun(origin)}catch{return newMollyRun(origin)}}
function saveMolly(){if(!molly)return;const saved={...molly,flare:null,cameraView:null};sessionStorage.setItem('hotel-molly-run',JSON.stringify(saved))}
function mollyComputerCode(number){return{2:'2408',4:'0417',6:'6620'}[number]||String(7300+number*17)}
function mollyComputerLabel(number){return String(number).padStart(2,'0')}
function mollySetDisplay(value){if(!mollyEntity)return;const display=mollyComputerLabel(Number(value)||0),canvas=mollyEntity.userData.screenCanvas,context=canvas.getContext('2d');context.clearRect(0,0,canvas.width,canvas.height);const gradient=context.createLinearGradient(0,0,0,canvas.height);gradient.addColorStop(0,'#071215');gradient.addColorStop(1,'#010405');context.fillStyle=gradient;context.fillRect(0,0,canvas.width,canvas.height);context.strokeStyle='rgba(115,230,245,.18)';context.lineWidth=2;for(let y=8;y<canvas.height;y+=8){context.beginPath();context.moveTo(0,y);context.lineTo(canvas.width,y);context.stroke()}context.textAlign='center';context.textBaseline='middle';context.shadowColor='#6feaff';context.shadowBlur=10;context.fillStyle='#8edee6';context.font='700 15px monospace';context.fillText('NOW ROUTING',canvas.width/2,18);context.shadowBlur=18;context.fillStyle='#d8fdff';context.font='700 78px monospace';context.fillText(display,canvas.width/2,76);mollyEntity.userData.screenTexture.needsUpdate=true;molly.display=display}
function makeMollyModel(admin=false){
 const entity=new THREE.Group();entity.name='Molly · teller-inspired blind computer monster';const uniform=mat(0x111a20,.76),uniformEdge=mat(0x263640,.48),lining=mat(0x314955,.42),metal=mat(0x66767b,.22),rubber=mat(0x0a1012,.86),copper=mat(0xa45f32,.28,0x321409),skinMetal=mat(0x879195,.56);
 const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.43,1.28,8,14),uniform);torso.position.y=1.62;torso.scale.set(.84,1.06,.67);entity.add(torso);
 const waist=new THREE.Mesh(new THREE.CylinderGeometry(.39,.44,.24,10),metal);waist.position.y=.93;entity.add(waist);const skirt=new THREE.Mesh(new THREE.CylinderGeometry(.38,.69,.82,10,1,true),uniform);skirt.name='Molly tailored service skirt';skirt.position.y=.66;entity.add(skirt);const skirtLining=new THREE.Mesh(new THREE.CylinderGeometry(.36,.61,.7,10,1,true),lining);skirtLining.position.set(0,.65,-.025);skirtLining.scale.set(.98,.96,.94);entity.add(skirtLining);
 const jacketPanel=new THREE.Mesh(new THREE.BoxGeometry(.54,1.3,.14),uniformEdge);jacketPanel.position.set(0,1.66,.4);entity.add(jacketPanel);for(const side of [-1,1]){const lapel=new THREE.Mesh(new THREE.BoxGeometry(.2,.72,.08),lining);lapel.position.set(side*.16,2.02,.495);lapel.rotation.z=side*.22;entity.add(lapel)}for(const y of [1.28,1.63,1.98]){const button=new THREE.Mesh(new THREE.SphereGeometry(.045,8,6),metal);button.position.set(0,y,.51);entity.add(button)}
 const collar=new THREE.Mesh(new THREE.CylinderGeometry(.25,.31,.22,8),uniformEdge);collar.position.y=2.42;entity.add(collar);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.18,.22,.34,10),metal);neck.position.y=2.57;entity.add(neck);
 const head=new THREE.Group();head.name='Molly teller monitor head';head.position.set(0,3.08,0);entity.add(head);const rearShell=new THREE.Mesh(new THREE.BoxGeometry(1.36,.94,.62),rubber);rearShell.position.z=-.02;head.add(rearShell);const bezel=new THREE.Mesh(new THREE.BoxGeometry(1.26,.84,.13),metal);bezel.position.z=.31;head.add(bezel);for(const side of [-1,1]){const port=new THREE.Mesh(new THREE.CylinderGeometry(.12,.12,.12,10),metal);port.position.set(side*.72,.03,-.03);port.rotation.z=Math.PI/2;head.add(port)}for(const x of [-.56,.56])for(const y of [-.37,.37]){const bolt=new THREE.Mesh(new THREE.SphereGeometry(.035,7,5),metal);bolt.position.set(x,y,.39);head.add(bolt)}
 const screenCanvas=document.createElement('canvas');screenCanvas.width=256;screenCanvas.height=128;const screenTexture=new THREE.CanvasTexture(screenCanvas);screenTexture.colorSpace=THREE.SRGBColorSpace;const screenMaterial=new THREE.MeshBasicMaterial({map:screenTexture,toneMapped:false});const screen=new THREE.Mesh(new THREE.PlaneGeometry(1.06,.65),screenMaterial);screen.name='Molly screen face';screen.position.z=.382;head.add(screen);const glow=new THREE.PointLight(0x68dcea,admin?1.8:2.6,3.5,2);glow.position.set(0,0,.56);head.add(glow);
 const arms=[];for(const side of [-1,1]){const shoulder=new THREE.Group();shoulder.name=`Molly ${side>0?'hair-flip':'terminal'} shoulder`;shoulder.position.set(side*.64,2.3,0);entity.add(shoulder);const shoulderCap=new THREE.Mesh(new THREE.SphereGeometry(.17,9,7),uniformEdge);shoulderCap.scale.set(1,.72,.8);shoulder.add(shoulderCap);const upper=new THREE.Mesh(new THREE.CylinderGeometry(.085,.125,.96,8),uniform);upper.position.y=-.46;shoulder.add(upper);const elbow=new THREE.Group();elbow.name='Molly articulated elbow';elbow.position.y=-.92;shoulder.add(elbow);const joint=new THREE.Mesh(new THREE.SphereGeometry(.105,8,6),metal);elbow.add(joint);const forearm=new THREE.Mesh(new THREE.CylinderGeometry(.065,.1,.79,8),uniform);forearm.position.y=-.38;elbow.add(forearm);const cuff=new THREE.Mesh(new THREE.CylinderGeometry(.105,.09,.2,8),metal);cuff.position.y=-.77;elbow.add(cuff);const wrist=new THREE.Group();wrist.name='Molly articulated wrist';wrist.position.y=-.88;elbow.add(wrist);const hand=new THREE.Mesh(new THREE.CapsuleGeometry(.1,.2,5,8),skinMetal);hand.name=side>0?'Molly hair-flip hand':'Molly terminal hand';hand.position.y=-.12;wrist.add(hand);const fingers=[];for(let fingerIndex=0;fingerIndex<3;fingerIndex++){const finger=new THREE.Mesh(new THREE.CapsuleGeometry(.025,.16,3,6),skinMetal);finger.position.set((fingerIndex-1)*.06,-.27,.025);finger.rotation.z=(fingerIndex-1)*.08;wrist.add(finger);fingers.push(finger)}arms.push({shoulder,elbow,wrist,upper,forearm,hand,fingers,side})}
 const legs=[];for(const side of [-1,1]){const leg=new THREE.Group();leg.position.set(side*.22,.72,0);entity.add(leg);const trouser=new THREE.Mesh(new THREE.CylinderGeometry(.095,.14,1.25,8),uniform);trouser.position.y=-.48;leg.add(trouser);const shoe=new THREE.Mesh(new THREE.BoxGeometry(.3,.2,.55),rubber);shoe.position.set(0,-1.12,.14);leg.add(shoe);const heelWheel=new THREE.Mesh(new THREE.CylinderGeometry(.085,.085,.06,10),metal);heelWheel.name='Molly service-chair heel wheel';heelWheel.position.set(0,-1.2,-.13);heelWheel.rotation.z=Math.PI/2;leg.add(heelWheel);legs.push({leg,side})}
 const chassis=new THREE.Mesh(new THREE.TorusGeometry(.42,.035,6,16),metal);chassis.name='Molly office-chair chassis';chassis.position.y=.28;chassis.rotation.x=Math.PI/2;entity.add(chassis);for(const angle of [-.8,0,.8]){const spoke=new THREE.Mesh(new THREE.CylinderGeometry(.025,.035,.58,6),metal);spoke.position.set(Math.sin(angle)*.24,.28,Math.cos(angle)*.24);spoke.rotation.x=Math.PI/2;spoke.rotation.z=-angle;entity.add(spoke)}
 const wires=[];for(let index=0;index<18;index++){const side=index<9?-1:1,rank=index%9,root=new THREE.Group(),thick=index%4===0,wireMaterial=index%5===0?copper:mat(index%3?0x111719:0x243036,.72);root.position.set(side*(.2+rank*.055),3.36-(rank%3)*.05,-.2-(rank%2)*.08);entity.add(root);const length=thick?2.22:1.58+(rank%3)*.18,segments=thick?4:3;for(let segment=0;segment<segments;segment++){const pieceLength=length/segments,piece=new THREE.Mesh(new THREE.CylinderGeometry(thick?.047:.022,thick?.064:.032,pieceLength,6),wireMaterial);piece.position.set(side*(segment*.045),-(segment+.5)*pieceLength,.02*Math.sin(segment+index));piece.rotation.z=side*(.04+segment*.025);root.add(piece)}const connector=new THREE.Mesh(new THREE.CylinderGeometry(thick?.07:.045,thick?.07:.045,.13,7),index%5===0?copper:metal);connector.position.set(side*((segments-1)*.045),-length-.07,0);root.add(connector);wires.push({root,side,rank,weight:thick?1:.58,phase:index*.73,rest:side*(.05+rank*.012),restX:root.position.x,restY:root.position.y,restZ:root.position.z})}
 entity.userData={...entity.userData,screenCanvas,screenTexture,screen,head,arms,legs,wires,torso,skirt,flipStage:{name:'rest',reach:0,grip:0,flick:0,fan:0,settle:0},lastPosition:new THREE.Vector3(),velocity:new THREE.Vector3(),turnAmount:0};entity.traverse(child=>{if(child.isMesh){child.castShadow=true;child.receiveShadow=true}});if(!admin){mollyEntity=entity;mollySetDisplay(molly?.display||'00')}else{const fake={screenCanvas,screenTexture};const old=mollyEntity;mollyEntity=entity;const oldRun=molly;molly={display:'00'};mollySetDisplay('00');molly=oldRun;mollyEntity=old;entity.userData.adminMolly=fake}return entity
}
function playMollySound(kind='step'){try{funAudio||=new AudioContext();const context=funAudio,osc=context.createOscillator(),gain=context.createGain(),filter=context.createBiquadFilter(),frequencies={step:58,wire:620,type:940,intercom:1280,error:92,door:44},duration=kind==='wire'?.32:kind==='door'?.55:.16;osc.type=kind==='step'||kind==='door'?'sine':kind==='error'?'sawtooth':'square';osc.frequency.setValueAtTime(frequencies[kind]||440,context.currentTime);if(kind==='wire')osc.frequency.exponentialRampToValueAtTime(240,context.currentTime+duration);filter.type='lowpass';filter.frequency.value=kind==='type'?1800:900;gain.gain.setValueAtTime(kind==='door'?.17:.065,context.currentTime);gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+duration);osc.connect(filter).connect(gain).connect(context.destination);osc.start();osc.stop(context.currentTime+duration)}catch{}}
function startMollyFlare(style='casual',finish='resume-patrol'){if(!molly||molly.flare)return;molly.flare={style,finish,elapsed:0,duration:style==='casual'?1.3:style==='agitated'?1.8:style==='final'?2.3:1.95};document.body.classList.add('molly-flare');playMollySound('wire')}
function cancelMollyFlare(){if(!molly?.flare)return;molly.flare=null;document.body.classList.remove('molly-flare')}
function finishMollyFlare(){const finish=molly.flare?.finish;molly.flare=null;document.body.classList.remove('molly-flare');if(finish==='begin-hack'){molly.phase='hack';molly.timer=3.5;document.body.classList.add('molly-hacking')}else if(finish==='resume-search'){molly.phase='search';molly.timer=6}else if(finish==='final-listen'){molly.phase='final-listen';molly.timer=3.5;molly.finalControlLost=true;mollySetDisplay('00');saveMolly()}else{molly.phase='patrol';molly.selectionTimer=5+Math.random()*5}}
function mollySmoothStep(start,end,value){const amount=THREE.MathUtils.clamp((value-start)/(end-start),0,1);return amount*amount*(3-2*amount)}
function mollyFlarePose(progress,style='focused'){
 const amplitude=style==='casual'?.72:style==='agitated'?1.12:style==='final'?.94:1,reach=mollySmoothStep(.03,.3,progress)*(1-mollySmoothStep(.78,.98,progress)),grip=mollySmoothStep(.19,.31,progress)*(1-mollySmoothStep(.42,.52,progress)),flick=mollySmoothStep(.34,.58,progress)*(1-mollySmoothStep(.76,.98,progress)),fan=mollySmoothStep(.4,.59,progress)*(1-mollySmoothStep(.74,1,progress))*amplitude,settle=mollySmoothStep(.74,1,progress);
 const name=progress<.03?'prepare':progress<.31?'hand-up':progress<.42?'grip-wires':progress<.59?'flick':progress<.76?'follow-through':'settle';return{name,reach,grip,flick,fan,settle,amplitude}
}
function animateMollyRig(dt,time,moving=false,speed=0){
 if(!mollyEntity)return;const rig=mollyEntity.userData,flare=molly?.flare,p=flare?THREE.MathUtils.clamp(flare.elapsed/flare.duration,0,1):0,pose=flare?mollyFlarePose(p,flare.style):mollyFlarePose(1,'focused'),walk=moving?Math.sin(time*(7+speed)):0,alpha=Math.min(1,dt*14);rig.flipStage=flare?pose:{name:'rest',reach:0,grip:0,flick:0,fan:0,settle:0};rig.legs.forEach(({leg,side})=>leg.rotation.x=walk*side*.42);
 rig.arms.forEach((arm,index)=>{const {shoulder,elbow,wrist,side}=arm,isFlipHand=index===1&&flare,hacking=molly?.phase==='hack'||molly?.phase==='final-input';let shoulderX=walk*-side*.18,shoulderY=0,shoulderZ=side*.08,elbowX=0,elbowZ=0,wristX=0,wristZ=0;if(isFlipHand){shoulderX=-.34*pose.reach-.2*pose.flick;shoulderY=-.16*pose.reach-.16*pose.flick;shoulderZ=-.92*pose.reach-1.55*pose.flick-.12*pose.grip;elbowX=-.08*pose.grip;elbowZ=-2.04*pose.reach+1.44*pose.flick;wristX=-.48*pose.grip-.32*pose.flick;wristZ=.28*pose.grip+.76*pose.flick}else if(hacking){shoulderX=-1.02+Math.sin(time*11+index)*.12;shoulderZ=side*.25;elbowZ=-side*(.58+Math.sin(time*9+index)*.08);wristX=Math.sin(time*12+index)*.12}shoulder.rotation.x=THREE.MathUtils.lerp(shoulder.rotation.x,shoulderX,alpha);shoulder.rotation.y=THREE.MathUtils.lerp(shoulder.rotation.y,shoulderY,alpha);shoulder.rotation.z=THREE.MathUtils.lerp(shoulder.rotation.z,shoulderZ,alpha);elbow.rotation.x=THREE.MathUtils.lerp(elbow.rotation.x,elbowX,alpha);elbow.rotation.z=THREE.MathUtils.lerp(elbow.rotation.z,elbowZ,alpha);wrist.rotation.x=THREE.MathUtils.lerp(wrist.rotation.x,wristX,alpha);wrist.rotation.z=THREE.MathUtils.lerp(wrist.rotation.z,wristZ,alpha)});
 rig.head.rotation.z=THREE.MathUtils.lerp(rig.head.rotation.z,molly?.phase==='listening'||molly?.phase==='search-wait'?.18*Math.sin(time*.8):0,Math.min(1,dt*5));rig.wires.forEach(wire=>{const lag=wire.weight,rightGrip=wire.side>0?pose.grip:0,wireLift=pose.fan*(wire.side>0?1:.88),restSway=Math.sin(time*(1.25+wire.rank*.04)+wire.phase)*(.025+(1-lag)*.035),motionSway=moving?Math.sin(time*7+wire.phase)*(.05+(1-lag)*.07):0,targetRotationZ=wire.rest+restSway+motionSway-wire.side*rightGrip*.22+wire.side*wireLift*(2.02+(1-lag)*.25),targetRotationX=-wireLift*(.42+(1-lag)*.2)-Math.min(.22,speed*.025),targetY=wire.restY+rightGrip*(.1+wire.rank*.012)+wireLift*(.22+(1-lag)*.12),targetX=wire.restX-wire.side*rightGrip*.08,targetPositionZ=wire.restZ+rightGrip*.12-wireLift*.18,wireAlpha=Math.min(1,dt*(lag?9:13));wire.root.rotation.z=THREE.MathUtils.lerp(wire.root.rotation.z,targetRotationZ,wireAlpha);wire.root.rotation.x=THREE.MathUtils.lerp(wire.root.rotation.x,targetRotationX,Math.min(1,dt*(5+lag*5)));wire.root.position.x=THREE.MathUtils.lerp(wire.root.position.x,targetX,wireAlpha);wire.root.position.y=THREE.MathUtils.lerp(wire.root.position.y,targetY,wireAlpha);wire.root.position.z=THREE.MathUtils.lerp(wire.root.position.z,targetPositionZ,wireAlpha)});if(flare){flare.elapsed+=dt;if(flare.elapsed>=flare.duration)finishMollyFlare()}
}
function mollyPlayerPosition(){return molly?.cameraView?.playerPosition?new THREE.Vector3(...molly.cameraView.playerPosition):camera.position}
function mollyRouteNodeBlocked(index){return index===23||index===24||index===20&&!molly.droneLatchOpen}
function mollyNearestRouteNode(position){let best=0,distance=Infinity;MOLLY_ROUTE_NODES.forEach((node,index)=>{if(mollyRouteNodeBlocked(index))return;const value=Math.hypot(position[0]-node[0],position[2]-node[2]);if(value<distance){distance=value;best=index}});return best}
function mollyPlanRoute(target){const start=mollyNearestRouteNode([mollyEntity.position.x,0,mollyEntity.position.z]),end=mollyNearestRouteNode(target),queue=[start],previous=new Map([[start,-1]]);while(queue.length){const current=queue.shift();if(current===end)break;for(const next of MOLLY_ROUTE_LINKS[current]||[]){if(mollyRouteNodeBlocked(next)||previous.has(next))continue;previous.set(next,current);queue.push(next)}}const indexes=[];let current=end;while(current!==-1&&previous.has(current)){indexes.unshift(current);current=previous.get(current)}const route=indexes.slice(1).map(index=>[...MOLLY_ROUTE_NODES[index]]);if(!route.length||Math.hypot(route.at(-1)[0]-target[0],route.at(-1)[2]-target[2])>.2)route.push([target[0],0,target[2]]);return route}
function moveMollyToward(target,speed,dt){if(!mollyEntity)return false;const key=`${target[0].toFixed?.(2)??target[0]}:${target[2].toFixed?.(2)??target[2]}`;if(molly.routeTarget!==key||!molly.route?.length){molly.route=mollyPlanRoute(target);molly.routeTarget=key}const waypoint=molly.route[0]||target,destination=new THREE.Vector3(waypoint[0],0,waypoint[2]),direction=destination.clone().sub(mollyEntity.position);direction.y=0;const distance=direction.length();if(distance<.22){molly.route.shift();if(molly.route.length)return moveMollyToward(target,speed,dt);molly.routeTarget='';animateMollyRig(dt,performance.now()*.001,false,0);return true}direction.normalize();mollyEntity.position.addScaledVector(direction,Math.min(distance,speed*dt));const desired=Math.atan2(direction.x,direction.z),delta=Math.atan2(Math.sin(desired-mollyEntity.rotation.y),Math.cos(desired-mollyEntity.rotation.y));mollyEntity.rotation.y+=delta*Math.min(1,dt*6);mollyEntity.userData.turnAmount=delta;molly.stepTimer-=dt;if(molly.stepTimer<=0){playMollySound('step');molly.stepTimer=speed>4?.22:.42}animateMollyRig(dt,performance.now()*.001,true,speed);return false}
function mollyHearSound(position,strength=1,source='sound'){if(!molly||molly.dying||molly.finalControlLost&&source==='computer'||molly.finalUnlocked&&!molly.finalControlLost&&['final-travel','final-input'].includes(molly.phase))return;cancelMollyFlare();document.body.classList.remove('molly-hacking');molly.lastSound=[position.x??position[0],0,position.z??position[2]];molly.soundStrength=strength;molly.route=[];molly.routeTarget='';molly.phase='listening';molly.timer=strength>1?1.15:.7;molly.targetComputer=0;mollySetDisplay('00');document.body.classList.add('molly-listening');if(strength>1)startMollyFlare('focused','resume-search');document.querySelector('#prompt').textContent=`MOLLY HEARD ${source.toUpperCase()} · SHE IS GOING TO THAT LOCATION`;saveMolly()}
function mollyDoorForComputer(number){return MOLLY_DOOR_COMPUTERS.indexOf(number)}
function makeMollyReadout(name,textValue,position,scale=.26){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=160;const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false}));sprite.name=name;sprite.position.set(...position);sprite.scale.set(2.8*scale,.88*scale,1);sprite.renderOrder=6;sprite.userData={canvas,texture,text:''};roomGroup.add(sprite);updateMollyReadout(sprite,textValue);return sprite}
function updateMollyReadout(sprite,textValue){if(!sprite)return;const {canvas,texture}=sprite.userData,context=canvas.getContext('2d'),text=String(textValue);context.clearRect(0,0,canvas.width,canvas.height);context.fillStyle='rgba(5,12,13,.94)';context.fillRect(4,4,504,152);context.strokeStyle=text.includes('ACTIVE')||text.includes('POWERED')?'#63e3a2':text.includes('LOCK')?'#ee6157':'#7fdce5';context.lineWidth=7;context.strokeRect(7,7,498,146);context.fillStyle='#ecf8f2';context.font='700 34px monospace';context.textAlign='center';context.textBaseline='middle';context.fillText(text,256,80);texture.needsUpdate=true;sprite.userData.text=text}
function setMollyDoor(index,open){const door=mollyDoors[index];if(!door)return;door.open=open;door.mesh.position.y=open?5.3:1.7;const existing=solidColliders.find(collider=>collider.mesh===door.mesh);if(open&&existing)solidColliders=solidColliders.filter(collider=>collider!==existing);if(!open&&!existing)solidColliders.push({mesh:door.mesh,halfX:2.9,halfZ:.22,bottom:0,top:3.4});door.indicator.material.emissive.setHex(open?0x1ca86a:0xb71e24);door.indicator.material.emissiveIntensity=3;updateMollyReadout(door.statusLabel,open?`C${mollyComputerLabel(door.computer)} · OPEN`:`C${mollyComputerLabel(door.computer)} · LOCK ACTIVE`)}
function mollyComputerStatus(number,status){const computer=mollyComputers.find(entry=>entry.number===number);if(!computer)return;computer.status=status;computer.indicator.material.color.setHex(status==='override'?0x42db91:status==='hacked'?0xd12b31:0x4ccfe2);computer.indicator.material.emissive.setHex(status==='override'?0x1aa462:status==='hacked'?0x8b1118:0x176779);computer.indicator.material.emissiveIntensity=3;updateMollyReadout(computer.statusLabel,`COMPUTER ${mollyComputerLabel(number)} · ${status==='override'?'OVERRIDE ACTIVE':status==='hacked'?'LOCK ACTIVE':'STANDBY'}`)}
function updateMollyProgressBoard(){mollyProgressLights.forEach((lamp,index)=>{const active=molly.levers.includes(index);lamp.material.color.setHex(active?0x54e39b:0x6a2323);lamp.material.emissive.setHex(active?0x25a96b:0x4b1111);lamp.material.emissiveIntensity=active?4:.65});updateMollyReadout(mollyFinalStatus,molly.finalUnlocked?'EXIT POWERED · DOOR READY':`EXIT POWER · ${molly.levers.length}/3 LEVERS`)}
function hackMollyComputer(number){if(molly.overridden.includes(number))return;const index=mollyDoorForComputer(number);if(!molly.hacked.includes(number))molly.hacked.push(number);mollyComputerStatus(number,'hacked');if(index>=0&&!molly.overridden.includes(number))setMollyDoor(index,false);playMollySound('door');document.querySelector('#prompt').textContent=`COMPUTER ${mollyComputerLabel(number)} HACKED · LINKED SHUTTER CLOSED`;saveMolly()}
function openMollyOverride(number){if(!molly.codesRead)return document.querySelector('#prompt').textContent='THE TERMINAL REQUESTS A CODE · USE THE CLATTERING CODE MACHINE IN RECEPTION FIRST';if(molly.overridden.includes(number))return document.querySelector('#prompt').textContent=`COMPUTER ${mollyComputerLabel(number)} OVERRIDE HOLDS · MOLLY CANNOT UNDO IT`;controls.unlock();base('ELECTRICAL SECTION',`COMPUTER ${mollyComputerLabel(number)} OVERRIDE`,'Enter this terminal’s four-digit unlock code. The computer number on Molly’s face identifies her destination; it is not the code.');const input=document.createElement('input');input.maxLength=4;input.inputMode='numeric';input.placeholder='_ _ _ _';const button=document.createElement('button');button.textContent='OVERRIDE LINKED SHUTTER';button.onclick=()=>{if(input.value.trim()!==mollyComputerCode(number)){feedback.textContent='ACCESS DENIED · The terminal alarm gives Molly this exact location.';playMollySound('error');mollyHearSound(mollyComputers.find(entry=>entry.number===number).mesh.position,1.35,'terminal alarm');return}molly.overridden.push(number);molly.hacked=molly.hacked.filter(value=>value!==number);mollyComputerStatus(number,'override');const index=mollyDoorForComputer(number);if(index>=0)setMollyDoor(index,true);saveMolly();dlg.close();pickupTone();document.querySelector('#prompt').textContent=`COMPUTER ${mollyComputerLabel(number)} OVERRIDDEN · LINKED SHUTTER PERMANENTLY OPEN`;molly.lastSound=[...MOLLY_COMPUTER_POSITIONS[number-1]];molly.soundStrength=1.2;molly.route=[];molly.routeTarget='';molly.phase='listening';mollySetDisplay('00');cancelMollyFlare();startMollyFlare('agitated','resume-search')};body.append(input,button)}
function triggerMollyCodeMachine(){molly.codesRead=true;saveMolly();playPurgeCrash();mollyHearSound(new THREE.Vector3(0,0,21.5),1.4,'the code machine');objective.textContent=`Printed codes: C02 ${mollyComputerCode(2)} · C04 ${mollyComputerCode(4)} · C06 ${mollyComputerCode(6)}. Reach each lever; override only shutters Molly has locked.`;message('DOOR OVERRIDE CODES',`COMPUTER 02 · ${mollyComputerCode(2)}   //   COMPUTER 04 · ${mollyComputerCode(4)}   //   COMPUTER 06 · ${mollyComputerCode(6)}. The slip is kept. Molly heard the machine, not your new position.`)}
function openMollyDroneLatch(){if(molly.droneLatchOpen)return;const blocker=roomGroup.getObjectByName('Molly drone shortcut blocker'),hatch=roomGroup.getObjectByName('Molly drone shortcut hatch');blocker?.removeFromParent();solidColliders=solidColliders.filter(collider=>collider.mesh!==blocker);if(hatch)hatch.position.y=4.9;molly.droneLatchOpen=true;saveMolly()}
function mollyDroneDistraction(){if(!molly||hotelSideScene!=='molly-electrical')return false;const route=MOLLY_DRONE_ROUTES[molly.droneRouteIndex%MOLLY_DRONE_ROUTES.length];molly.droneRouteIndex++;openMollyDroneLatch();playMollySound('intercom');mollyHearSound(new THREE.Vector3(...route.position),1,'the drone beep');if(!molly.cameraView){molly.cameraView={kind:'drone',label:route.label,position:[route.position[0],4.6,route.position[2]+2.2],look:[route.position[0],1,route.position[2]],playerPosition:[camera.position.x,camera.position.y,camera.position.z],playerQuaternion:[camera.quaternion.x,camera.quaternion.y,camera.quaternion.z,camera.quaternion.w],timer:4};controls.unlock()}document.querySelector('#prompt').textContent=`DRONE · ${route.label} · SHORTCUT LATCH RELEASED · AUTO-RECALL IN 4 SECONDS`;saveMolly();return true}
function startMollyCameraFeed(){if(molly.cameraView)return;const index=molly.cameraFeedIndex%MOLLY_CAMERA_FEEDS.length,feed=MOLLY_CAMERA_FEEDS[index];molly.cameraFeedIndex=(index+1)%MOLLY_CAMERA_FEEDS.length;molly.cameraView={kind:'security',feedIndex:index,label:feed.label,position:feed.position,look:feed.look,playerPosition:[camera.position.x,camera.position.y,camera.position.z],playerQuaternion:[camera.quaternion.x,camera.quaternion.y,camera.quaternion.z,camera.quaternion.w],timer:7};controls.unlock();document.querySelector('#prompt').textContent=`CAM ${String(index+1).padStart(2,'0')} · ${feed.label} · LIVE · RETURNING IN 7 SECONDS`;saveMolly()}
function endMollyCameraFeed(){if(!molly?.cameraView)return;const view=molly.cameraView;molly.cameraView=null;camera.position.set(...view.playerPosition);camera.quaternion.set(...view.playerQuaternion);if(storySelect.hidden&&!dlg.open)controls.lock();document.querySelector('#prompt').textContent='CAMERA FEED CLOSED · YOUR POSITION DID NOT MOVE'}
document.addEventListener('keydown',event=>{if(event.code==='Escape'&&molly?.cameraView){event.preventDefault();event.stopImmediatePropagation();endMollyCameraFeed()}},true);
function pullMollyLever(index){if(molly.levers.includes(index))return;molly.levers.push(index);const lever=mollyLevers[index];if(lever){lever.rotation.z=-.72;lever.userData.indicator.material.color.setHex(0x55e7a0);lever.userData.indicator.material.emissive.setHex(0x26a96c);lever.userData.housing.material.emissive.setHex(0x174f36);updateMollyReadout(lever.userData.statusLabel,`MAIN LEVER ${index+1} · ENGAGED`)}pickupTone();playMollySound('door');if(molly.levers.length===3){molly.finalUnlocked=true;cancelMollyFlare();document.body.classList.remove('molly-hacking','molly-listening');objective.textContent='All three levers hold. Reach the powered final exit; Molly cannot cancel it.';document.querySelector('#prompt').textContent='FINAL EXIT POWERED · NO ADDITIONAL CODE REQUIRED';molly.phase='final-travel';molly.route=[];molly.routeTarget='';molly.lastSound=[...MOLLY_COMPUTER_POSITIONS[5]];mollySetDisplay('00');horrorStinger()}else document.querySelector('#prompt').textContent=`LEVER ${index+1} ENGAGED PERMANENTLY · ${3-molly.levers.length} REMAIN`;updateMollyProgressBoard();saveMolly();setMollyHud()}
function handleMolly(part,trigger){if(!molly||molly.dying)return;if(part==='code-machine')return triggerMollyCodeMachine();if(part.startsWith('computer:'))return openMollyOverride(Number(part.slice(9)));if(part.startsWith('lever:'))return pullMollyLever(Number(part.slice(6)));if(part==='hammer'){if(molly.hammerTaken)return;molly.hammerTaken=true;hotelRunItems.add('electrical-hammer');saveHotelRun();saveMolly();updateInventory();playFirstPersonAction('pickup','electrical-hammer',.7);return document.querySelector('#prompt').textContent='INSULATED HAMMER ACQUIRED · YELLOW-BLACK WINDOW FRAMES ARE BREAKABLE'}if(part==='drone'){if(molly.droneTaken)return;molly.droneTaken=true;hotelRunItems.add('drone-controller');saveHotelRun();saveMolly();updateInventory();playFirstPersonAction('pickup','drone-controller',.7);return document.querySelector('#prompt').textContent='MAINTENANCE DRONE ACQUIRED · SELECT IT AND PRESS Q FOR A FEED, LATCH, AND DISTRACTION'}if(part==='window'){if(molly.brokenWindow)return;if(!molly.hammerTaken)return document.querySelector('#prompt').textContent='YELLOW-BLACK SHORTCUT WINDOW · INSULATED HAMMER REQUIRED';molly.brokenWindow=true;playFirstPersonAction('use','electrical-hammer',.62);playPurgeCrash();mollyHearSound(new THREE.Vector3(24,0,-16),1.6,'the breaking window');const pane=roomGroup.getObjectByName('Molly breakable safety window'),blocker=roomGroup.getObjectByName('Molly breakable window blocker');if(pane)pane.visible=false;blocker?.removeFromParent();solidColliders=solidColliders.filter(collider=>collider.mesh!==blocker);saveMolly();return document.querySelector('#prompt').textContent='SHORTCUT WINDOW OPEN · CLIMB THROUGH AND MOVE · MOLLY IS COMING TO THE CRASH'}if(part==='camera')return startMollyCameraFeed();if(part==='exit'){if(!molly.finalUnlocked)return document.querySelector('#prompt').textContent=`FINAL EXIT UNPOWERED · ${3-molly.levers.length} LEVERS REMAIN`;return beginHotelRoomPassage(trigger,leaveMollySection)}}
function makeMollyTerminal(number,position){const side=position[0]<0?-1:1,linked=MOLLY_DOOR_COMPUTERS.includes(number),consoleZ=position[2]+1.2,mesh=box(`Molly computer ${number}`,[position[0],1.25,consoleZ],[2.7,2.5,1.45],0x26373d,true),screen=box(`Molly computer ${number} screen`,[position[0]-side*.05,1.72,consoleZ-.74],[1.75,.86,.08],0x10292c,false),indicator=sphere(`Molly computer ${number} indicator`,[position[0]+.95,2.17,consoleZ-.78],.075,0x4ccfe2);screen.material.emissive.setHex(0x124c53);screen.material.emissiveIntensity=2;indicator.material.emissive.setHex(0x176779);indicator.material.emissiveIntensity=3;const interactionPosition=[position[0],1.35,consoleZ-1.05];if(linked)interactive(interactionPosition,[3.1,2.8,1.5],8,'molly',`computer:${number}`);objectLabel(`COMPUTER ${mollyComputerLabel(number)}${linked?' · DOOR CONTROL':' · HOTEL SYSTEM'}`,[position[0],3.35,consoleZ-.85],.28);const statusLabel=makeMollyReadout(`Molly computer ${number} status`,`COMPUTER ${mollyComputerLabel(number)} · STANDBY`,[position[0],2.72,consoleZ-.87],.22),computer={number,mesh,screen,indicator,statusLabel,status:'idle'};mollyComputers.push(computer);if(molly.overridden.includes(number))mollyComputerStatus(number,'override');else if(molly.hacked.includes(number))mollyComputerStatus(number,'hacked');return computer}
function makeMollyIntercom(position,index){const panel=box(`active antenna intercom ${index}`,[position[0],2.15,position[2]],[.48,.92,.3],0x39474b,false),grille=box(`intercom speaker grille ${index}`,[position[0],2.13,position[2]-.17],[.31,.48,.04],0x11191b,false),lamp=sphere(`intercom indicator ${index}`,[position[0],2.49,position[2]-.2],.075,0x3ee4d3);lamp.material.emissive.setHex(0x1b978c);lamp.material.emissiveIntensity=3;const antenna=new THREE.Mesh(new THREE.CylinderGeometry(.025,.04,.78,6),mat(0x69787d,.25));antenna.position.set(position[0],2.96,position[2]);antenna.rotation.z=.28;roomGroup.add(antenna);const zone=new THREE.Mesh(new THREE.CircleGeometry(3.05,32),new THREE.MeshBasicMaterial({color:0x2cc8bd,transparent:true,opacity:.09,depthWrite:false}));zone.name=`intercom monitored floor marking ${index}`;zone.rotation.x=-Math.PI/2;zone.position.set(position[0],.018,position[2]);roomGroup.add(zone);mollyIntercoms.push({position:new THREE.Vector3(...position),panel,grille,lamp,antenna,zone,cooldown:0,transmitTimer:0,index})}
function makeMollyBrokenIntercom(position,index){box(`broken intercom ${index}`,[position[0],2.1,position[2]],[.48,.9,.3],0x20282a,false);const antenna=new THREE.Mesh(new THREE.CylinderGeometry(.025,.04,.58,6),mat(0x4b5051,.7));antenna.position.set(position[0]-.12,2.72,position[2]);antenna.rotation.z=1.05;roomGroup.add(antenna);objectLabel('INTERCOM OFFLINE',[position[0],3.25,position[2]],.18)}
function makeMollyCabinet(name,position,size=[3,3.4,3]){const cabinet=box(name,[position[0],size[1]/2,position[2]],size,0x2b393b,true),window=box(`${name} inspection window`,[position[0],size[1]*.65,position[2]-size[2]/2-.03],[size[0]*.58,.58,.06],0x132326,false);window.material.transparent=true;window.material.opacity=.72;for(let x=-.7;x<=.7;x+=.7){const lamp=sphere(`${name} status light`,[position[0]+x,size[1]*.35,position[2]-size[2]/2-.08],.055,x===0?0xd69645:0x43d6bd);lamp.material.emissive.setHex(x===0?0x7b4217:0x176f68);lamp.material.emissiveIntensity=3}return cabinet}
function makeMollyCableRun(axis,position,length){const tray=box('open cable support tray',position,axis==='z'?[1.1,.16,length]:[length,.16,1.1],0x4b5556,false);for(const offset of [-.3,-.1,.12,.33]){const wire=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,length,6),mat(offset>.2?0x845534:0x151c1e,.65));if(axis==='z')wire.rotation.x=Math.PI/2;else wire.rotation.z=Math.PI/2;wire.position.set(position[0]+(axis==='z'?offset:0),position[1]-.08,position[2]+(axis==='x'?offset:0));roomGroup.add(wire)}return tray}
function makeMollySecurityCamera(position,label){const group=new THREE.Group(),bracket=new THREE.Mesh(new THREE.BoxGeometry(.16,.38,.16),mat(0x4f5d60,.35)),bodyMesh=new THREE.Mesh(new THREE.BoxGeometry(.55,.32,.72),mat(0x313d40,.3)),lens=new THREE.Mesh(new THREE.CylinderGeometry(.13,.17,.18,14),mat(0x10191c,.15,0x113b42));bracket.position.y=.2;bodyMesh.position.set(0,-.08,-.28);lens.rotation.x=Math.PI/2;lens.position.set(0,-.08,-.69);group.add(bracket,bodyMesh,lens);group.position.set(...position);group.name=`security camera ${label}`;roomGroup.add(group);mollyCameras.push(group);return group}
function makeMollyLever(index,position){const active=molly.levers.includes(index),housing=box(`objective lever ${index+1} housing`,[position[0],1.45,position[2]],[1.6,2.5,.8],0x3b4a4e,false),border=box(`objective lever ${index+1} protective border`,[position[0],1.45,position[2]-.46],[2.1,2.9,.12],0x87908b,false),indicator=sphere(`objective lever ${index+1} indicator`,[position[0],2.35,position[2]-.58],.12,active?0x55e7a0:0x7a2929),lever=new THREE.Mesh(new THREE.BoxGeometry(.2,1.18,.24),mat(0xc44232,.3,0x5b100c)),statusLabel=makeMollyReadout(`objective lever ${index+1} status`,`MAIN LEVER ${index+1} · ${active?'ENGAGED':'READY'}`,[position[0],3.45,position[2]-.7],.25);lever.position.set(position[0],1.55,position[2]-.55);lever.rotation.z=active?-.72:.5;lever.userData={housing,indicator,statusLabel};housing.material.emissive.setHex(active?0x174f36:0x2b0c0d);indicator.material.emissive.setHex(active?0x26a96c:0x4b1111);indicator.material.emissiveIntensity=3;roomGroup.add(lever);mollyLevers.push(lever);interactive([position[0],1.55,position[2]-.8],[2.5,3.1,1.5],8,'molly',`lever:${index}`);return lever}
function buildMollyElectrical(){
 resetHotelSideScene();activeStory='hotel';room=8;hotelSideScene='molly-electrical';molly.boundary=32;molly.route=[];molly.routeTarget='';renderer.toneMappingExposure=1.05;scene.background.setHex(0x101616);scene.fog.color.setHex(0x152120);scene.fog.density=.012;
 box('electrical maintenance tile floor',[0,-.15,0],[56,.3,64],0x353b38,false);box('electrical old hotel ceiling',[0,6.35,8],[56,.25,48],0x262c29,false);box('high final switch room ceiling',[0,7.9,-24],[56,.25,16],0x171f1f,false);box('electrical west exterior wall',[-28,3.4,0],[.4,6.8,64],0x777467,true);box('electrical east exterior wall',[28,3.4,0],[.4,6.8,64],0x777467,true);box('electrical north wall',[0,3.4,32],[56,6.8,.4],0x777467,true);box('electrical south wall',[0,4,-32],[56,8,.4],0x485452,true);
 for(const x of [-27.72,27.72]){for(let z=27;z>-29;z-=8)box('faded hotel wallpaper panel',[x,2.7,z],[.08,4.7,6.4],z%16?0x777564:0x6d776a,false);box('dark hotel wood base trim',[x,.42,0],[.14,.55,63],0x30241e,false)}for(const z of [31.72,18.18,-15.82])box('dark hotel wood header trim',[0,5.35,z],[55,.24,.16],0x30241e,false);
 for(const [x,width] of [[-21,14],[-11,6],[0,16],[11,6],[21,14]])if(![-11,11].includes(x))box('maintenance reception south wall',[x,3.2,18],[width,6.4,.34],0x777467,true);for(const x of [-14,-8,8,14])box('reception doorway wood frame',[x,2.2,17.78],[.28,4.4,.28],0x352720,false);box('reception center wall trim',[0,.48,17.78],[16,.65,.18],0x352720,false);
 box('maintenance reception desk',[0,.72,25],[8,1.45,1.7],0x49372a,true);for(const x of [-2.8,-.95,.95,2.8])box('reception filing drawer',[x,.72,24.08],[1.55,.46,.15],0x293638,false);box('electrical layout board',[0,3.65,31.72],[11,3.1,.1],0x314447,false);objectLabel('ELECTRICAL SECTION · ROUTE BOARD',[0,5.25,31.55],.35);for(const [x,z] of [[-3.4,29.5],[0,28.8],[3.4,29.5]])box('layout route line',[x,3.65,31.61],[2.2,.12,.04],0x55c7b5,false);
 box('DOOR OVERRIDE CODES machine',[0,1.55,23.75],[3.5,2.6,1.5],0x39484a,true);box('code machine display',[0,2.05,22.96],[2.3,.7,.08],0x10282b,false).material.emissive.setHex(0x14545b);box('code machine activation plate',[0,1.1,22.91],[1.4,.32,.09],0xb78645,false);box('code machine output slot',[0,1.58,22.91],[1.9,.18,.11],0x090e0f,false);interactive([0,1.55,22.65],[3.8,3,1.6],8,'molly','code-machine');objectLabel('DOOR OVERRIDE CODES · E TAP',[0,3.45,22.8],.3);
 if(!molly.hammerTaken){box('insulated hammer',[-5,.82,25],[1.6,.18,.34],0xb36b3d,false);interactive([-5,.95,24.4],[2.3,1.8,1.5],8,'molly','hammer');objectLabel('INSULATED HAMMER · E TAKE',[-5,2,24.4],.22)}if(!molly.droneTaken){box('maintenance drone controller',[5,.9,25],[1.15,.38,.78],0x35545b,false);interactive([5,1,24.4],[2.2,1.8,1.6],8,'molly','drone');objectLabel('DRONE CONTROLLER · E TAKE',[5,2,24.4],.22)}box('security camera console',[7.2,1.35,28.8],[2.5,2.3,1.1],0x26373d,true);interactive([7.2,1.5,28.05],[2.9,2.6,1.5],8,'molly','camera');objectLabel('CAMERA FEEDS · E NEXT VIEW',[7.2,3.05,28],.23);
 makeMollyCabinet('north transformer bank',[0,0,8],[10,3.8,7]);makeMollyCabinet('south relay bank',[0,0,-7],[10,3.8,7]);for(const [x,z] of [[-25,10],[-25,-7],[25,10],[25,-7]])makeMollyCabinet('perimeter electrical cabinet',[x,0,z],[2.8,3.5,4.2]);
 for(const x of [-17,17])box('faded painted route marking',[x,.015,1],[.24,.03,30],0xb89c51,false);for(const z of [13,0,-13])box('faded cross-route marking',[0,.016,z],[34,.035,.2],0x5faaa0,false);objectLabel('← WEST LOOP · FAN JUNCTION · EAST LOOP →',[0,4.65,14.5],.3);objectLabel('LEVER ROOMS · SOUTH',[0,4.4,-12.8],.27);
 const fanHub=new THREE.Group();fanHub.name='ventilation fan landmark';const fanRing=new THREE.Mesh(new THREE.TorusGeometry(1.25,.16,8,28),mat(0x586261,.38));fanHub.add(fanRing);for(let blade=0;blade<6;blade++){const mesh=new THREE.Mesh(new THREE.BoxGeometry(.28,1.25,.12),mat(0x455153,.32));mesh.position.y=.58;mesh.rotation.z=blade*Math.PI/3;fanHub.add(mesh)}fanHub.position.set(0,3.75,-10.62);roomGroup.add(fanHub);mollyFans.push(fanHub);objectLabel('VENTILATION FAN JUNCTION',[0,5.4,-10.5],.24);box('broken maintenance trolley',[-8,.62,-12],[3.6,1.2,1.7],0x4a5150,true);for(const x of [-9.3,-6.7])for(const z of [-12.65,-11.35])sphere('trolley wheel',[x,.17,z],.18,0x15191a);objectLabel('WINDOW SHORTCUT →',[-11,2.1,-12],.2);
 makeMollyCableRun('z',[-11.5,5.65,1],32);makeMollyCableRun('z',[11.5,5.65,1],32);makeMollyCableRun('x',[0,5.5,13],34);makeMollyCableRun('x',[0,4.65,0],34);for(const x of [-12,-4,4,12])box('low hanging cable warning',[x,3.15,0],[.42,.32,4.5],0x171d1e,false);objectLabel('LOW CEILING CABLES',[0,3.7,1.8],.2);
 MOLLY_COMPUTER_POSITIONS.forEach((position,index)=>makeMollyTerminal(index+1,position));
 const frontSegments=[[-26.75,2.5],[-21.75,1.5],[-9,12],[9,12],[21.75,1.5],[26.75,2.5]];for(const [x,width] of frontSegments)box('lever room front wall',[x,3.2,-16],[width,6.4,.36],0x65706a,true);box('lever room continuous lintel',[0,5.25,-16],[56,2.3,.38],0x4a5652,true);for(const x of [-9,9])box('lever room divider',[x,4,-24],[.35,8,16],0x4b5753,true);
 const doorCenters=[-18,0,18];doorCenters.forEach((x,index)=>{const computer=MOLLY_DOOR_COMPUTERS[index],mesh=box(`Molly linked shutter ${index+1}`,[x,1.7,-16],[5.8,3.4,.44],0x4c5c61,false),indicator=box(`Molly shutter ${index+1} indicator`,[x,4.25,-15.72],[1,.28,.18],0xb71e24,false),statusLabel=makeMollyReadout(`Molly shutter ${index+1} status`,`C${mollyComputerLabel(computer)} · OPEN`,[x,4.65,-15.65],.2);mollyDoors.push({mesh,indicator,statusLabel,index,computer,open:true});const open=!molly.hacked.includes(computer)||molly.overridden.includes(computer);setMollyDoor(index,open)});
 const reinforced=box('reinforced observation window',[-24,2.25,-16],[3,3.6,.24],0x4d7778,true);reinforced.material.transparent=true;reinforced.material.opacity=.42;for(const x of [-25.55,-22.45])box('reinforced window frame',[x,2.25,-15.78],[.18,3.9,.3],0xb4b05f,false);objectLabel('LEVER 01 OBSERVATION · REINFORCED',[-24,4.65,-15.6],.19);
 const breakPane=box('Molly breakable safety window',[24,2.25,-16],[3,3.6,.18],0x527f82,false);breakPane.material.transparent=true;breakPane.material.opacity=molly.brokenWindow?0:.48;for(const x of [-25.55,-22.45,22.45,25.55])box('window frame warning stripe',[x,2.25,-15.76],[.18,3.9,.3],0xd0a43b,false);const breakBlocker=box('Molly breakable window blocker',[24,2,-16],[3,4,.22],0x000000,true);breakBlocker.visible=false;if(molly.brokenWindow){breakBlocker.removeFromParent();solidColliders=solidColliders.filter(collider=>collider.mesh!==breakBlocker)}interactive([24,2,-15.35],[3.5,4.1,1.4],8,'molly','window');objectLabel(molly.brokenWindow?'SHORTCUT OPEN':'HAMMER SHORTCUT · YELLOW FRAME',[24,4.65,-15.55],.22);
 makeMollyCabinet('lever one equipment',[-22,0,-24],[3.3,3.7,5]);for(const z of [-21,-25])makeMollyCabinet('lever two aisle cabinet',[-4.8,0,z],[2.2,3.5,2.7]);for(const z of [-21,-25])makeMollyCabinet('lever two aisle cabinet',[4.8,0,z],[2.2,3.5,2.7]);box('lever three maintenance office desk',[20,.72,-25],[6,1.4,1.5],0x49372a,true);makeMollyLever(0,[-18,0,-27.6]);makeMollyLever(1,[0,0,-27.6]);makeMollyLever(2,[18,0,-27.6]);
 box('final exit status board',[0,4.1,-30.9],[9,2.5,.18],0x223033,false);mollyFinalStatus=makeMollyReadout('Molly final exit status','EXIT POWER · 0/3 LEVERS',[0,4.15,-30.75],.36);for(const x of [-2.2,0,2.2]){const lamp=sphere('final exit lever connection',[x,3.35,-30.68],.18,0x6a2323);mollyProgressLights.push(lamp)}updateMollyProgressBoard();
 makeMollyIntercom([-10,0,14],0);makeMollyIntercom([10,0,1],1);makeMollyIntercom([-2.6,0,-13],2);makeMollyIntercom([18,0,-13],3);makeMollyBrokenIntercom([-26.5,0,-2],0);makeMollyBrokenIntercom([26.5,0,15],1);
 box('drone shortcut partition west',[-7.7,3.2,0],[10.6,6.4,.35],0x55625d,true);box('drone shortcut partition east',[7.7,3.2,0],[10.6,6.4,.35],0x55625d,true);const shortcutHatch=box('Molly drone shortcut hatch',[0,molly.droneLatchOpen?4.9:1.65,0],[4.8,3.3,.35],0x4b5958,false),shortcutBlocker=box('Molly drone shortcut blocker',[0,1.65,0],[4.8,3.3,.38],0x000000,true);shortcutBlocker.visible=false;if(molly.droneLatchOpen){shortcutBlocker.removeFromParent();solidColliders=solidColliders.filter(collider=>collider.mesh!==shortcutBlocker)}for(const x of [-2.6,2.6])box('drone vent frame',[x,1.7,0],[.25,3.5,.5],0x8a8f7f,false);objectLabel(molly.droneLatchOpen?'MAINTENANCE SHORTCUT OPEN':'DRONE SERVICE LATCH',[0,3.7,-.25],.22);
 makeMollySecurityCamera([0,5.7,29],'reception');makeMollySecurityCamera([-12,5.5,12],'computer 02');makeMollySecurityCamera([0,5.1,3],'fan junction');makeMollySecurityCamera([12,5.5,12],'computer 04');makeMollySecurityCamera([12,5.6,-10],'lever approach');makeMollySecurityCamera([0,7.1,-28],'final room');for(const [x,z] of [[0,27],[-11,18],[11,18],[-17,9],[17,9],[-17,-8],[17,-8],[0,-14],[-18,-24],[0,-24],[18,-24]])light([x,z<-16?6.7:5.35,z],z<-16?0xe6b96f:0x83c7bd,z<-16?7.5:6.2,9);light([0,4.8,23.5],0xd7b16d,9,11);const electricalAmbient=new THREE.HemisphereLight(0xaabdb7,0x17201e,1.3);roomGroup.add(electricalAmbient);for(const [z,color,intensity] of [[24,0xd7b577,58],[8,0x8fc7bd,44],[-8,0x74aaa4,40],[-24,0xd7b577,52]]){const fill=new THREE.PointLight(color,intensity,25,1.55);fill.position.set(0,z<-16?6:4.7,z);roomGroup.add(fill)}
 const exitTrigger=addSeamlessHotelPassage({depth:64,width:56,height:8,x:0,doorWidth:6.5,wall:0x4b5753,floor:0x353b38,door:0x3f4d4d,label:'PROTECTED SERVICE CORRIDOR',type:'molly',part:'exit'});exitTrigger.userData.hotelPassage.door.name='Molly final exit door';exitTrigger.userData.hotelPassage.blocker.name='Molly final exit blocker';
 mollyEntity=makeMollyModel();mollyEntity.position.set(0,0,13);roomGroup.add(mollyEntity);camera.position.set(0,1.7,20.8);camera.lookAt(0,1.7,24);chapter.textContent='HOTEL NOCTURNE · ELECTRICAL SECTION';title.textContent='Molly · Door Control Network';description.textContent='An old hotel maintenance wing has been threaded with newer cabinets, cable trays, antenna intercoms, security shutters, and looping routes.';objective.textContent=molly.codesRead?`Printed codes: C02 ${mollyComputerCode(2)} · C04 ${mollyComputerCode(4)} · C06 ${mollyComputerCode(6)}. Reach and permanently engage all three main levers.`:'Use the loud code machine in reception, leave through either doorway, and learn the connected loops. Crouch only beneath active antenna intercoms.';document.querySelector('#prompt').textContent='RECEPTION HAS TWO EXITS · ACTIVE ANTENNAS PULSE OVER MARKED FLOOR ZONES';setRoomNumber('ELECTRICAL');setMollyHud();saveMolly();setTimeout(()=>controls.lock(),100)
}
function startMolly(fresh=false,origin='floor2'){if(floorTwo)saveFloorTwo();floorFive=null;floorOne=null;floorTwo=null;collector=null;clockmaker=null;drowned=null;pursuer=null;cancelNoise();cancelHotelNoiseArc();molly=fresh?newMollyRun(origin):loadMolly(origin);buildMollyElectrical();if(fresh)message('MOLLY · ELECTRICAL SECTION','Watch her screen. 00 means no computer is selected; a number identifies the terminal she will physically visit and hack.')}
function setMollyHud(){if(!molly)return;const phaseNames={patrol:'PATROLLING · 00','patrol-wait':'LISTENING · 00',select:`SELECTED · ${molly.display}`,'computer-travel':`APPROACHING · ${molly.display}`,hack:`HACKING · ${molly.display}`,listening:'SOUND DETECTED · 00',search:'INVESTIGATING · 00','search-wait':'SEARCHING · 00','final-travel':'FINAL CONTROL LOST','final-input':'ACCESS DENIED · 00','final-listen':'LISTENING · 00'},copy=molly.phase==='hack'?`Molly is physically operating Computer ${molly.display}. Its linked shutter closes only when her input completes.`:molly.phase==='computer-travel'?`Molly chose Computer ${molly.display}. The number remains trustworthy throughout her approach.`:molly.finalUnlocked?'The exit controls no longer answer Molly. She remains dangerous until you leave.':'Crouch beneath antennas. Loud actions send Molly to the place where the sound occurred.';setBossEncounterHud(true,'MOLLY',phaseNames[molly.phase]||'LISTENING · 00',copy,molly.levers.length/3)}
function failMolly(){if(adminPreventDeath('MOLLY COULD NOT CATCH YOU'))return;if(!molly||molly.dying)return;molly.dying=true;saveMolly();controls.unlock();horrorStinger();const blackout=document.querySelector('#blackout');blackout.querySelector('span').textContent='MOLLY FOUND THE SOURCE';blackout.classList.add('show');setTimeout(()=>{molly.dying=false;molly.phase='patrol';molly.grace=4;molly.display='00';molly.targetComputer=0;buildMollyElectrical();blackout.classList.remove('show');blackout.querySelector('span').textContent='You wake inside the cabin.'},950)}
function leaveMollySection(){localStorage.setItem('hotel-molly-complete','true');sessionStorage.removeItem('hotel-molly-run');molly=null;renderer.toneMappingExposure=.78;setBossEncounterHud(false);floorTwo=loadFloorTwo()||newFloorTwoRun();floorTwo.phase=19;buildFloorTwoSafe();message('MOLLY · EXIT OVERRIDE HELD','The final system ignored Molly’s last input. Behind the maintenance door, her cables settle and her screen returns to 00.')}
function updateMolly(dt,time){
 if(!molly||hotelSideScene!=='molly-electrical'||molly.dying||dlg.open)return;molly.grace=Math.max(0,molly.grace-dt);molly.soundCooldown=Math.max(0,molly.soundCooldown-dt);molly.intercomCooldown=Math.max(0,molly.intercomCooldown-dt);const player=mollyPlayerPosition();
 mollyFans.forEach((fan,index)=>fan.rotation.z+=dt*(index%2?-.72:.72));
 if(molly.cameraView){molly.cameraView.timer-=dt;camera.position.set(...molly.cameraView.position);camera.lookAt(...molly.cameraView.look);if(molly.cameraView.timer<=0)endMollyCameraFeed()}
 if(molly.flare){animateMollyRig(dt,time,false,0);setMollyHud();return}
 if(molly.phase==='patrol'){molly.selectionTimer-=dt;const target=MOLLY_PATROL_POINTS[molly.patrolIndex%MOLLY_PATROL_POINTS.length];if(moveMollyToward(target,1.45,dt)){molly.phase='patrol-wait';molly.timer=1.1+Math.random()*1.2}if(molly.selectionTimer<=0){const candidates=MOLLY_DOOR_COMPUTERS.filter(number=>!molly.overridden.includes(number));if(candidates.length){molly.targetComputer=candidates[Math.floor(Math.random()*candidates.length)];mollySetDisplay(molly.targetComputer);molly.phase='select';molly.timer=.9;document.querySelector('#prompt').textContent=`MOLLY’S SCREEN CHANGED TO ${molly.display} · SHE CHOSE COMPUTER ${molly.display}`;}else molly.selectionTimer=8}
 }else if(molly.phase==='patrol-wait'){animateMollyRig(dt,time,false,0);molly.timer-=dt;mollyEntity.rotation.y+=Math.sin(time*.9)*dt*.2;if(molly.timer<=0){if(Math.random()<.3)startMollyFlare('casual','resume-patrol');else{molly.patrolIndex=(molly.patrolIndex+1)%MOLLY_PATROL_POINTS.length;molly.phase='patrol'}}
 }else if(molly.phase==='select'){animateMollyRig(dt,time,false,0);molly.timer-=dt;const target=MOLLY_COMPUTER_POSITIONS[molly.targetComputer-1],direction=new THREE.Vector3(...target).sub(mollyEntity.position);mollyEntity.rotation.y+=Math.atan2(Math.sin(Math.atan2(direction.x,direction.z)-mollyEntity.rotation.y),Math.cos(Math.atan2(direction.x,direction.z)-mollyEntity.rotation.y))*Math.min(1,dt*5);if(molly.timer<=0)molly.phase='computer-travel'
 }else if(molly.phase==='computer-travel'){const target=MOLLY_COMPUTER_POSITIONS[molly.targetComputer-1];if(moveMollyToward(target,2.05,dt)){startMollyFlare('focused','begin-hack');document.querySelector('#prompt').textContent=`MOLLY REACHED COMPUTER ${molly.display} · WATCH HER HAND LIFT THE WIRES`}}
 else if(molly.phase==='hack'){animateMollyRig(dt,time,false,0);molly.timer-=dt;if(Math.floor(molly.timer*6)%2===0&&molly.soundCooldown<=0){playMollySound('type');molly.soundCooldown=.22}if(molly.timer<=0){document.body.classList.remove('molly-hacking');hackMollyComputer(molly.targetComputer);molly.targetComputer=0;mollySetDisplay('00');molly.phase='patrol';molly.selectionTimer=5+Math.random()*5;molly.patrolIndex=(molly.patrolIndex+1)%MOLLY_PATROL_POINTS.length}}
 else if(molly.phase==='listening'){animateMollyRig(dt,time,false,0);molly.timer-=dt;if(molly.lastSound){const target=new THREE.Vector3(...molly.lastSound),direction=target.sub(mollyEntity.position);mollyEntity.rotation.y+=Math.atan2(Math.sin(Math.atan2(direction.x,direction.z)-mollyEntity.rotation.y),Math.cos(Math.atan2(direction.x,direction.z)-mollyEntity.rotation.y))*Math.min(1,dt*7)}if(molly.timer<=0){document.body.classList.remove('molly-listening');molly.phase='search';molly.timer=6}}
 else if(molly.phase==='search'){if(moveMollyToward(molly.lastSound||[0,0,0],molly.soundStrength>1?4.7:2.75,dt)){molly.phase='search-wait';molly.timer=2.4;document.querySelector('#prompt').textContent='MOLLY REACHED THE REPORTED LOCATION · SHE IS LISTENING THERE'}}
 else if(molly.phase==='search-wait'){animateMollyRig(dt,time,false,0);molly.timer-=dt;mollyEntity.rotation.y+=Math.sin(time*1.6)*dt*.48;if(molly.timer<=0){molly.phase='patrol';molly.selectionTimer=4+Math.random()*5;molly.patrolIndex=(molly.patrolIndex+1)%MOLLY_PATROL_POINTS.length}}
 else if(molly.phase==='final-travel'){if(moveMollyToward(MOLLY_COMPUTER_POSITIONS[5],1.8,dt)){molly.phase='final-input';molly.timer=2.6;document.querySelector('#prompt').textContent='MOLLY TRIES COMPUTER 06 · THE FINAL SYSTEM DOES NOT ANSWER'}}
 else if(molly.phase==='final-input'){animateMollyRig(dt,time,false,0);molly.timer-=dt;if(molly.timer<=0){playMollySound('error');startMollyFlare('final','final-listen')}}
 else if(molly.phase==='final-listen'){animateMollyRig(dt,time,false,0);molly.timer-=dt;if(molly.timer<=0){molly.phase='patrol';molly.selectionTimer=20}}
 for(const intercom of mollyIntercoms){intercom.cooldown=Math.max(0,intercom.cooldown-dt);intercom.transmitTimer=Math.max(0,intercom.transmitTimer-dt);const transmitting=intercom.transmitTimer>0,pulse=.065+(Math.sin(time*3.5+intercom.index)+1)*.035;intercom.zone.material.opacity=transmitting?.2:pulse;intercom.lamp.material.emissiveIntensity=transmitting?7:2.4+Math.sin(time*4+intercom.index)*.8;intercom.antenna.rotation.z=.28+Math.sin(time*(transmitting?34:8)+intercom.index)*(transmitting?.16:.035);const crouched=keys.KeyC||keys.ControlLeft||keys.ControlRight;if(!molly.cameraView&&!crouched&&intercom.cooldown<=0&&molly.intercomCooldown<=0&&player.distanceTo(intercom.position)<3.1){intercom.cooldown=8;intercom.transmitTimer=.85;molly.intercomCooldown=2.5;intercom.lamp.material.emissive.setHex(0xff382e);playMollySound('intercom');mollyHearSound(intercom.position,1.15,'an intercom transmission');setTimeout(()=>intercom.lamp?.material?.emissive?.setHex(0x1b978c),850)}}
 if(!molly.cameraView&&molly.soundCooldown<=0&&!keys.KeyC&&!keys.ControlLeft&&!keys.ControlRight){const moving=keys.KeyW||keys.KeyS||keys.KeyA||keys.KeyD||keys.ArrowUp||keys.ArrowDown||keys.ArrowLeft||keys.ArrowRight,sprinting=keys.ShiftLeft||keys.ShiftRight;if(moving&&sprinting&&player.distanceTo(mollyEntity.position)<9){molly.soundCooldown=1.6;molly.soundStrength=1.25;mollyHearSound(player.clone(),1.25,'running footsteps')}}
 if(molly.grace<=0&&player.distanceTo(mollyEntity.position)<1.18)return failMolly();setMollyHud()
}
