const MOLLY_COMPUTER_POSITIONS=[[-12,0,10],[12,0,10],[-12,0,1],[12,0,1],[-12,0,-8],[12,0,-8]],MOLLY_PATROL_POINTS=[[0,0,14],[-8,0,9],[8,0,4],[-7,0,-4],[7,0,-9],[0,0,6]],MOLLY_DOOR_COMPUTERS=[2,4,6];
function newMollyRun(origin='floor2'){return{origin,boundary:22,phase:'patrol',timer:0,selectionTimer:7,patrolIndex:0,targetComputer:0,display:'00',hacked:[],overridden:[],levers:[],codesRead:false,hammerTaken:false,droneTaken:false,brokenWindow:false,finalUnlocked:false,finalControlLost:false,grace:5,soundCooldown:0,intercomCooldown:0,stepTimer:.4,dying:false,flare:null,cameraView:null,lastSound:null}}
function loadMolly(origin='floor2'){try{const value=JSON.parse(sessionStorage.getItem('hotel-molly-run')||'null');return value?{...newMollyRun(value.origin||origin),...value,origin:value.origin||origin,hacked:value.hacked||[],overridden:value.overridden||[],levers:value.levers||[],flare:null,cameraView:null,dying:false}:newMollyRun(origin)}catch{return newMollyRun(origin)}}
function saveMolly(){if(!molly)return;const saved={...molly,flare:null,cameraView:null};sessionStorage.setItem('hotel-molly-run',JSON.stringify(saved))}
function mollyComputerCode(number){return{2:'2408',4:'0417',6:'6620'}[number]||String(7300+number*17)}
function mollyComputerLabel(number){return String(number).padStart(2,'0')}
function mollySetDisplay(value){if(!mollyEntity)return;const display=mollyComputerLabel(Number(value)||0),canvas=mollyEntity.userData.screenCanvas,context=canvas.getContext('2d');context.clearRect(0,0,canvas.width,canvas.height);const gradient=context.createLinearGradient(0,0,0,canvas.height);gradient.addColorStop(0,'#071215');gradient.addColorStop(1,'#010405');context.fillStyle=gradient;context.fillRect(0,0,canvas.width,canvas.height);context.strokeStyle='rgba(115,230,245,.18)';context.lineWidth=2;for(let y=8;y<canvas.height;y+=8){context.beginPath();context.moveTo(0,y);context.lineTo(canvas.width,y);context.stroke()}context.font='700 82px monospace';context.textAlign='center';context.textBaseline='middle';context.shadowColor='#6feaff';context.shadowBlur=18;context.fillStyle='#c9fbff';context.fillText(display,canvas.width/2,canvas.height/2+4);mollyEntity.userData.screenTexture.needsUpdate=true;molly.display=display}
function makeMollyModel(admin=false){
 const entity=new THREE.Group();entity.name='Molly · blind computer monster';const uniform=mat(0x172229,.72),uniformEdge=mat(0x273943,.52),metal=mat(0x56656a,.24),rubber=mat(0x101719,.82),copper=mat(0xa45f32,.28,0x321409);
 const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.42,1.35,8,14),uniform);torso.position.y=1.55;torso.scale.set(.82,1.08,.66);entity.add(torso);const jacketPanel=new THREE.Mesh(new THREE.BoxGeometry(.52,1.35,.16),uniformEdge);jacketPanel.position.set(0,1.62,.39);entity.add(jacketPanel);for(const y of [1.25,1.65,2.05]){const seam=new THREE.Mesh(new THREE.BoxGeometry(.42,.025,.025),metal);seam.position.set(0,y,.49);entity.add(seam)}
 const neck=new THREE.Mesh(new THREE.CylinderGeometry(.18,.22,.36,10),metal);neck.position.y=2.47;entity.add(neck);const head=new THREE.Group();head.name='Molly monitor head';head.position.set(0,3.03,0);entity.add(head);const frame=new THREE.Mesh(new THREE.BoxGeometry(1.18,.82,.52),rubber);head.add(frame);for(const x of [-.5,.5])for(const y of [-.33,.33]){const bolt=new THREE.Mesh(new THREE.SphereGeometry(.035,7,5),metal);bolt.position.set(x,y,.29);head.add(bolt)}
 const screenCanvas=document.createElement('canvas');screenCanvas.width=256;screenCanvas.height=128;const screenTexture=new THREE.CanvasTexture(screenCanvas);screenTexture.colorSpace=THREE.SRGBColorSpace;const screenMaterial=new THREE.MeshStandardMaterial({map:screenTexture,emissiveMap:screenTexture,emissive:0x8befff,emissiveIntensity:2.4,roughness:.12,metalness:.05});const screen=new THREE.Mesh(new THREE.PlaneGeometry(.94,.59),screenMaterial);screen.name='Molly screen face';screen.position.z=.267;head.add(screen);const glow=new THREE.PointLight(0x68dcea,admin?28:38,6,1.8);glow.position.set(0,0,.48);head.add(glow);
 const arms=[];for(const side of [-1,1]){const shoulder=new THREE.Group();shoulder.position.set(side*.57,2.18,0);entity.add(shoulder);const upper=new THREE.Mesh(new THREE.CylinderGeometry(.075,.12,1.18,8),uniform);upper.position.y=-.53;upper.rotation.z=side*.08;shoulder.add(upper);const cuff=new THREE.Mesh(new THREE.CylinderGeometry(.1,.11,.22,8),metal);cuff.position.y=-1.08;shoulder.add(cuff);const hand=new THREE.Mesh(new THREE.CapsuleGeometry(.095,.18,5,8),mat(0x879195,.56));hand.position.set(0,-1.28,.02);shoulder.add(hand);arms.push({shoulder,upper,hand,side})}
 const legs=[];for(const side of [-1,1]){const leg=new THREE.Group();leg.position.set(side*.22,.88,0);entity.add(leg);const trouser=new THREE.Mesh(new THREE.CylinderGeometry(.095,.14,1.45,8),uniform);trouser.position.y=-.55;leg.add(trouser);const shoe=new THREE.Mesh(new THREE.BoxGeometry(.28,.2,.52),rubber);shoe.position.set(0,-1.3,.13);leg.add(shoe);legs.push({leg,side})}
 const wires=[];for(let index=0;index<16;index++){const side=index<8?-1:1,rank=index%8,root=new THREE.Group(),thick=index%4===0,wireMaterial=index%5===0?copper:mat(index%3?0x131a1d:0x202a2e,.72);root.position.set(side*(.22+rank*.055),3.27-(rank%3)*.055,-.18-(rank%2)*.08);entity.add(root);const length=thick?2.15:1.55+(rank%3)*.18,segments=thick?4:3;for(let segment=0;segment<segments;segment++){const pieceLength=length/segments,piece=new THREE.Mesh(new THREE.CylinderGeometry(thick?.047:.022,thick?.062:.032,pieceLength,6),wireMaterial);piece.position.set(side*(segment*.045),-(segment+.5)*pieceLength,.02*Math.sin(segment+index));piece.rotation.z=side*(.04+segment*.025);root.add(piece)}const connector=new THREE.Mesh(new THREE.CylinderGeometry(thick?.07:.045,thick?.07:.045,.13,7),index%5===0?copper:metal);connector.position.set(side*((segments-1)*.045),-length-.07,0);root.add(connector);wires.push({root,side,rank,weight:thick?1:.58,phase:index*.73,rest:side*(.05+rank*.012)})}
 entity.userData={...entity.userData,screenCanvas,screenTexture,screen,head,arms,legs,wires,torso,lastPosition:new THREE.Vector3(),velocity:new THREE.Vector3(),turnAmount:0};entity.traverse(child=>{if(child.isMesh){child.castShadow=true;child.receiveShadow=true}});if(!admin){mollyEntity=entity;mollySetDisplay(molly?.display||'00')}else{const fake={screenCanvas,screenTexture};const old=mollyEntity;mollyEntity=entity;const oldRun=molly;molly={display:'00'};mollySetDisplay('00');molly=oldRun;mollyEntity=old;entity.userData.adminMolly=fake}return entity
}
function playMollySound(kind='step'){try{funAudio||=new AudioContext();const context=funAudio,osc=context.createOscillator(),gain=context.createGain(),filter=context.createBiquadFilter(),frequencies={step:58,wire:620,type:940,intercom:1280,error:92,door:44},duration=kind==='wire'?.32:kind==='door'?.55:.16;osc.type=kind==='step'||kind==='door'?'sine':kind==='error'?'sawtooth':'square';osc.frequency.setValueAtTime(frequencies[kind]||440,context.currentTime);if(kind==='wire')osc.frequency.exponentialRampToValueAtTime(240,context.currentTime+duration);filter.type='lowpass';filter.frequency.value=kind==='type'?1800:900;gain.gain.setValueAtTime(kind==='door'?.17:.065,context.currentTime);gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+duration);osc.connect(filter).connect(gain).connect(context.destination);osc.start();osc.stop(context.currentTime+duration)}catch{}}
function startMollyFlare(style='casual',finish='resume-patrol'){if(!molly||molly.flare)return;molly.flare={style,finish,elapsed:0,duration:style==='casual'?1.05:style==='agitated'?1.6:style==='final'?2.15:1.75};document.body.classList.add('molly-flare');playMollySound('wire')}
function cancelMollyFlare(){if(!molly?.flare)return;molly.flare=null;document.body.classList.remove('molly-flare')}
function finishMollyFlare(){const finish=molly.flare?.finish;molly.flare=null;document.body.classList.remove('molly-flare');if(finish==='begin-hack'){molly.phase='hack';molly.timer=3.5;document.body.classList.add('molly-hacking')}else if(finish==='resume-search'){molly.phase='search';molly.timer=6}else if(finish==='final-listen'){molly.phase='final-listen';molly.timer=3.5;molly.finalControlLost=true;mollySetDisplay('00');saveMolly()}else{molly.phase='patrol';molly.selectionTimer=5+Math.random()*5}}
function animateMollyRig(dt,time,moving=false,speed=0){if(!mollyEntity)return;const rig=mollyEntity.userData,flare=molly?.flare,p=flare?THREE.MathUtils.clamp(flare.elapsed/flare.duration,0,1):0,strength=!flare?0:p<.22?p/.22*.22:p<.58?.22+(p-.22)/.36*.78:p<.73?1:Math.max(0,(1-p)/.27),styleStrength=flare?.style==='casual'?.62:flare?.style==='agitated'?1.15:flare?.style==='final'?.9:1,fan=strength*styleStrength,walk=moving?Math.sin(time*(7+speed)):0;rig.legs.forEach(({leg,side})=>leg.rotation.x=walk*side*.42);rig.arms.forEach(({shoulder,side},index)=>{shoulder.rotation.x=walk*-side*.18;shoulder.rotation.z=side*.08;if(flare&&index===1){shoulder.rotation.z=-1.48*fan;shoulder.rotation.x=-.58*fan;shoulder.rotation.y=-.35*fan}else if(molly?.phase==='hack'||molly?.phase==='final-input'){shoulder.rotation.x=-1.08+Math.sin(time*11+index)*.16;shoulder.rotation.z=side*.28}});rig.head.rotation.z=THREE.MathUtils.lerp(rig.head.rotation.z,molly?.phase==='listening'||molly?.phase==='search-wait'?.18*Math.sin(time*.8):0,Math.min(1,dt*5));rig.wires.forEach(wire=>{const lag=wire.weight,restSway=Math.sin(time*(1.25+wire.rank*.04)+wire.phase)*(.025+(1-lag)*.035),motionSway=moving?Math.sin(time*7+wire.phase)*(.05+(1-lag)*.07):0,targetZ=wire.rest+restSway+motionSway+wire.side*fan*(1.98+(1-lag)*.22),targetX=-fan*(.28+(1-lag)*.18)-Math.min(.22,speed*.025);wire.root.rotation.z=THREE.MathUtils.lerp(wire.root.rotation.z,targetZ,Math.min(1,dt*(lag?8:11)));wire.root.rotation.x=THREE.MathUtils.lerp(wire.root.rotation.x,targetX,Math.min(1,dt*(4+lag*4)))});if(flare){flare.elapsed+=dt;if(flare.elapsed>=flare.duration)finishMollyFlare()}}
function mollyPlayerPosition(){return molly?.cameraView?.playerPosition?new THREE.Vector3(...molly.cameraView.playerPosition):camera.position}
function moveMollyToward(target,speed,dt){if(!mollyEntity)return false;const destination=new THREE.Vector3(target[0],0,target[2]),direction=destination.clone().sub(mollyEntity.position);direction.y=0;const distance=direction.length();if(distance<.18){animateMollyRig(dt,performance.now()*.001,false,0);return true}direction.normalize();mollyEntity.position.addScaledVector(direction,Math.min(distance,speed*dt));const desired=Math.atan2(direction.x,direction.z),delta=Math.atan2(Math.sin(desired-mollyEntity.rotation.y),Math.cos(desired-mollyEntity.rotation.y));mollyEntity.rotation.y+=delta*Math.min(1,dt*6);mollyEntity.userData.turnAmount=delta;molly.stepTimer-=dt;if(molly.stepTimer<=0){playMollySound('step');molly.stepTimer=speed>4?.22:.42}animateMollyRig(dt,performance.now()*.001,true,speed);return distance<.28}
function mollyHearSound(position,strength=1,source='sound'){if(!molly||molly.dying||molly.finalControlLost&&source==='computer')return;cancelMollyFlare();document.body.classList.remove('molly-hacking');molly.lastSound=[position.x??position[0],0,position.z??position[2]];molly.soundStrength=strength;molly.phase='listening';molly.timer=strength>1?1.15:.7;molly.targetComputer=0;mollySetDisplay('00');document.body.classList.add('molly-listening');if(strength>1)startMollyFlare('focused','resume-search');document.querySelector('#prompt').textContent=`MOLLY HEARD ${source.toUpperCase()} · SHE IS GOING TO THAT LOCATION`;saveMolly()}
function mollyDoorForComputer(number){return MOLLY_DOOR_COMPUTERS.indexOf(number)}
function setMollyDoor(index,open){const door=mollyDoors[index];if(!door)return;door.open=open;door.mesh.position.y=open?4.65:1.7;const existing=solidColliders.find(collider=>collider.mesh===door.mesh);if(open&&existing)solidColliders=solidColliders.filter(collider=>collider!==existing);if(!open&&!existing)solidColliders.push({mesh:door.mesh,halfX:2.9,halfZ:.22,bottom:0,top:3.4});door.indicator.material.emissive.setHex(open?0x1ca86a:0xb71e24);door.indicator.material.emissiveIntensity=3}
function mollyComputerStatus(number,status){const computer=mollyComputers.find(entry=>entry.number===number);if(!computer)return;computer.status=status;computer.indicator.material.color.setHex(status==='override'?0x42db91:status==='hacked'?0xd12b31:0x4ccfe2);computer.indicator.material.emissive.setHex(status==='override'?0x1aa462:status==='hacked'?0x8b1118:0x176779);computer.indicator.material.emissiveIntensity=3}
function hackMollyComputer(number){if(molly.overridden.includes(number))return;const index=mollyDoorForComputer(number);if(!molly.hacked.includes(number))molly.hacked.push(number);mollyComputerStatus(number,'hacked');if(index>=0&&!molly.overridden.includes(number))setMollyDoor(index,false);playMollySound('door');document.querySelector('#prompt').textContent=`COMPUTER ${mollyComputerLabel(number)} HACKED · LINKED SHUTTER CLOSED`;saveMolly()}
function openMollyOverride(number){if(!molly.codesRead)return document.querySelector('#prompt').textContent='THE TERMINAL REQUESTS A CODE · USE THE CLATTERING CODE MACHINE FIRST';if(molly.overridden.includes(number))return document.querySelector('#prompt').textContent=`COMPUTER ${mollyComputerLabel(number)} OVERRIDE HOLDS · MOLLY CANNOT UNDO IT`;controls.unlock();base('ELECTRICAL SECTION',`COMPUTER ${mollyComputerLabel(number)} OVERRIDE`,'Enter this terminal’s four-digit unlock code. The computer number on Molly’s face is not the code.');const input=document.createElement('input');input.maxLength=4;input.inputMode='numeric';input.placeholder='_ _ _ _';const button=document.createElement('button');button.textContent='OVERRIDE LINKED SHUTTER';button.onclick=()=>{if(input.value.trim()!==mollyComputerCode(number)){feedback.textContent='ACCESS DENIED · The terminal alarm gives Molly this exact location.';playMollySound('error');mollyHearSound(mollyComputers.find(entry=>entry.number===number).mesh.position,1.35,'terminal alarm');return}molly.overridden.push(number);molly.hacked=molly.hacked.filter(value=>value!==number);mollyComputerStatus(number,'override');const index=mollyDoorForComputer(number);if(index>=0)setMollyDoor(index,true);saveMolly();dlg.close();pickupTone();document.querySelector('#prompt').textContent=`COMPUTER ${mollyComputerLabel(number)} OVERRIDDEN · LINKED SHUTTER PERMANENTLY OPEN`;molly.lastSound=[...MOLLY_COMPUTER_POSITIONS[number-1]];molly.soundStrength=1.2;molly.phase='listening';mollySetDisplay('00');cancelMollyFlare();startMollyFlare('agitated','resume-search')};body.append(input,button)}
function triggerMollyCodeMachine(){molly.codesRead=true;saveMolly();playPurgeCrash();mollyHearSound(new THREE.Vector3(0,0,18),1.4,'the code machine');objective.textContent=`Codes acquired: C02 ${mollyComputerCode(2)} · C04 ${mollyComputerCode(4)} · C06 ${mollyComputerCode(6)}. Override each linked shutter and flick its lever.`;message('ELECTRICAL UNLOCK CODES',`COMPUTER 02 · ${mollyComputerCode(2)}   //   COMPUTER 04 · ${mollyComputerCode(4)}   //   COMPUTER 06 · ${mollyComputerCode(6)}. Molly heard the machine, not your new position.`)}
function mollyDroneDistraction(){if(!molly||hotelSideScene!=='molly-electrical')return false;const player=mollyPlayerPosition(),target=[...MOLLY_PATROL_POINTS].sort((a,b)=>new THREE.Vector3(...b).distanceTo(player)-new THREE.Vector3(...a).distanceTo(player))[0];playMollySound('intercom');mollyHearSound(new THREE.Vector3(...target),1,'the drone beep');document.querySelector('#prompt').textContent='DRONE BEEP SENT · MOLLY INVESTIGATES THE BEEP, NOT THE CONTROLLER';return true}
function startMollyCameraFeed(){if(molly.cameraView)return;molly.cameraView={playerPosition:[camera.position.x,camera.position.y,camera.position.z],playerQuaternion:[camera.quaternion.x,camera.quaternion.y,camera.quaternion.z,camera.quaternion.w],timer:6};controls.unlock();document.querySelector('#prompt').textContent='SECURITY FEED · WATCH MOLLY’S SCREEN AND HANDS · RETURNING IN 6 SECONDS'}
function endMollyCameraFeed(){if(!molly?.cameraView)return;const view=molly.cameraView;molly.cameraView=null;camera.position.set(...view.playerPosition);camera.quaternion.set(...view.playerQuaternion);if(storySelect.hidden&&!dlg.open)controls.lock();document.querySelector('#prompt').textContent='CAMERA FEED CLOSED · YOUR POSITION DID NOT MOVE'}
function pullMollyLever(index){if(molly.levers.includes(index))return;const required=MOLLY_DOOR_COMPUTERS[index];if(!molly.overridden.includes(required))return document.querySelector('#prompt').textContent=`LEVER ${index+1} HAS NO POWER · OVERRIDE COMPUTER ${mollyComputerLabel(required)}`;molly.levers.push(index);const lever=mollyLevers[index];if(lever)lever.rotation.z=-.72;pickupTone();playMollySound('door');if(molly.levers.length===3){molly.finalUnlocked=true;cancelMollyFlare();document.body.classList.remove('molly-hacking','molly-listening');const blocker=roomGroup.getObjectByName('Molly final exit blocker'),exitDoor=roomGroup.getObjectByName('Molly final exit door');blocker?.removeFromParent();solidColliders=solidColliders.filter(collider=>collider.mesh!==blocker);if(exitDoor)exitDoor.position.y=6;objective.textContent='All three levers hold. Reach the released final exit while Molly tests a terminal that no longer answers her.';document.querySelector('#prompt').textContent='FINAL LEVER ACTIVE · MOLLY HAS LOST CONTROL OF THE EXIT';molly.phase='final-travel';molly.lastSound=[...MOLLY_COMPUTER_POSITIONS[5]];mollySetDisplay('00');horrorStinger()}else document.querySelector('#prompt').textContent=`LEVER ${index+1} ACTIVE · ${3-molly.levers.length} REMAIN`;saveMolly();setMollyHud()}
function handleMolly(part){if(!molly||molly.dying)return;if(part==='code-machine')return triggerMollyCodeMachine();if(part.startsWith('computer:'))return openMollyOverride(Number(part.slice(9)));if(part.startsWith('lever:'))return pullMollyLever(Number(part.slice(6)));if(part==='hammer'){if(molly.hammerTaken)return;molly.hammerTaken=true;hotelRunItems.add('electrical-hammer');saveHotelRun();saveMolly();updateInventory();playFirstPersonAction('pickup','electrical-hammer',.7);return document.querySelector('#prompt').textContent='INSULATED HAMMER ACQUIRED · BREAK THE MARKED WINDOW'}if(part==='drone'){if(molly.droneTaken)return;molly.droneTaken=true;hotelRunItems.add('drone-controller');saveHotelRun();saveMolly();updateInventory();playFirstPersonAction('pickup','drone-controller',.7);return document.querySelector('#prompt').textContent='MAINTENANCE DRONE ACQUIRED · SELECT IT AND PRESS Q TO DISTRACT MOLLY'}if(part==='window'){if(molly.brokenWindow)return;if(!molly.hammerTaken)return document.querySelector('#prompt').textContent='THE REINFORCED WINDOW NEEDS THE INSULATED HAMMER';molly.brokenWindow=true;playFirstPersonAction('use','electrical-hammer',.62);playPurgeCrash();mollyHearSound(new THREE.Vector3(-18,0,4),1.6,'the breaking window');const pane=roomGroup.getObjectByName('Molly breakable safety window');if(pane)pane.visible=false;saveMolly();return document.querySelector('#prompt').textContent='WINDOW BROKEN · MOLLY COMMITS TO THE CRASH LOCATION'}if(part==='camera')return startMollyCameraFeed();if(part==='exit'){if(!molly.finalUnlocked)return document.querySelector('#prompt').textContent=`FINAL EXIT LOCKED · ${3-molly.levers.length} LEVERS REMAIN`;return leaveMollySection()}}
function makeMollyTerminal(number,position){const side=position[0]<0?-1:1,mesh=box(`Molly computer ${number}`,[position[0],1.15,position[2]],[2.4,2.3,1.35],0x26373d,true);mesh.rotation.y=side<0?Math.PI/2:-Math.PI/2;const indicator=box(`Molly computer ${number} indicator`,[position[0]-side*.72,2,position[2]],[.08,.58,.9],0x4ccfe2,false);indicator.material.emissive.setHex(0x176779);indicator.material.emissiveIntensity=3;interactive([position[0]-side*1.05,1.4,position[2]],[1.7,2.8,2.5],8,'molly',`computer:${number}`);objectLabel(`COMPUTER ${mollyComputerLabel(number)} · E OVERRIDE`,[position[0]-side*1.25,3.05,position[2]],.24);const computer={number,mesh,indicator,status:'idle'};mollyComputers.push(computer);if(molly.overridden.includes(number))mollyComputerStatus(number,'override');else if(molly.hacked.includes(number))mollyComputerStatus(number,'hacked');return computer}
function makeMollyIntercom(position,index){const panel=box(`active intercom ${index}`,[position[0],2.25,position[2]],[.28,.85,.75],0x39474b,false),lamp=sphere(`intercom indicator ${index}`,[position[0]-(position[0]>0?.18:-.18),2.45,position[2]],.075,0x3ee4d3);lamp.material.emissive.setHex(0x1b978c);lamp.material.emissiveIntensity=3;const antenna=new THREE.Mesh(new THREE.CylinderGeometry(.025,.04,.75,6),mat(0x69787d,.25));antenna.position.set(position[0],3,position[2]);antenna.rotation.z=position[0]>0?.35:-.35;roomGroup.add(antenna);mollyIntercoms.push({position:new THREE.Vector3(...position),panel,lamp,antenna,cooldown:0,transmitTimer:0,index})}
function buildMollyElectrical(){
 resetHotelSideScene();activeStory='hotel';room=8;hotelSideScene='molly-electrical';molly.boundary=22;scene.background.setHex(0x071215);scene.fog.color.setHex(0x09161a);scene.fog.density=.018;box('electrical section floor',[0,-.15,0],[38,.3,46],0x233238,false);box('electrical section ceiling',[0,6,0],[38,.25,46],0x10191c,false);box('electrical west wall',[-19,3,0],[.35,6,46],0x28383d,true);box('electrical east wall',[19,3,0],[.35,6,46],0x28383d,true);box('electrical entrance wall',[0,3,23],[38,6,.35],0x28383d,true);for(const [x,width] of [[-12,14],[12,14]])box('electrical final wall',[x,3,-23],[width,6,.35],0x28383d,true);for(const [x,width] of [[-16.5,5],[-5.5,5],[5.5,5],[16.5,5]])box('lever bay front wall',[x,3,-14.5],[width,6,.35],0x314249,true);for(const x of [-5.5,5.5])box('lever bay divider',[x,3,-18.75],[.3,6,8.5],0x314249,true);
 for(let z=18;z>-13;z-=8){for(const side of [-1,1]){box('electrical cabinet',[side*16.8,1.5,z],[2.7,3,4.5],0x26343a,true);for(let y=.6;y<2.7;y+=.55){const led=sphere('cabinet status lamp',[side*15.4,y,z+(y%1-.5)*2],.045,y>1.5?0x49d1cf:0xd29744);led.material.emissive.setHex(y>1.5?0x167b7a:0x7b481b);led.material.emissiveIntensity=3}}light([0,4.9,z],0x78dbe3,2.3,8)}
 const doorCenters=[-11,0,11];doorCenters.forEach((x,index)=>{const mesh=box(`Molly linked shutter ${index+1}`,[x,1.7,-14.5],[5.8,3.4,.44],0x4c5c61,false),indicator=box(`Molly shutter ${index+1} indicator`,[x,4,-14.2],[1,.28,.18],0xb71e24,false);mollyDoors.push({mesh,indicator,index,open:false});setMollyDoor(index,molly.overridden.includes(MOLLY_DOOR_COMPUTERS[index]))});
 MOLLY_COMPUTER_POSITIONS.forEach((position,index)=>makeMollyTerminal(index+1,position));doorCenters.forEach((x,index)=>{const housing=box(`lever ${index+1} housing`,[x,1.4,-19.2],[1.4,2.2,.8],0x3b4a4e,false),lever=new THREE.Mesh(new THREE.BoxGeometry(.18,1.1,.2),mat(0xc44232,.3,0x5b100c));lever.position.set(x,1.6,-18.72);lever.rotation.z=molly.levers.includes(index)?-.72:.5;roomGroup.add(lever);mollyLevers.push(lever);interactive([x,1.5,-18.5],[2.2,2.8,1.8],8,'molly',`lever:${index}`);objectLabel(`LEVER ${index+1} · COMPUTER ${mollyComputerLabel(MOLLY_DOOR_COMPUTERS[index])}`,[x,3.1,-18.5],.23);housing.material.emissive.setHex(molly.levers.includes(index)?0x174f36:0x2b0c0d)});
 box('Molly final exit door',[0,molly.finalUnlocked?6:2,-22.78],[6,4,.25],0x42585e,false);const exitBlocker=box('Molly final exit blocker',[0,1.75,-22.45],[6,3.5,.28],0x000000,true);exitBlocker.visible=false;if(molly.finalUnlocked){exitBlocker.removeFromParent();solidColliders=solidColliders.filter(collider=>collider.mesh!==exitBlocker)}interactive([0,1.7,-21.7],[6.5,3.5,1.5],8,'molly','exit');objectLabel(molly.finalUnlocked?'FINAL EXIT · E LEAVE':'FINAL EXIT · THREE LEVERS REQUIRED',[0,4.2,-21.4],.28);
 box('code machine',[0,1.2,18],[3.2,2.4,1.2],0x34464b,true);interactive([0,1.3,17.2],[3.8,2.7,1.6],8,'molly','code-machine');objectLabel(molly.codesRead?'CODES PRINTED · E CLATTER AGAIN':'CODE MACHINE · E PRINT CODES',[0,3.15,17],.3);if(!molly.hammerTaken){box('insulated hammer',[-5,.72,17],[1.5,.16,.32],0xb36b3d,false);interactive([-5,.9,17],[2.2,1.8,1.5],8,'molly','hammer');objectLabel('INSULATED HAMMER · E TAKE',[-5,2.05,17],.24)}if(!molly.droneTaken){box('maintenance drone controller',[5,.9,17],[1.1,.35,.75],0x35545b,false);interactive([5,1,17],[2.1,1.8,1.8],8,'molly','drone');objectLabel('DRONE CONTROLLER · E TAKE',[5,2.1,17],.23)}
 const windowPane=box('Molly breakable safety window',[-18.78,2.4,4],[.12,3.8,5],0x416d78,false);windowPane.material.transparent=true;windowPane.material.opacity=molly.brokenWindow?0:.58;interactive([-18.2,2.1,4],[1.2,4.2,5.2],8,'molly','window');objectLabel(molly.brokenWindow?'BROKEN WINDOW':'MARKED WINDOW · HAMMER',[-17.6,4.65,4],.22);box('security camera controller',[0,1.4,13],[2.1,1.9,1],0x26373d,true);interactive([0,1.5,12.35],[2.6,2.2,1.4],8,'molly','camera');objectLabel('SECURITY CAMERA · E WATCH MOLLY',[0,3,12.1],.25);
 makeMollyIntercom([-18.72,0,11],0);makeMollyIntercom([18.72,0,5],1);makeMollyIntercom([-18.72,0,-6],2);makeMollyIntercom([18.72,0,-11],3);mollyEntity=makeMollyModel();mollyEntity.position.set(0,0,2);roomGroup.add(mollyEntity);camera.position.set(0,1.7,20);camera.lookAt(0,1.7,5);chapter.textContent='HOTEL NOCTURNE · ELECTRICAL SECTION';title.textContent='Molly · The Blind Computer';description.textContent='A tall maintenance figure patrols by sound. Her screen reads 00 until she deliberately selects and walks to a numbered computer.';objective.textContent=molly.codesRead?`Codes: C02 ${mollyComputerCode(2)} · C04 ${mollyComputerCode(4)} · C06 ${mollyComputerCode(6)}. Override the shutters and activate all three levers.`:'Use the loud code machine, then leave its location quietly. Crouch beneath active intercom antennas.';document.querySelector('#prompt').textContent='MOLLY HEARS LOCATIONS, NOT INVISIBLE TRAILS · CROUCH UNDER INTERCOMS';setRoomNumber('ELECTRICAL');setMollyHud();saveMolly();setTimeout(()=>controls.lock(),100)
}
function startMolly(fresh=false,origin='floor2'){if(floorTwo)saveFloorTwo();floorFive=null;floorOne=null;floorTwo=null;collector=null;clockmaker=null;drowned=null;pursuer=null;cancelNoise();cancelHotelNoiseArc();molly=fresh?newMollyRun(origin):loadMolly(origin);buildMollyElectrical();if(fresh)message('MOLLY · ELECTRICAL SECTION','Watch her screen. 00 means no computer is selected; a number identifies the terminal she will physically visit and hack.')}
function setMollyHud(){if(!molly)return;const phaseNames={patrol:'PATROLLING · 00','patrol-wait':'LISTENING · 00',select:`SELECTED · ${molly.display}`,'computer-travel':`APPROACHING · ${molly.display}`,hack:`HACKING · ${molly.display}`,listening:'SOUND DETECTED · 00',search:'INVESTIGATING · 00','search-wait':'SEARCHING · 00','final-travel':'FINAL CONTROL LOST','final-input':'ACCESS DENIED · 00','final-listen':'LISTENING · 00'},copy=molly.phase==='hack'?`Molly is physically operating Computer ${molly.display}. Its linked shutter closes only when her input completes.`:molly.phase==='computer-travel'?`Molly chose Computer ${molly.display}. The number remains trustworthy throughout her approach.`:molly.finalUnlocked?'The exit controls no longer answer Molly. She remains dangerous until you leave.':'Crouch beneath antennas. Loud actions send Molly to the place where the sound occurred.';setBossEncounterHud(true,'MOLLY',phaseNames[molly.phase]||'LISTENING · 00',copy,molly.levers.length/3)}
function failMolly(){if(adminPreventDeath('MOLLY COULD NOT CATCH YOU'))return;if(!molly||molly.dying)return;molly.dying=true;saveMolly();controls.unlock();horrorStinger();const blackout=document.querySelector('#blackout');blackout.querySelector('span').textContent='MOLLY FOUND THE SOURCE';blackout.classList.add('show');setTimeout(()=>{molly.dying=false;molly.phase='patrol';molly.grace=4;molly.display='00';molly.targetComputer=0;buildMollyElectrical();blackout.classList.remove('show');blackout.querySelector('span').textContent='You wake inside the cabin.'},950)}
function leaveMollySection(){localStorage.setItem('hotel-molly-complete','true');sessionStorage.removeItem('hotel-molly-run');molly=null;setBossEncounterHud(false);floorTwo=loadFloorTwo()||newFloorTwoRun();floorTwo.phase=19;buildFloorTwoSafe();message('MOLLY · EXIT OVERRIDE HELD','The final system ignored Molly’s last input. Behind the maintenance door, her cables settle and her screen returns to 00.')}
function updateMolly(dt,time){
 if(!molly||hotelSideScene!=='molly-electrical'||molly.dying||dlg.open)return;molly.grace=Math.max(0,molly.grace-dt);molly.soundCooldown=Math.max(0,molly.soundCooldown-dt);molly.intercomCooldown=Math.max(0,molly.intercomCooldown-dt);const player=mollyPlayerPosition();
 if(molly.cameraView){molly.cameraView.timer-=dt;camera.position.set(0,8.5,16);camera.lookAt(mollyEntity.position.x,2.2,mollyEntity.position.z);if(molly.cameraView.timer<=0)endMollyCameraFeed()}
 if(molly.flare){animateMollyRig(dt,time,false,0);setMollyHud();return}
 if(molly.phase==='patrol'){molly.selectionTimer-=dt;const target=MOLLY_PATROL_POINTS[molly.patrolIndex%MOLLY_PATROL_POINTS.length];if(moveMollyToward(target,1.45,dt)){molly.phase='patrol-wait';molly.timer=1.1+Math.random()*1.2}if(molly.selectionTimer<=0){const candidates=MOLLY_DOOR_COMPUTERS.filter(number=>!molly.overridden.includes(number));if(candidates.length){molly.targetComputer=candidates[Math.floor(Math.random()*candidates.length)];mollySetDisplay(molly.targetComputer);molly.phase='select';molly.timer=.9;document.querySelector('#prompt').textContent=`MOLLY’S SCREEN CHANGED TO ${molly.display} · SHE CHOSE COMPUTER ${molly.display}`;}else molly.selectionTimer=8}
 }else if(molly.phase==='patrol-wait'){animateMollyRig(dt,time,false,0);molly.timer-=dt;mollyEntity.rotation.y+=Math.sin(time*.9)*dt*.2;if(molly.timer<=0){if(Math.random()<.3)startMollyFlare('casual','resume-patrol');else{molly.patrolIndex=(molly.patrolIndex+1)%MOLLY_PATROL_POINTS.length;molly.phase='patrol'}}
 }else if(molly.phase==='select'){animateMollyRig(dt,time,false,0);molly.timer-=dt;const target=MOLLY_COMPUTER_POSITIONS[molly.targetComputer-1],direction=new THREE.Vector3(...target).sub(mollyEntity.position);mollyEntity.rotation.y+=Math.atan2(Math.sin(Math.atan2(direction.x,direction.z)-mollyEntity.rotation.y),Math.cos(Math.atan2(direction.x,direction.z)-mollyEntity.rotation.y))*Math.min(1,dt*5);if(molly.timer<=0)molly.phase='computer-travel'
 }else if(molly.phase==='computer-travel'){const target=MOLLY_COMPUTER_POSITIONS[molly.targetComputer-1];if(moveMollyToward(target,2.05,dt)){startMollyFlare('focused','begin-hack');document.querySelector('#prompt').textContent=`MOLLY REACHED COMPUTER ${molly.display} · WATCH HER HAND LIFT THE WIRES`}}
 else if(molly.phase==='hack'){animateMollyRig(dt,time,false,0);molly.timer-=dt;if(Math.floor(molly.timer*6)%2===0&&molly.soundCooldown<=0){playMollySound('type');molly.soundCooldown=.22}if(molly.timer<=0){document.body.classList.remove('molly-hacking');hackMollyComputer(molly.targetComputer);molly.targetComputer=0;mollySetDisplay('00');molly.phase='patrol';molly.selectionTimer=5+Math.random()*5;molly.patrolIndex=(molly.patrolIndex+1)%MOLLY_PATROL_POINTS.length}}
 else if(molly.phase==='listening'){animateMollyRig(dt,time,false,0);molly.timer-=dt;if(molly.lastSound){const target=new THREE.Vector3(...molly.lastSound),direction=target.sub(mollyEntity.position);mollyEntity.rotation.y+=Math.atan2(Math.sin(Math.atan2(direction.x,direction.z)-mollyEntity.rotation.y),Math.cos(Math.atan2(direction.x,direction.z)-mollyEntity.rotation.y))*Math.min(1,dt*7)}if(molly.timer<=0){document.body.classList.remove('molly-listening');molly.phase='search';molly.timer=6}}
 else if(molly.phase==='search'){if(moveMollyToward(molly.lastSound||[0,0,0],molly.soundStrength>1?4.7:2.75,dt)){molly.phase='search-wait';molly.timer=2.4;document.querySelector('#prompt').textContent='MOLLY REACHED THE REPORTED LOCATION · SHE IS LISTENING THERE'}}
 else if(molly.phase==='search-wait'){animateMollyRig(dt,time,false,0);molly.timer-=dt;mollyEntity.rotation.y+=Math.sin(time*1.6)*dt*.48;if(molly.timer<=0){molly.phase='patrol';molly.selectionTimer=4+Math.random()*5;molly.patrolIndex=(molly.patrolIndex+1)%MOLLY_PATROL_POINTS.length}}
 else if(molly.phase==='final-travel'){if(moveMollyToward(MOLLY_COMPUTER_POSITIONS[5],1.8,dt)){molly.phase='final-input';molly.timer=2.6;document.querySelector('#prompt').textContent='MOLLY TRIES COMPUTER 06 · THE FINAL SYSTEM DOES NOT ANSWER'}}
 else if(molly.phase==='final-input'){animateMollyRig(dt,time,false,0);molly.timer-=dt;if(molly.timer<=0){playMollySound('error');startMollyFlare('final','final-listen')}}
 else if(molly.phase==='final-listen'){animateMollyRig(dt,time,false,0);molly.timer-=dt;if(molly.timer<=0){molly.phase='patrol';molly.selectionTimer=20}}
 for(const intercom of mollyIntercoms){intercom.cooldown=Math.max(0,intercom.cooldown-dt);intercom.transmitTimer=Math.max(0,intercom.transmitTimer-dt);const transmitting=intercom.transmitTimer>0;intercom.antenna.rotation.z=(intercom.position.x>0?.35:-.35)+Math.sin(time*(transmitting?34:8)+intercom.index)*(transmitting?.16:.035);const crouched=keys.KeyC||keys.ControlLeft||keys.ControlRight;if(!molly.cameraView&&!crouched&&intercom.cooldown<=0&&molly.intercomCooldown<=0&&player.distanceTo(intercom.position)<3.1){intercom.cooldown=8;intercom.transmitTimer=.85;molly.intercomCooldown=2.5;intercom.lamp.material.emissive.setHex(0xff382e);playMollySound('intercom');mollyHearSound(intercom.position,1.15,'an intercom transmission');setTimeout(()=>intercom.lamp?.material?.emissive?.setHex(0x1b978c),850)}}
 if(!molly.cameraView&&molly.soundCooldown<=0&&!keys.KeyC&&!keys.ControlLeft&&!keys.ControlRight){const moving=keys.KeyW||keys.KeyS||keys.KeyA||keys.KeyD||keys.ArrowUp||keys.ArrowDown||keys.ArrowLeft||keys.ArrowRight,sprinting=keys.ShiftLeft||keys.ShiftRight;if(moving&&sprinting&&player.distanceTo(mollyEntity.position)<9){molly.soundCooldown=1.6;molly.soundStrength=1.25;mollyHearSound(player.clone(),1.25,'running footsteps')}}
 if(molly.grace<=0&&player.distanceTo(mollyEntity.position)<1.18)return failMolly();setMollyHud()
}
