function doll(pos,s=1){const d=new THREE.Group();d.position.set(...pos);d.scale.setScalar(s);const body=new THREE.Mesh(new THREE.BoxGeometry(.5,.7,.3),mat(0x544943));body.position.y=.45;d.add(body);const head=new THREE.Group();head.name='head';head.position.y=1.05;d.add(head);sphere('face',[0,0,0],.3,0xaaa08a,head);[-.11,.11].forEach(x=>{sphere('eye',[x,.04,-.27],.055,0xd8cfb9,head);sphere('pupil',[x,.04,-.322],.025,0x090908,head)});roomGroup.add(d);d.userData.origin=d.position.clone();dolls.push(d)}
function makeGiantSpider(){const spider=new THREE.Group(),hide=mat(0x171512,.92),legMat=mat(0x211d18,.88),legs=[];const abdomen=new THREE.Mesh(new THREE.SphereGeometry(1.05,22,15),hide);abdomen.scale.set(1.05,.72,1.35);abdomen.position.set(0,1.35,-.55);abdomen.castShadow=true;spider.add(abdomen);const thorax=new THREE.Mesh(new THREE.SphereGeometry(.78,20,14),hide);thorax.scale.set(1,.78,1.05);thorax.position.set(0,1.35,.72);thorax.castShadow=true;spider.add(thorax);for(const side of [-1,1])for(let row=0;row<4;row++){const leg=new THREE.Group(),front=(row-1.5)*.48;leg.position.set(side*.45,1.35,front);const upper=new THREE.Mesh(new THREE.CylinderGeometry(.1,.16,1.75,8),legMat);upper.position.x=side*.72;upper.rotation.z=side*-1.05;const lower=new THREE.Mesh(new THREE.CylinderGeometry(.07,.12,1.85,8),legMat);lower.position.set(side*1.65,-.48,0);lower.rotation.z=side*-.62;const claw=new THREE.Mesh(new THREE.ConeGeometry(.08,.45,7),legMat);claw.position.set(side*2.25,-1.12,.02);claw.rotation.z=side*-.85;upper.castShadow=lower.castShadow=claw.castShadow=true;leg.add(upper,lower,claw);leg.userData={side,row,baseZ:front};spider.add(leg);legs.push(leg)}const head=new THREE.Mesh(new THREE.SphereGeometry(.58,20,14),mat(0x1b1815,.82));head.position.set(0,1.42,1.42);spider.add(head);for(const y of [1.48,1.64])for(const x of [-.29,-.1,.1,.29]){const eye=sphere('spider eye',[x,y,1.92],x*x>.03?.085:.065,0xb91d12,spider);eye.material.emissive.setHex(0x7b0905);eye.material.emissiveIntensity=4}for(const side of [-1,1]){const fang=new THREE.Mesh(new THREE.ConeGeometry(.11,.55,8),mat(0xd1c5a3,.5));fang.position.set(side*.2,1.1,1.85);fang.rotation.x=Math.PI;spider.add(fang)}spider.userData.legs=legs;return spider}
function buildForest(){if(roomGroup)scene.remove(roomGroup);roomGroup=new THREE.Group();scene.add(roomGroup);interactables=[];dolls=[];solidColliders=[];const ground=box('forest floor',[0,-.2,-8],[40,.4,45],0x10140e);for(let i=0;i<70;i++){const x=(Math.random()-.5)*35,z=-Math.random()*38+7;if(Math.abs(x)<3&&z>-22)continue;const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.18+.2*Math.random(),.3+.25*Math.random(),5+Math.random()*5,7),mat(0x251b12));trunk.position.set(x,2.5,z);roomGroup.add(trunk);const crown=new THREE.Mesh(new THREE.ConeGeometry(1.2+Math.random(),4+Math.random()*2,7),mat(0x10170f));crown.position.set(x,6,z);roomGroup.add(crown)}box('cabin silhouette',[0,1.5,-25],[8,3,6],0x120d09);const roof=new THREE.Mesh(new THREE.ConeGeometry(6,2.7,4),mat(0x0b0907));roof.rotation.y=Math.PI/4;roof.position.set(0,4,-25);roomGroup.add(roof);light([0,3,-21],0xb27635,8,12);camera.position.set(0,1.7,5.5);camera.lookAt(0,1.5,-25)}
const jailbreakRooms=[
 ['ACT I','Cell 17','Beyond the bars, a guard patrols the main security room. The cell bars protect you from his searchlight.','Search the safe cell and open the side-wall security vent. The guard can only catch you outside the cage.'],
 ['ACT II','The Broken Cellblock','Holes split the floor and several abandoned cells stand open. The north gate uses a physical key.','Explore the open cells, dig through the loose floor, open the keypad evidence room, and recover the north-gate key.'],
 ['ACT III','Security Control','Camera feeds cover every exit. Four breaker switches control the lockdown.','Disable the cameras in the correct order.'],
 ['ACT IV','The Prison Yard','Searchlights rake the concrete. The outer wall is crowned with razor wire.','Build an escape rope and climb the marked wall.'],
 ['ACT V','The Storm Drain','A concrete tunnel runs beneath the outer wall. A locked floodgate blocks the channel.','Find the cutting tool and open the floodgate.'],
 ['ACT VI','The Boiler Works','Steam hides the service exit. Three pressure wheels feed the release manifold.','Balance the boiler pressure without triggering the alarm.'],
 ['ACT VII','The Transport Garage','Prison vans wait behind a motorized shutter. One maintenance truck still has power.','Hot-wire the truck and open the garage shutter.'],
 ['ACT VIII','The Pursuit','The truck dies beyond the gate. Guards and dogs spill onto the rain-soaked service road behind you.','Sprint through the barricades and reach the getaway lights.'],
 ['ESCAPED','Beyond Blackridge','Rain falls on the empty road. Behind you, the prison siren finally dies.','You escaped Blackridge Penitentiary.']
];
