// Persistent two-page creature journal. Entries reveal observations, then survival notes, then personal notes.

const SURVIVOR_JOURNAL_ENTRIES=[
 {id:'bash',name:'Bash',learn:'Bash announces itself with a heavy warning, chooses a straight lane, and charges. Once it commits, it does not keep turning after me.',survive:'Move sideways out of the lane before it arrives. Running straight away leaves me in its path. Solid walls stop Bash, so its charge has a physical limit.',note:'It commits completely. My mistake would be doing the same.'},
 {id:'purge',name:'The Purge',learn:'The Purge sweeps through rooms without respecting the walls. Bursting lights are the warning that it is approaching.',survive:'Get inside a wardrobe or closet before it reaches the room and remain there until it passes. Walls, tables, and ordinary corners are not substitutes for hiding. This is not Bash; sidestepping is not the plan.',note:'The walls belong to the hotel. Apparently, they let its machinery through.'},
 {id:'noise',name:'The Noise',learn:'It follows what it hears, not what it sees. Running, splashing, breaking objects, and creaking floors can raise the Noise Meter until a hunt begins.',survive:'Move quietly and crouch where the encounter supports it. During a hunt, another loud movement gives it a new location to investigate. The laundry chase is different: follow its escape route instead of assuming a locker will protect me.',note:'Silence is not proof that it has gone. Sometimes silence is what keeps it away.'},
 {id:'chef',name:'The Chef',learn:'The Chef moves around my position to attack from another side. His knives have a visible warning, and the same counter will not keep him in front of me.',survive:'Watch his throwing preparation, dodge or use solid cover, and exploit distractions while completing the kitchen objectives. The valves, freezer controls, and carts create the route to the elevator. Escape is the objective, not killing him.',note:'The elevator is the victory. Staying to prove anything would be a mistake.'},
 {id:'collector',name:'The Collector',learn:'The Collector protects its territory and possessions. A displaced valuable can become more important to it than the person who moved it.',survive:'Use designated luggage and valuables as distractions. Let it retrieve one object while moving another toward the exit. Follow the changing rules around the Pocket Watch; ordinary inventory items are not guaranteed distractions.',note:'It notices an empty shelf before it notices an empty room.'},
 {id:'clockmaker',name:'The Clockmaker',learn:'The Clockmaker moves in mechanical bursts synchronized with the tower beats. Pendulums, floor hazards, and clock controls all change when movement is safe.',survive:'Read the timing cues, obey the marked hiding beats, and complete the clock mechanisms. Constant sprinting is not a solution. Stopping the Master Clock creates the opportunity to leave.',note:'The quiet between the ticks is the only time that feels like mine.'},
 {id:'drowned-guest',name:'The Drowned Guest',learn:'The Drowned Guest approaches heavily and slowly, then makes sudden waterlogged surges. Slow movement is preparation, not permission to ignore it.',survive:'Activate the pumps and watch how falling water changes the routes. Keep away from warned bursts, including when it moves on land. Reach the exit and seal the bulkhead instead of remaining in the atrium.',note:'I thought taking away the water would take away the danger. It only changed how the danger moved.'},
 {id:'pursuer',name:'The Pursuer',learn:'The Pursuer aims ahead instead of simply following my footsteps. It wants to reach the place I am going.',survive:'Follow the illuminated chase route, jump hurdles, crouch beneath beams, and use marked switches and temporary barriers. Do not stop to search drawers. Each chase ends at a specific protected exit.',note:'It is not following my trail. It is trying to finish it.'},
 {id:'molly',name:'Molly',learn:'Molly is blind. Her face normally displays 00. Another number identifies the computer she is heading toward to hack. Her wire-hair flare reveals intent; it does not give her sight.',survive:'Crouch near active antenna intercoms. Use the noisy reception machine to collect a hacked computer code, leave while Molly investigates, and enter it at the matching terminal. Use controllers and shortcuts to reach and flick all three permanent exit levers.',note:'The number is a destination, not a password. And 00 does not mean safe.'},
 {id:'staircase-monster',name:'Staircase Monster',learn:'The Staircase Monster approaches in broad zigzags and can climb larger ledges. It does not follow the same narrow line I take through the shaft.',survive:'Keep moving along the intended staircase and parkour route. Watch the next landing before jumping. Gaining height alone does not end the chase because it can climb after me.',note:'The stairs are broken. Unfortunately, that inconveniences me more than it inconveniences it.'},
 {id:'cable-mass',name:'Cable Mass',learn:'Cable Mass gives a short warning before charging along a fast, winding path. It can pass through walls.',survive:'React to the warning and move clear of its approach. Do not rely on a wall or assume its charge stays in one narrow lane. No separate hiding method is confirmed.',note:'I cannot use the walls to predict where it will stop. It does not stop for them.'},
 {id:'ballroom-guest',name:'Ballroom Guest / Masked Guest',learn:'The six Guests do not all move alike. Some circle, some approach directly, and others reach tagging distance from another angle. Broken glass can reveal me.',survive:'Tag every Guest before one tags me. Use clear paths between the glass and read each movement pattern. Once tagged, a Guest freezes and leaves the round.',note:'A Guest standing still is only reassuring after I know I tagged it.'},
 {id:'watcher',name:'The Watcher',learn:'The Watcher stops completely when directly observed. Looking away gives it permission to move.',survive:'Locate it between statue interactions. Turn a statue, look back, stop its approach, and repeat. Its actual position matters more than how long I think I looked away.',note:'Every time I look back, the distance tells me what happened.'},
 {id:'water-creature',name:'Water Creature',learn:'The Water Creature swims with a continuous side-to-side motion. Connected deep water gives it a route between pools.',survive:'Use valves to create a dry crossing while separating its water route from mine. Before changing a valve, consider which pools become connected. Control where it can travel instead of racing it in water.',note:'A pool can look separate until one open channel makes it the same pool.'},
 {id:'gardener',name:'The Gardener',learn:'The Gardener patrols the maze and investigates audible footsteps. Moss muffles movement, but it does not make me invisible.',survive:'Watch its route, move between quiet moss patches, and use real cover when needed. Collect the three gate pieces. If a noisy crossing draws it in, be somewhere else when it arrives.',note:'The softest path is not always the shortest. I am learning to prefer it anyway.'},
 {id:'window-creature',name:'Window Creature',learn:'The Window Creature moves among six windows while I repeat a light sequence. A correct remembered switch is still dangerous when the creature occupies that window.',survive:'Remember the sequence, but check the creature before each switch. Wait for the required window to become safe. Its spawned form behaves differently: it waits before a sudden forward burst.',note:'Knowing which switch comes next is only half the answer.'},
 {id:'false-guest',name:'False Guest / Fake Guest',learn:'One impostor hides among five terrace Guests. Choosing it reveals the disguise and begins a chase.',survive:'Compare the evidence before selecting anyone. If exposed, use the reset route. Its spawned form also deceives: approaching, retreating, and circling from another side.',note:'I would rather trust a matching record than a convincing smile.'},
 {id:'giant-spider',name:'Giant Spider',learn:'The Giant Spider pursues me while throwing a red ball. Getting too close ends the attempt.',survive:'Keep a safe distance and use the bat to return the ball. Five successful returns complete the challenge. Watch the incoming ball and the spider at the same time.',note:'The ball is the chance to win. The spider is the reason I cannot stand still waiting for it.'},
 {id:'root-stalker',name:'Root Stalker',learn:'The Root Stalker follows through the Root Maze, but it cannot enter the Heart chamber.',survive:'Find the Heart chamber instead of trusting an ordinary corner. Its spawned version nearly stops when watched, but that behavior is separate from the maze escape objective.',note:'The Heart chamber is a boundary it respects. I will remember every boundary like that.'},
 {id:'luggage-warden',name:'The Luggage Warden',learn:'The Luggage Warden tries to occupy the route directly ahead of me instead of relying on a chase from behind.',survive:'Do not force forward into it. Watch the space it is moving to occupy and choose another available route. No permanent defeat method is confirmed.',note:'It does not need to catch up if I walk directly into its position.'},
 {id:'empty-porter',name:'The Empty Porter',learn:'The Empty Porter walks slowly, then periodically blinks across open floor. Its ordinary pace does not show how quickly it can close the distance.',survive:'Leave space to react and do not let the slow walk tempt me closer. Its blink makes distance unreliable. No way to disable that ability is confirmed.',note:'I checked the distance. Then it stopped being the distance.'},
 {id:'black-bellhop',name:'The Black Bellhop',learn:'The Black Bellhop rings in place before charging, then slows down to recover.',survive:'Treat the ringing as preparation. Make room to avoid the approach, then use the slower recovery to reposition. No permanent defeat method is confirmed.',note:'A bell is supposed to call someone over. This one tells me not to be there.'},
 {id:'reflection',name:'The Reflection',learn:'The Reflection answers my movement with an opposing, mirrored step while approaching. It can pass through walls.',survive:'Watch its response when changing direction. Walls are not dependable barriers, and an ordinary mirror is not a confirmed weapon. Its defeat condition remains unknown.',note:'It copies the movement without giving me the comfort of predicting the result.'},
 {id:'hotel-manager',name:'The Hotel Manager?',learn:'This figure moves toward the direction I am looking instead of simply approaching where I stand. It tries to occupy the route ahead.',survive:'Watch where it is heading before committing to that passage. No complete defeat method is established, and its title is not proof of identity.',note:'I have seen the office. I have seen the badge. Neither proves who is actually in charge.',design:'This movement record remains separate from the Fake Manager story reveal. Nothing here confirms that they are the same figure.'},
 {id:'night-auditor',name:'The Night Auditor',learn:'The Night Auditor alternates between sideways scanning and direct inspection. Its circling can become an approach.',survive:'Watch for the transition instead of assuming it will keep moving sideways. Leave room to change route. No specific item weakness is confirmed.',note:'It looks as though it is checking the room. I suspect I am the thing being checked.'},
 {id:'ransack',name:'Ransack',learn:'Ransack appears with a STOP instruction and a short countdown. This is a rule challenge, not an ordinary chase.',survive:'Release movement before the countdown ends. If I fail, collect the three glowing red marks to reopen the route. Failure creates another task; it does not immediately end the run.',note:'He threatens like he wants an ending. Then he hands me another challenge.'},
 {id:'elevator-boss',name:'The Elevator Boss',learn:'The Elevator Boss blocks the Grand Lift until the required key is handed over.',survive:'Find the Elevator Key, approach him, and deliberately complete the handoff. Carrying it is not enough. He is a gatekeeper, not something I need to fight.',note:'The one obstacle in this hotel that becomes reasonable after receiving the correct item.'},
 {id:'door-boss',name:'The Door Boss',learn:'The Door Boss guards an elevator route and waits for the correct key.',survive:'Complete the interaction and give him the key personally. Once the handoff is accepted, he opens the route.',note:'A locked door has become a person with instructions.'},
 {id:'vent-crawler',name:'The Vent Crawler',learn:'A pursuing threat follows through Jailbreak’s timed vent maze.',survive:'Keep navigating toward the maze exit and follow its route cues. No special weakness, attack pattern, or safe hiding method is confirmed.',note:'There is too little room here to learn by turning around.'},
 {id:'cellblock-guard',name:'The Cellblock Guard',learn:'The guard patrols and uses a searchlight. Its position and facing direction decide when crossing is dangerous.',survive:'Observe the patrol and use established openings. The stun baton belongs to this puzzle; it is not proof that the same tool works on supernatural creatures.',note:'A predictable patrol is still a threat. At least it gives me something to predict.'},
 {id:'pursuit-guards',name:'Pursuit Guards',learn:'These guards appear during Jailbreak’s final road escape.',survive:'Follow the escape route and its obstacle instructions. Their individual attack patterns are not recorded well enough to add a special counter.',note:'The route is the information I have. I should not mistake a guess for another instruction.'},
 {id:'watching-figures',name:'Watching Figures',learn:'Some dolls, mannequins, shadows, and other figures watch or move without beginning a damaging encounter.',survive:'Stay aware, but do not assume every unsettling figure needs a combat solution. These are atmospheric scares unless the game gives them an active pursuit behavior.',note:'Not everything that watches me is chasing me. Remembering that is harder than it should be.'}
];

const SURVIVOR_JOURNAL_OPINIONS={
 bash:'I almost respect how plainly it announces the danger. Almost.',
 purge:'This is the hotel at its cruelest: a warning, one correct shelter, and no negotiation.',
 noise:'It frightens me most when I catch myself blaming my own footsteps for what it chooses to do.',
 chef:'He treats the kitchen like a stage. I refuse to become the final course.',
 collector:'I do not think it loves its collection. I think it fears anything leaving.',
 clockmaker:'The rhythm is beautiful until I remember that it is measuring my mistakes.',
 'drowned-guest':'There is something sad beneath all that water, but sympathy is dangerous at close range.',
 pursuer:'It feels less like an animal and more like a bad ending trying to arrive early.',
 molly:'I cannot decide whether 00 is her resting face or the closest she comes to being calm.',
 'staircase-monster':'It looks awkward until it climbs. Then I remember that the awkwardness belongs to me.',
 'cable-mass':'I suspect the hotel made it from every wire someone thought they had safely hidden.',
 'ballroom-guest':'The game would almost be fun if losing did not mean being taken by a smiling stranger.',
 watcher:'It makes attention feel like a physical object I can drop.',
 'water-creature':'On dry stone it looks stranded. In connected water, I am the one out of place.',
 gardener:'The maze is cared for with more patience than any guest has ever received.',
 'window-creature':'Windows should show what is outside. These feel like places where something waits to be selected.',
 'false-guest':'The worst part is how badly I want one of the friendly faces to be real.',
 'giant-spider':'The red ball makes the encounter absurd, which somehow makes the spider more upsetting.',
 'root-stalker':'I think the Heart chamber refuses it for a reason. I am grateful without understanding why.',
 'luggage-warden':'It behaves like every route belongs to it and every traveler is misplaced baggage.',
 'empty-porter':'A missing face should make it less expressive. It does not.',
 'black-bellhop':'Every ring sounds professional, practiced, and completely hateful.',
 reflection:'I know it is not me. I still feel responsible whenever it moves.',
 'hotel-manager':'Anyone who needs the building itself to prove their authority probably does not possess much authority.',
 'night-auditor':'It has the patience of someone certain that every guest eventually has to settle an account.',
 ransack:'I resent that following one simple instruction can feel like surrender.',
 'elevator-boss':'He may be the closest thing here to honest hotel staff, which is not reassuring.',
 'door-boss':'I prefer a gatekeeper with a clear price to a creature with an unclear appetite.',
 'vent-crawler':'The vents make every sound intimate. I would rather not know how close it is.',
 'cellblock-guard':'A human threat can be understood, but understanding does not make the searchlight less bright.',
 'pursuit-guards':'They make the final road feel narrower every time I look back.',
 'watching-figures':'I keep telling myself they are only scenery. Scenery should not need convincing.'
};
for(const entry of SURVIVOR_JOURNAL_ENTRIES)entry.opinion=SURVIVOR_JOURNAL_OPINIONS[entry.id];

const JOURNAL_ENTRY_BY_ID=new Map(SURVIVOR_JOURNAL_ENTRIES.map(entry=>[entry.id,entry]));
const JOURNAL_KIND_ALIASES={spider:'giant-spider',root:'root-stalker','stair-monster':'staircase-monster','masked-guest':'ballroom-guest','fake-guest':'false-guest','the-purge':'purge','the-noise':'noise'};
const HOTEL_PLACE_DISCOVERIES=[
 {id:'forgotten-suite',name:'The Forgotten Suite',where:'ELECTRICAL RECEPTION · ROOM 217',copy:'This room was left off the corridor directory. Someone stayed long enough to pack, begin a letter, and cover one face in a photograph. The abandoned supplies were useful, but the missing name is the real discovery.'},
 {id:'maintenance-observation',name:'Maintenance Observation Room',where:'ELECTRICAL RECEPTION · SERVICE PANEL',copy:'The reinforced window overlooks Molly&apos;s reception route and its ordinary exits. It is useful for planning, but Molly can still enter the connected corridor and the room is not a hiding place.'},
 {id:'electrical-shortcut',name:'Maintenance Passage',where:'ELECTRICAL SECTION · RECEPTION RETURN',copy:'The maintenance door beside reception opens from the corridor side. I released its latch. It gives me a shorter route back to the code machine, but it does not disable Molly, hacked shutters, or the three main levers.'}
];
const HOTEL_PLACE_BY_ID=new Map(HOTEL_PLACE_DISCOVERIES.map(entry=>[entry.id,entry]));
let journalPaused=false,journalResumeLocked=false,journalPreviousFocus=null,journalSelectedId='opening';
let journalDiscoveries=(()=>{try{return JSON.parse(localStorage.getItem('hotel-survivor-journal-v1')||'{}')}catch{return{}}})();
let journalCurios=new Set((()=>{try{return JSON.parse(localStorage.getItem('hotel-survivor-curios-v1')||'[]')}catch{return[]}})());
let journalPlaces=new Set((()=>{try{return JSON.parse(localStorage.getItem('hotel-survivor-places-v1')||'[]')}catch{return[]}})());

function saveJournalDiscoveries(){localStorage.setItem('hotel-survivor-journal-v1',JSON.stringify(journalDiscoveries))}
function saveJournalCurios(){localStorage.setItem('hotel-survivor-curios-v1',JSON.stringify([...journalCurios]))}
function saveJournalPlaces(){localStorage.setItem('hotel-survivor-places-v1',JSON.stringify([...journalPlaces]))}
function journalDiscoverPlace(id){if(!HOTEL_PLACE_BY_ID.has(id)||journalPlaces.has(id))return false;journalPlaces.add(id);saveJournalPlaces();if(journalPaused)renderSurvivorJournal();return true}
function journalDiscoverCurio(id){if(!String(id).startsWith('curio-')||journalCurios.has(id))return false;journalCurios.add(id);saveJournalCurios();if(journalPaused)renderSurvivorJournal();return true}
function journalEntryId(kind=''){const normalized=String(kind).toLowerCase();return JOURNAL_KIND_ALIASES[normalized]||normalized}
function journalDiscover(kind,level=1){const id=journalEntryId(kind);if(!JOURNAL_ENTRY_BY_ID.has(id))return false;const next=Math.max(1,Math.min(3,level)),previous=Number(journalDiscoveries[id]||0);if(next<=previous)return false;journalDiscoveries[id]=next;saveJournalDiscoveries();if(journalPaused)renderSurvivorJournal();return true}
function journalLevel(id){return Number(journalDiscoveries[id]||0)}
function journalShowAdvice(){return document.querySelector('#journal-show-advice')?.checked||localStorage.getItem('hotel-journal-show-advice')==='true'}
function journalOpeningMarkup(){return`<div class="journal-opening"><span class="journal-page__number">NOTES FOR THE NEXT GUEST</span><h3>Hotel Nocturne</h3><div class="journal-opening__rule"></div><p>Not everything here can be defeated. Some things must be avoided. Some things must be distracted. Others will let you pass once you understand what they want.</p><p>I have written the rules I could confirm, the keepsakes I found, and a few opinions I probably should have kept to myself.</p><section><small>UNMAPPED AREAS</small><p>Several elevator plates contain blank positions below the known floors. I call them the <b>sub-floors</b>. I have not found an open route into them, so these pages make no claims about what is there.</p></section><blockquote>A blank space means I do not know.<br><br>It does not mean you are safe.</blockquote></div>`}
function journalCurioMarkup(){const rooms=hotelRunFloors.flatMap(floor=>floor.rooms),found=rooms.filter(def=>journalCurios.has(def.special.id));return`<span class="journal-page__number">ROOM KEEPSAKES · ${found.length} / ${rooms.length}</span><h3>Room Curios</h3><b class="journal-page__status">PERSISTENT ARCHIVE</b><p>Each numbered room contains one optional object. Finding it records it here permanently, even when the hotel run begins again.</p>${rooms.map(def=>journalCurios.has(def.special.id)?`<section><small>ROOM ${def.number} · ${def.roomName}</small><h4>${def.special.label}</h4><p>${def.special.copy}</p><blockquote>“${def.special.opinion}”</blockquote></section>`:`<section><small>ROOM ${def.number}</small><h4>UNKNOWN KEEPSAKE</h4><p class="journal-page__locked">I have not recorded the special item in this room.</p></section>`).join('')}<section><small>SUB-FLOORS</small><p class="journal-page__locked">Reserved as an unmapped future area. No rooms or rules have been confirmed.</p></section>`}
function journalPlacesMarkup(){return`<span class="journal-page__number">PLACES & DISCOVERIES · ${journalPlaces.size} / ${HOTEL_PLACE_DISCOVERIES.length}</span><h3>Places & Discoveries</h3><b class="journal-page__status">ROUTES I CONFIRMED</b><p>These notes record rooms and passages I actually found. A shortcut changes the route; it does not erase the danger.</p>${HOTEL_PLACE_DISCOVERIES.map(entry=>journalPlaces.has(entry.id)?`<section><small>${entry.where}</small><h4>${entry.name}</h4><p>${entry.copy}</p></section>`:`<section><small>UNDISCOVERED LOCATION</small><h4>UNKNOWN</h4><p class="journal-page__locked">I have not found enough evidence to record this place.</p></section>`).join('')}`}
function journalEntryMarkup(entry,level){
 if(!level)return`<span class="journal-page__number">CREATURE RECORD ${String(SURVIVOR_JOURNAL_ENTRIES.indexOf(entry)+1).padStart(2,'0')}</span><h3>UNKNOWN</h3><b class="journal-page__status">UNDISCOVERED</b><section><small>WHAT I LEARNED</small><p class="journal-page__locked">The page is blank. I have not encountered this creature.</p></section>`;
 const adviceUnlocked=level>=2||journalShowAdvice(),complete=level>=3,status=complete?'COMPLETE ENTRY':adviceUnlocked?'SURVIVAL NOTES AVAILABLE':'BASIC OBSERVATION';
 return`<span class="journal-page__number">CREATURE RECORD ${String(SURVIVOR_JOURNAL_ENTRIES.indexOf(entry)+1).padStart(2,'0')}</span><h3>${entry.name}</h3><b class="journal-page__status">${status}</b><section><small>WHAT I LEARNED</small><p>${entry.learn}</p></section><section><small>MY OPINION</small><p>${entry.opinion}</p></section><section><small>HOW TO SURVIVE</small><p class="${adviceUnlocked?'':'journal-page__locked'}">${adviceUnlocked?entry.survive:'I have not learned enough to trust any advice yet.'}</p></section>${complete?`<blockquote>“${entry.note}”</blockquote>${entry.design?`<p class="journal-page__design-note">${entry.design}</p>`:''}`:'<p class="journal-page__locked">The rest of the page is blank.</p>'}`
}
function selectJournalEntry(id,focusPage=false){journalSelectedId=id==='opening'||id==='curios'||id==='places'||JOURNAL_ENTRY_BY_ID.has(id)?id:'opening';const page=document.querySelector('#journal-entry-page');if(!page)return;page.innerHTML=journalSelectedId==='opening'?journalOpeningMarkup():journalSelectedId==='curios'?journalCurioMarkup():journalSelectedId==='places'?journalPlacesMarkup():journalEntryMarkup(JOURNAL_ENTRY_BY_ID.get(journalSelectedId),journalLevel(journalSelectedId));document.querySelectorAll('.journal-entry-button').forEach(button=>{const active=button.dataset.journalId===journalSelectedId;button.classList.toggle('active',active);button.setAttribute('aria-current',active?'page':'false')});page.scrollTop=0;if(focusPage)page.focus({preventScroll:true})}
function renderSurvivorJournal(){
 const list=document.querySelector('#journal-entry-list');if(!list)return;list.replaceChildren();const opening=document.createElement('button');opening.className='journal-entry-button';opening.dataset.journalId='opening';opening.innerHTML='<i>✎</i><span>Opening Page</span><small>READ</small>';opening.onclick=()=>selectJournalEntry('opening');list.append(opening);
 const curios=document.createElement('button');curios.className='journal-entry-button';curios.dataset.journalId='curios';curios.innerHTML=`<i>◇</i><span>Room Curios</span><small>${journalCurios.size} / 12</small>`;curios.onclick=()=>selectJournalEntry('curios');list.append(curios);
 const places=document.createElement('button');places.className='journal-entry-button';places.dataset.journalId='places';places.innerHTML=`<i>⌘</i><span>Places & Discoveries</span><small>${journalPlaces.size} / ${HOTEL_PLACE_DISCOVERIES.length}</small>`;places.onclick=()=>selectJournalEntry('places');list.append(places);
 SURVIVOR_JOURNAL_ENTRIES.forEach((entry,index)=>{const level=journalLevel(entry.id),button=document.createElement('button');button.className=`journal-entry-button${level?'':' unknown'}`;button.dataset.journalId=entry.id;const number=document.createElement('i'),name=document.createElement('span'),status=document.createElement('small');number.textContent=level?String(index+1).padStart(2,'0'):'';name.textContent=level?entry.name:'UNKNOWN';status.textContent=level>=3?'FULL':level>=2?'NOTES':level?'SEEN':'—';button.append(number,name,status);button.onclick=()=>selectJournalEntry(entry.id);list.append(button)});
 document.querySelector('#journal-discovery-count').textContent=`${SURVIVOR_JOURNAL_ENTRIES.filter(entry=>journalLevel(entry.id)).length} / ${SURVIVOR_JOURNAL_ENTRIES.length}`;selectJournalEntry(journalSelectedId)
}
function journalTypingTarget(target){return Boolean(target&&(['INPUT','SELECT','TEXTAREA'].includes(target.tagName)||target.isContentEditable))}
function setFieldJournal(open=!journalPaused){
 const journal=document.querySelector('#survivor-journal'),button=document.querySelector('#journal-toggle');if(!journal)return false;
 if(open){if(journalPaused||dlg.open||intro.open||document.body.classList.contains('admin-open'))return false;syncJournalDiscovery();journalResumeLocked=controls.isLocked;journalPreviousFocus=document.activeElement;journalPaused=true;clearTimeout(hudCompactHandle);hudRevealToken++;document.body.classList.remove('hud-compact');document.body.classList.add('journal-open');journal.hidden=false;button?.setAttribute('aria-expanded','true');renderSurvivorJournal();controls.unlock();document.querySelector('#journal-close')?.focus({preventScroll:true});return true}
 journalPaused=false;document.body.classList.remove('journal-open');journal.hidden=true;button?.setAttribute('aria-expanded','false');if(storySelect.hidden)revealStoryHud();if(journalResumeLocked&&!dlg.open&&!intro.open&&storySelect.hidden)setTimeout(()=>controls.lock(),0);else journalPreviousFocus?.focus?.({preventScroll:true});return true
}

function syncJournalDiscovery(){
 const mark=(id,level=1)=>journalDiscover(id,level),adminKinds=new Set((adminMonsters||[]).map(monster=>journalEntryId(monster.type)));for(const id of adminKinds)mark(id,1);
 if(eviction){mark('purge',eviction.phase==='dormant'?1:2)}if(sessionStorage.getItem('infinite-hotel-purge-complete-v1')==='true'||hotelRunItems.has('purge-survived'))mark('purge',3);
 if(noise||hotelNoiseArc){const run=noise||hotelNoiseArc;mark('noise',run.phase==='quiet'?1:2)}if(hotelRunItems.has('noise-survived')||floorOne)mark('noise',3);
 if(floorOne){if(floorOne.phase===2)mark('noise',floorOne.huntTimer>0||floorOne.noise>0?2:1);if(floorOne.phase>2)mark('noise',3);if(floorOne.phase===4)mark('cable-mass',floorOne.elevation?.timer<44?2:1);if(floorOne.phase>4)mark('cable-mass',3);if(floorOne.phase===10)mark('chef',floorOne.chefTriggered?2:1);if(floorOne.phase>10||floorOne.chefStage==='survived')mark('chef',3)}if(hotelProgress.has('floor-one-checkout'))mark('chef',3);
 if(collector){mark('collector',collector.carrying||collector.slots?.length||collector.phase>1?2:1);if(collector.complete)mark('collector',3)}
 if(clockmaker){mark('clockmaker',clockmaker.phase>1?2:1);if(clockmaker.complete)mark('clockmaker',3)}
 if(drowned){mark('drowned-guest',drowned.phase>1||drowned.pumps?.length?2:1);if(drowned.complete)mark('drowned-guest',3)}
 if(pursuer){mark('pursuer',pursuer.scene>0||pursuer.phase>1?2:1)}if(pursuerCompletedScenes.size)mark('pursuer',pursuerCompletedScenes.size>=6?3:2);
 if(molly){mark('molly',molly.hacked?.length||molly.collectedCodes?.length||molly.levers?.length?2:1);if(molly.finalUnlocked||molly.complete)mark('molly',3)}
 if(hotelStairMonster){mark('staircase-monster',hotelStairMonster.visible?2:1)}if(hotelProgress.has('floor-five-arrival')||floorFive)mark('staircase-monster',3);
 if(floorTwo){const phaseRecords=[[6,'ballroom-guest',floorTwo.ballroomTagged?.length],[7,'watcher',floorTwo.watcherStatues?.length],[10,'gardener',floorTwo.gardenPieces?.length],[11,'window-creature',floorTwo.windowProgress||floorTwo.windowRound],[12,'false-guest',floorTwo.falseGuestSelected?.length||floorTwo.falseGuestChase]];for(const [phase,id,learned] of phaseRecords){if(floorTwo.phase===phase)mark(id,learned?2:1);else if(floorTwo.phase>phase)mark(id,3)}}if(hotelProgress.has('floor-two-room140'))for(const id of ['ballroom-guest','watcher','gardener','window-creature','false-guest'])mark(id,3);
 if(combat||creatureModel||room===6&&!inLobby)mark('giant-spider',combat?.hits?2:1);if(saved[6])mark('giant-spider',3);
 if(rootChaser||chaseState||room===7&&!inLobby)mark('root-stalker',chaseState?.safe?2:1);if(saved[7])mark('root-stalker',3);
 if(ransack.phase!=='waiting'||ransack.appearances>0)mark('ransack',ransack.phase==='marks'||ransack.appearances>1?2:1);if(ransack.phase==='cooldown'&&ransack.appearances>0)mark('ransack',3);
 if(floorFive?.phase==='boss'||floorFive?.items?.has('key-given'))mark('elevator-boss',floorFive.items.has('key-given')?3:1);if(noise?.boss||hotelRunItems.has('noise-door-open'))mark('door-boss',hotelRunItems.has('noise-door-open')?3:1);
 if(inJailbreak&&jailbreakStage===0)mark('cellblock-guard',jailbreakGuardLap>0?2:1);if(jailbreakStage>0)mark('cellblock-guard',3);if(document.querySelector('#puzzle-title')?.textContent.includes('CRAWLING')||jailbreakItems.has('vent-maze'))mark('vent-crawler',jailbreakItems.has('vent-maze')?3:1);if(inJailbreak&&jailbreakStage===7)mark('pursuit-guards',2);if(jailbreakStage>7)mark('pursuit-guards',3);
 if((dolls?.length||horrorProps?.length)&&!inLobby)mark('watching-figures',1)
}

document.querySelector('#journal-toggle')?.addEventListener('click',event=>{event.stopPropagation();setFieldJournal()});
document.querySelector('#journal-close')?.addEventListener('click',()=>setFieldJournal(false));
document.querySelector('#journal-show-advice')?.addEventListener('change',event=>{localStorage.setItem('hotel-journal-show-advice',String(event.currentTarget.checked));selectJournalEntry(journalSelectedId)});
document.querySelector('#journal-show-advice').checked=localStorage.getItem('hotel-journal-show-advice')==='true';
document.querySelector('#survivor-journal')?.addEventListener('pointerdown',event=>{if(event.target.id==='survivor-journal')setFieldJournal(false)});
addEventListener('keydown',event=>{if(journalPaused&&(event.code==='KeyJ'||event.code==='Escape')){event.preventDefault();event.stopImmediatePropagation();setFieldJournal(false);return}if(event.code!=='KeyJ'||event.repeat||journalTypingTarget(event.target)||dlg.open)return;event.preventDefault();event.stopImmediatePropagation();setFieldJournal(true)},true);
setInterval(()=>{if(!journalPaused)syncJournalDiscovery()},600);
